### ISSUE TITLE
staradmin -start db is not completely functional

### ISSUE THREAD

**Issue by habib535** [Starcounter/Home#446] opened 2018-09-27 13:35 UTC
Starcounter version: `2.4.990.168`.

### Issue type

- [x] Bug

### Issue description
I created a starpack and installed it to `default database`
`starpack -i Launchpad-2.1.2.zip -d=default`

I set the application `Auto-Start` to ON, which means whenever this database will be started the app will also start.

When I start the database from Starcounter Administrator UI it also starts the app but if I start the database using CLI (`staradmin --database=Default start db`) it fails.

### Exception stack trace

Nothing is logged, only this message appears next to database.
```
Not all installed applications is running.
```

**Comment by miyconst** [comment] 2018-10-11 08:40
@per-samuelsson please add it to your issue-pipe-line with mid-low priority.

**Comment by per-samuelsson** [comment] 2018-10-11 08:54
> @per-samuelsson please add it to your issue-pipe-line with mid-low priority.

Add what? This is not a bug IMO, since this feature has never been supported by either tooling or the actual admin server. 

I'm guessing this is functionality added to web admin and/or starpack, and I have never been involved in any of that. So I'd rather not have it assigned to me unless it's very clear that

1) This is an enhancement that need to be added to L1
2) This is code / functionality I don't have any idea of how it's supposed to work

**Comment by miyconst** [comment] 2018-10-11 08:59
>When I start the database from Starcounter Administrator UI it also starts the app but if I start the database using CLI (`staradmin --database=Default start db`) it fails.

As far as I understood @habib535, `staradmin` fails to start the database. Which should not happen with or without automatic app startup.

@habib535 am I wrong?

**Comment by habib535** [comment] 2018-10-11 10:16
The database starts but apps are not starting automatically. This might seems a low priority bug but it annoys when you have to switch from scripts to UI and perform this operation there.

**Comment by miyconst** [comment] 2018-10-12 11:14
>The database starts but apps are not starting automatically. This might seems a low priority bug but it annoys when you have to switch from scripts to UI and perform this operation there.

Then it's a known limitation and won't be fixed in Starcounter Odessa (2.4).

The database and the apps have to be started manually when using CLI.

**Closed by miyconst** 2018-10-12 11:14 UTC
Labels: bug, tools, tools-cli
