### ISSUE TITLE
TypedJson: Derived properties are not exposed in ToJson()

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#227] opened 2017-09-05 12:58 UTC
During work under Calendar app rewriting I've found behavior that is not described in docs and can be seen as a bug. 
I have base view-model class (`EventBasePage`) and a class that inherits from it - `EventPage`. Base class has declared property in typed json called `Start$`, but it doesn't exist in client view-model. Further investigation by me and @joozek78 showed that origin of this problem is that **`Start$` property doesn't show up in Exposed properties list (`DefaultTemplate.Properties.ExposedProperties`)**. It is present in `DefaultTemplate.Properties`, though.

Here is additional example for better understading of this problem:

A.json
```json
{
  "Start$": ""
}
```
A.json.cs
```c#
public class A: Json
{
  public string Start => "abc";
}
```
B.json
```json
{}
```
B.json.cs
```c#
public class B : A
{
    public void Test()
    {
        Trace.Assert(this.ToJson().Contains("Start$")); // fails
    }
}
```

You can see the actual code here: https://github.com/StarcounterApps/Calendar/pull/81/commits/0792c4a6f2b5d882b78faae14584077ecbfa9180

**Comment by joozek78** [comment] 2017-09-05 13:18
@chrhol can you take a look?

**Comment by joozek78** [comment] 2017-09-05 13:59
Is it described somewhere? It seems strange - one could expect rules like C# inheritance (you don't need to "expose" inherited members)

**Comment by chrhol** [comment] 2017-09-05 14:07
> Is it described somewhere?

Probably not. This was discussed and implemented ages ago, and I think this might be the first time inheritance is used anywhere (except perhaps in some test). Might be a good candidate for review (among other stuff of course).

**Comment by miyconst** [comment] 2017-12-15 08:18
Related - [Extend inheritance between view-models](https://github.com/Starcounter/Home/issues/294).

**Comment by atifwaqar** [comment] 2018-02-22 10:54
@PatrykSzwer. I'm not sure if my solution will solve your exact issue, but I have a feeling that you might benifit from this info.

Do you aim to use `Start$` in your viewModel (i.e. you'd like to see & access `Start$` in Starcounter Debug Aid), without declaring it in `B.json`?

I am working on similar stuff, and I faced the same issue. here is how I got it to work.
A.json
```
{
  "InheritedViewModel" : {
      "Start$": ""
   }
}
```
A.json.cs
```
    partial class A : Json
    {
    }

    [A_json.InheritedViewModel]
    partial class InheritedViewModel : Json
    {
        public string Start => "abc";
    }
```

B.json
```
{
  "InheritedViewModel" : { }
}
```

B.json.cs
```
    partial class B : A
    {
    }
```

my handler code looks like this 
```
            Handle.GET("/t", (Request r) =>
            {
                    return Db.Scope(() =>
                    {
                        B B_Page = new B();
                        return B_Page;
                    });
            });
```

and my SDA looks like this : 
![image](https://user-images.githubusercontent.com/4388707/36534460-e3bd6234-17c6-11e8-8457-63f57d6d2a65.png)


Let me know if this helped or if its even related to what you asked :)

**Comment by PatrykSzwer** [comment] 2018-02-22 16:31
I'm no longer onto that, but thank you for proposing an interesting solution! If I'll step on this again, I'll remember to check your approach.

**Comment by miyconst** [comment] 2019-12-06 11:12
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:12 UTC
Labels: json, json-typed, question, won’t fix
