### ISSUE TITLE
Administrator SQL Panel: Find object by ObjectNo

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#96] opened 2017-04-28 07:25 UTC
I'd like to have a feature where I could just put in ObjectNo / Key and get the object contents along with its type. Some projects don't use Simplified, so querying `Something` isn't always a viable option. Also, normal query doesn't return object type.

**Comment by Mihaiii** [comment] 2017-11-01 23:08
This will be done in 2.4. using `MotherOfAllLayouts`.

**Comment by Mihaiii** [comment] 2018-01-29 21:37
Given https://github.com/Starcounter/level1/issues/4210#issuecomment-297365991 and https://github.com/Starcounter/level1/issues/4463#issuecomment-361222186, we have:

`The ObjectNo, which is a number, should be used to identify objects`, but I can't use `like` operator on ints (we don't support implicit conversion, `cast`/`convert`, afaik).
I tested returning `true` [here](https://github.com/Starcounter/level1/blob/develop/src/Starcounter.QueryProcessor/Query/Execution/Enumerators/ReferenceLookup.cs#L282) to see if it fixes the issue and it does, but 
1. It's code that shouldn't be on production because it's a ugly workaround. After having a look at MOAL, I have absolutely no intention in trying to dig into this any further (I would be way over my head).
2. Can't be 100% certain that it doesn't have unintended side effects as I'm not familiar with the code.

Also, we don't support `union all` operator.

Therefore, I'm removing this card from Odessa and I'm moving it to Vilnius.

**Comment by miyconst** [comment] 2019-12-06 11:08
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:08 UTC
Labels: enhancement, nice to have, tools, tools-admin-ui, won’t fix
