### ISSUE TITLE
Db.SQL query that returns non-database return type

### ISSUE THREAD

**Issue by habib535** [Starcounter/Home#335] opened 2017-12-08 13:14 UTC
I have the following SQL query which gives me some stats.

```cs
var subcriptionStats = Db.SQL(
	"SELECT MIN(s.StartDate) MinStartDate, COUNT(s) CustomersCount, MAX(s.EndDate) MaxEndDate " +
	$"FROM {typeof(Subscription)} s " +
	"GROUP By s.Customer");
```

By default, Db.SQL returns an `object`, if we want to specify a type it has to be a database class. So I converted each object to `Starcounter.Query.Execution.Row` and then using reflection fetched each property. It took me a lot of time to find out this way but I am more interested in looking for a standard approach here as our documentation contains only samples where `Db.SQL` returns a Database class or single value.

```cs
foreach (var item in subcriptionStats)
{
	var dbObj = (Starcounter.Query.Execution.Row)item;
	
	var minStartDate = dbObj.GetValue("MinStartDate");
	var customersCount = dbObj.GetValue("CustomersCount");
	var maxEndDate = dbObj.GetValue("MaxEndDate");
}
```

**Comment by bigwad** [comment] 2017-12-08 14:13
You seem to find a correct way of retrieving columns. There is more performant approach when you call one of `GetXXX(int index)` method instead of `GetValue`, where `XXX` is a type you're expecting and the `index` is a 0-based column number.

**Comment by per-samuelsson** [comment] 2017-12-08 14:59
Maybe we can start supporting returning `System.Tuple`? Something like:

```csharp
var tuples = Db.SQL<Tuple<DateTime, int>>(
                    "SELECT MIN(s.StartDate) MinStartDate, COUNT(s) CustomersCount ...");
```

**Comment by mmnosek** [comment] 2017-12-13 12:29
> Maybe we can start supporting returning System.Tuple?

I think it would help a lot. I received this question couple times and forcing a developer to write a lot of code to do this isn't reasonable.

Who can tell if we can implement support for this and how can we move forward? @miyconst ? Thumb ups are not bringing us closer ;)

**Comment by Mackiovello** [comment] 2017-12-13 12:35
It would be even nicer to use `System.ValueTuple`, but that doesn't work in the old weaver: https://github.com/Starcounter/Home/issues/166

**Comment by miyconst** [comment] 2017-12-13 12:35
Okay, I accept the issue as `nice to have`, and maybe @un-tone will be able to get his hands on it after fixing the urgent bugs.

**Comment by un-tone** [comment] 2018-03-01 15:36
Closing as done.

**Comment by Mackiovello** [comment] 2018-03-02 10:02
Good that this is in place! One more thing though, it still has to be documented. This section should be adapted to these changes: https://docs.starcounter.io/v/2.4/guides/database/querying-using-sql#return-types

Can you write out how this works now and what versions it applies to? Please write down any possible pitfalls when using it too. If you can, a code snippet would be nice.

**Comment by un-tone** [comment] 2018-03-02 14:55
The `Db.SQL<T>` method supports Tuple result types. You can use it for aggregations and just for properties.

```cs
Db.SQL<Tuple<long>>("SELECT MAX(p.Age) FROM Person p GROUP BY p.Gender");
Db.SQL<Tuple<int, short?, byte?>("SELECT p.Age, p.Height, p.Weight FROM Person p");
```

The tuple argument should be consistent with the type of the corresponding property. Type casting is supported only for the types which can be casted implicitly.

For queries with more than 7 properties, you should use nested tuples.

```cs
Db.SQL<Tuple<int, int, int, int, int, int, int, Tuple<int, int>>>(
    "SELECT p.Attr1, p.Attr2, p.Attr3, p.Attr4, p.Attr5, p.Attr6, p.Attr7, p.Attr8, p.Attr9 FROM Person p");

Db.SQL<Tuple<int, int, int, int, int, int, int,
             Tuple<int, int, int, int, int, int, int,
                   Tuple<int, int, int, int>>>>(
    "SELECT p.Attr1, p.Attr2, p.Attr3, p.Attr4, p.Attr5, p.Attr6, p.Attr7, p.Attr8, p.Attr9, p.Attr10, " +
    "p.Attr11, p.Attr12, p.Attr13, p.Attr14, p.Attr15, p.Attr16, p.Attr17, p.Attr18 FROM Person p");
```

This feature is supported in Starcounter v2.4

**Comment by un-tone** [comment] 2018-03-02 14:56
@Mackiovello please check it

**Comment by Mackiovello** [comment] 2018-03-05 08:00
Thank you @un-tone! Documented here: https://docs.starcounter.io/v/2.4/guides/database/querying-using-sql#return-types

**Comment by bigwad** [comment] 2018-10-26 20:53
We have to recheck performance implications. I was trying to use `Tuple<string,string>` instead of accessing `Row.GetItem` and tuple version was 10 times slower. Lookup is indexed and returns only one row. As a result tuple instantiation dominated query execution time. I suspect the problem is with tuple activator cache that is recreated each time we run a query.

**Comment by un-tone** [comment] 2019-04-08 15:49
Fixed the issues.

**Closed by un-tone** 2019-04-08 15:49 UTC
Labels: enhancement, nice to have, qp, qp-old
