### ISSUE TITLE
Improve logging, error reporting, diagnostrics

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#194] opened 2017-08-04 18:39 UTC
Whenever you as a developer do something wrong it is more often than not, very very hard to find out what is wrong.

Examples:
* Missing wwwroot folder
The vs.net template doesn't have one and the documentation talks about a "recommended structure".
Obvious for those who know, not for those who don't.
There is no log stating this is a problem, there is nothing in the client console etc.

* Writing to Non-writable properties (`myprop$` vs `myprop`)
This will fail clientside with a message about the websocket error and bad message framing.

* `public void Handle(input.xxx)`
Typed Json when writing the codebehind,
If you wrongly create a handler with a `public` modifier, there is no compiletime error, log error or other notification that can lead you on the right track.

There are more cases where new developers are left hanging.

Personally, I'd very much like to see some major effort in this area as it will benefit adoption and lower the support burden and on-boarding of new developers or teams.

**Comment by miyconst** [comment] 2019-12-06 11:10
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:10 UTC
Labels: enhancement, errors, errors-reports, nice to have, won’t fix
