### ISSUE TITLE
2.4.0.5327 Can't start server

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#392] opened 2018-03-12 09:26 UTC
Starting server is impossible neither with `staradmin start server` nor `star <app.exe>`. It results in an exception:

```
Starting server (starting server)                                                                            
ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation.
Version: 0.0.0.
Help page: https://docs.starcounter.io/?q=SCERR10007.

Type "star -h" or "staradmin -h" to see help

Stack trace:
   at Starcounter.Server.ServerServiceProcess.WaitUntilServerIsOnlineOrSignalExit[T](Func`2 checkExited, T context) in C:\TeamCity\BuildAgent\work\sc-15753\Level1\src\Server\Starcounter.Server\ServerServiceProcess.cs:line 211
   at Starcounter.CLI.StartServerCLICommand.RunWithinContext() in C:\TeamCity\BuildAgent\work\sc-15753\Level1\src\Server\Starcounter.CLI\StartServerCLICommand.cs:line 53
   at Starcounter.CLI.StartServerCLICommand.Run() in C:\TeamCity\BuildAgent\work\sc-15753\Level1\src\Server\Starcounter.CLI\StartServerCLICommand.cs:line 40
[10:23:27, Starcounter (service)]
Process exitcode: 1

[10:23:27, Starcounter (service)]
ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation.```

Looks like a showstopper

**Comment by miyconst** [comment] 2018-03-12 10:05
Was this issue introduced with the `2.4.0.5327` build or it's related to an existing database?

**Comment by joozek78** [comment] 2018-03-12 10:08
It isn't related to any preexising database data. It was actually first found in the CI tests (which reconstruct the database)

**Comment by miyconst** [comment] 2018-03-12 12:42
I have reproduced the issue, looking for the culprit.

**Comment by joozek78** [comment] 2018-03-12 15:13
Offending release was removed from downloads page and marked as failed in TC (so that it doesn't use it in the apps tests)

**Comment by miyconst** [comment] 2018-03-12 17:21
@iqbalskd the crashing process is the tray icon, please investigate.

**Comment by iqbalskd** [comment] 2018-03-13 11:31
This issue is not related to TrayIcon.exe, the `scservicelib` is throwing an error on the following line: 

https://github.com/Starcounter/level1/blob/032f4ef964fb350a58020ffa9f72cd64a20a39c0/src/scservicelib/main.cpp#L662

**Comment by miyconst** [comment] 2018-03-13 11:51
@iqbalskd thank you for the investigation, looks like it's @alemoi's area.

**Comment by alemoi** [comment] 2018-03-13 14:32
Not mine @miyconst  :)

```
alemoi@ALEMOI c:\github\level1\bin\Release
$ scservice
Starting Starcounter PERSONAL engine...
Press CTRL-C to exit.

Reading server configuration from: C:\Users\alemoi\Documents\Starcounter\Personal\PERSONAL.server.config
Reading gateway configuration from: C:\Users\alemoi\Documents\Starcounter\Personal\scnetworkgateway.xml
System.IO.FileNotFoundException: Could not load file or assembly 'Starcounter.BluestarFFI, Version=2.2.0.0, Culture=neutral, PublicKeyToken=725f045760708bb7' or one of its dependencies. The system cannot find the file specified.
   at Starcounter.Hosting.Dependencies..ctor()
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.SetupQueryProcessorStubs() in C:\TeamCity\BuildAgent\work\sc-15843\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 142
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 configProvider, Func`1 appStartProvider) in C:\TeamCity\BuildAgent\work\sc-15843\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 133
   at Starcounter.Hosting.RuntimeHosts.Shared.AppSharedRuntimeHost.Run(Func`1 configProvider, Func`1 autoStartProvdier) in C:\TeamCity\BuildAgent\work\sc-15843\Level1\src\Starcounter.Hosting\RuntimeHosts\Shared\AppSharedRuntimeHost.cs:line 19
FileName=Starcounter.BluestarFFI, Version=2.2.0.0, Culture=neutral, PublicKeyToken=725f045760708bb7
FusionLog=WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

HResult=-2147024894

7EDE1D87-8181-4B1C-B1DF-CB939706F8CF--FC8F607939BC-FD1B-C1B4-1818-78D1EDE7Could not load file or assembly 'Starcounter.BluestarFFI, Version=2.2.0.0, Culture=neutral, PublicKeyToken=725f045760708bb7' or one of its dependencies. The system cannot find the file specified.
7EDE1D87-8181-4B1C-B1DF-CB939706F8CF--FC8F607939BC-FD1B-C1B4-1818-78D1EDE7Error: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation.
Please review server log in: C:\Users\alemoi\Documents\Starcounter\Personal\Logs
```

**Comment by alemoi** [comment] 2018-03-13 14:35
Someone forgot to white list the `Starcounter.BluestarFFI.dll`?

**Comment by Mackiovello** [comment] 2018-03-13 14:44
> Someone forgot to white list the Starcounter.BluestarFFI.dll?

It's a NuGet package. Does it have to be manually white-listed? In that case, it's my bad

**Comment by Mackiovello** [comment] 2018-03-13 14:47
I've learned something new today. It would be nice if this could be caught by a test or something like that.

**Comment by Mackiovello** [comment] 2018-03-13 14:50
PR in https://github.com/Starcounter/level1/pull/4547

Running a build and then merging

**Comment by Mackiovello** [comment] 2018-03-13 15:26
Fixed in https://github.com/Starcounter/level1/pull/4547

**Closed by Mackiovello** 2018-03-13 15:26 UTC
Labels: bug, investigate, required

**Comment by ubbeK** [comment] 2018-03-13 22:08
This is exactly how the old build system works, especially how the Installer works

* build everything to StarcounterBin
* test everything
* run whitelist on StarcounterBin
* generate installer with StarcounterBin binaries


There is an issue about [smoke testing the installer](https://github.com/Starcounter/AdminTrack/issues/340), where @per-samuelsson comment would be a full test:

> Just to be perfectly clear what I think we miss to begin with is this:
> 
> 1. Build Starcounter and generate an installer.
> 2. Run that installer with default settings.
> 3. Create a new skeleton app and bring down one of our sample apps.
> 4. Rebuild those apps (with Starcounter now installed).
> 5. Start those apps.
> That would probably be enough to catch quite a few things we haven't tested already. How to set it up technically is (or if you want to alter that sequence) is o/c totally up to you.


Today this could be added through another test step after generating the installer but as always, I don't want to continue developing the old build environment with the monolithic build scripts.

**Comment by miyconst** [comment] 2018-03-14 09:16
>The new TeamCity setup will separate the entire Installer steps to its own build, so it can be tested properly before uploading it.

Okay, waiting for it.
