### ISSUE TITLE
Stackoverflow when binding a child to Data and setting it to null.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#150] opened 2017-06-13 12:56 UTC
Running the following sample will cause a stackoverflow:

**TestJson.json**
```javascript
{
  "Child": {
     "Text": ""
   }
}
```

**TestJson.json.cs**
```csharp
partial class TestJson : Json {
    static TestJson() {
        DefaultTemplate.Child.Bind = "Data";
    }
}
```

**Program.cs**
```csharp
public class Test {
    public string Text { get; set; }
}

class Program {
    static void Main() {
        var testJson = new TestJson();
        testJson.Data = new Test();
        string tmp = testJson.Child.Text;
        testJson.Data = null;
    }
}
```

**Comment by miyconst** [comment] 2019-12-06 11:09
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:09 UTC
Labels: bug, json, json-typed, required, won’t fix
