### ISSUE TITLE
Upgrade failed - Redistributable 2017 error

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#430] opened 2018-07-25 13:53 UTC
I try to upgrade from `2.4.990.120` to `2.4.990.122`. 
Communicate shows: “Microsoft Visual Studio Redistributable 2017 is not detected (…) It will be installed now”
When I hit “OK”,  I have this immediately: `Starcounter setup failed. Returned error code: 1638. Error: Installation of Microsoft Redistributable failed`

**Comment by miyconst** [comment] 2018-08-07 10:34
@iqbalskd could you please follow up?

**Comment by miyconst** [comment] 2018-08-14 12:42
@mmnosek could you please validate the answer from @iqbalskd?

**Comment by iqbalskd** [comment] 2018-08-14 12:59
Even an easier step to reporduce:

1. Uninstall all versions of VC++Redistributable
2. Install [VC++ Redistributable 2017](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
3. Try Installing any version of Starcounter.
@mmnosek

**Comment by mmnosek** [comment] 2018-08-17 10:37
I confirm. So it's not our bug. I know more people have encoutered this. Can we add some information somewhere? In the installer? In the docs? On the downloads page? @miyconst @Mackiovello wdyt?

**Comment by Mackiovello** [comment] 2018-08-17 11:29
I think people will find this issue pretty fast if they hit it which explains it. Don't think it's a good idea to add to the installer or something like that

**Comment by miyconst** [comment] 2018-08-17 11:40
I am with @Mackiovello on this. If we add anything extra for it, then we will have to keep track of the VS issue and remove that "extra" thing once the VS issue is resolved.

**Comment by bigwad** [comment] 2018-08-17 12:25
>I confirm. So it's not our bug.

How is that? Microsoft closed the mentioned issue with a resolution "Closed - Not a Bug". So, no reason to wait for MS to fix it. We have to accept it and fix on our side.

**Comment by miyconst** [comment] 2018-08-17 13:07
@bigwad is not it what the MS representative says after closing the issue?

>We are aware (and acknowlege) the issues that occur with the current behavior related to attempted downgrades and we are looking into changes to the VC++ redistributable bundle that could be made to allow us to avoid these issues in the future.

**Comment by mmnosek** [comment] 2018-08-17 13:31
> How is that?

I didn't check Microsoft, just acknowledged information from @iqbalskd and @miyconst. I am not knowledgeable enough to debug it myself.

> Should I also say, that installer is the face of a product?

I agree 120%. I am all for the installer that does its job smoothly.

**Comment by iqbalskd** [comment] 2018-08-20 16:29
Changed the VC++ Restributable to 14.15.x.x on the FTP 

\\scbuildserver\FTP\SCDev\ThirdParty\VCRedistSetups\VS2017

**Comment by iqbalskd** [comment] 2018-08-30 11:53
Closing this as done

**Closed by iqbalskd** 2018-08-30 11:53 UTC
Labels: bug, packaging, windows
