### ISSUE TITLE
Binding of nested property issue.

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#142] opened 2017-06-02 12:15 UTC
During implementation of features for starcounter app [Calendar](https://github.com/StarcounterApps/Calendar) I've engaged an issue with binding properties.

I wanted to replace old bind way with new, direct binding:
before:
(view-model)
`"$Enabled$": { "Bind" : "_Enabled" },
"Enabled$": false,`
(json.cs file)
`public bool _Enabled
        {
            get
            {...`
after:
(view-model)
`"Enabled$": false,`
(json.cs file)
`public bool Enabled
        {
            get
            {...`
Theoretically everything should work, but instead, I'm getting error: 

> Error	CS0229	Ambiguity between 'EventGroups.Enabled' and 'EventGroups.Enabled'

Commit with bug can be found here: https://github.com/StarcounterApps/Calendar/pull/57/commits/20a9840a6a68aec8da72f0dcbc60dff3ab5e93a0

CC: @chrhol

**Comment by chrhol** [comment] 2017-06-02 12:50
I think this is a combination of two things: 
1. The msbuild task that generates code in the background for TypedJSON is only triggered when the json or code-behind file is saved.
2. VS seems to have some in-memory cache (or something similar) for the intellisense that sometimes is not properly updated when doing certain changes.

In this case you get this error reported design-time (I assume, at least I got it when trying to reproduce), but doing a build works fine.

When doing this change, there are two different properties with the same name that exists for a while: the property in code-behind and the property in the generated file. When the code-behind file is saved, the generated file changes and no longer generates this property.

Could you verify this? That running a build works fine and after a while the error goes away?

Unfortunately I have no good way to easy get around this problem at the moment, and since it's only happen for this very specific case it feels of a somewhat lower priority considering the current backlog.

**Comment by PatrykSzwer** [comment] 2017-06-02 13:01
I forgot to mention that I tried every typical solution to fix it. Building, cleaning solution and rebuilding, restarting visual studio, nothing helps.

**Comment by chrhol** [comment] 2017-06-02 13:11
Really, that's strange. I will take a more thorough look at it then and see if I can get the same problems.

**Comment by PatrykSzwer** [comment] 2017-06-07 09:52
How is it going @chrhol ? Did You managed to get the same problems?

**Comment by chrhol** [comment] 2017-06-07 10:23
Yes, I have reproduced it doing the same changes in calendar app. Weird, for some reason the property is not skipped in the generated code. I will debug and see if I can find the cause. Maybe it's something that happens when it's declared in an array. 

I will look into it today, was just finishing up some other stuff.

**Comment by chrhol** [comment] 2017-06-07 11:59
I've found the problem. The class in code-behind for `EventsPage.Calendars` is added outside of the class for `EventsPage` (i.e. not added as a nested class), which is supported. However the part of the codegenerator that is responsible for detecting that a property already exists, did not handle this.

I will push a fix shortly for this, so it's included in the next nightly build.

**Comment by chrhol** [comment] 2017-06-07 12:43
The fix for this is pushed to `v2.3` and `develop` branches. Let me know when you have a chance to test it @PatrykSzwer

**Closed** 2017-08-28 12:59 UTC
Labels: bug, json-typed
