### ISSUE TITLE
Admin Panel cuts error message

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#396] opened 2018-03-21 17:15 UTC
I tried to start the `SignIn` app next to the `BlendingEditor` and got some error due to `Simplified` version mismatch. This is expected. There is a problem with the error message in the admin panel, as on the screenshot:

![admin error cut](https://user-images.githubusercontent.com/4943949/37725614-a7a57d04-2d33-11e8-95a7-74297349e61a.png)

Either this message is wrong or it is somehow trimmed. @ubbeK @iqbalskd

**Comment by ubbeK** [comment] 2018-03-22 09:29
@Mihaiii

**Comment by Mihaiii** [comment] 2018-03-22 09:32
It's most probably by design to not mess up the layout.
As long as the "View the log for more details" (with the link to the log page) is intact, I don't consider anything should be changed.
I would like to close this with the "won't fix" label unless @miyconst considers otherwise.

**Comment by mmnosek** [comment] 2018-03-22 09:38
This message looks completely unprofessional. I agree that too long message may be bad, but we cannot leave it like this. Actually, I think the best solution would be to remove custom message totally and in case of any error show: "An error occurred. View the *log* for more details" for all errors here. Do we agree?

**Comment by miyconst** [comment] 2018-03-22 09:56
>Actually, I think the best solution would be to remove custom message totally and in case of any error show: "An error occurred. View the log for more details" for all errors here. Do we agree?

@mmnosek, unfortunately we can't focus on this issue right now, would you like to fix it yourself?

**Comment by mmnosek** [comment] 2018-03-22 10:07
> @mmnosek, unfortunately, we can't focus on this issue right now, would you like to fix it yourself?

Nope, but I would appreciate if it can be done sometime in the future, not left as it is forever. It's low prio for me.

**Comment by Mihaiii** [comment] 2018-04-04 10:52
Closing as done.

**Closed by Mihaiii** 2018-04-04 10:52 UTC
Labels: nice to have, tools, tools-admin-ui
