### ISSUE TITLE
System.ValueTuple and the Weaver

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#166] opened 2017-06-26 14:12 UTC
A project with the System.ValueTuple package imported (see [link](https://www.nuget.org/packages/System.ValueTuple)) will generate the notorious:

`An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. (ScErrUnhandledWeaverException (SCERR6066))`

during runtime, unless `System.ValueTuple` is included in weaver.ignore. The problem and its solution are hard to identify once encountered since the error message gives no hints about the problematic assembly.

**Comment by Mackiovello** [comment] 2017-06-26 16:11
CC @per-samuelsson

**Comment by per-samuelsson** [comment] 2017-06-27 06:03
Thanks @erikvk for reporting. Can't promise to deal with it ASAP, but assigning it to me as part of relevant work we need to improve some time pretty soon.

**Comment by atifwaqar** [comment] 2017-06-29 07:55
When I run the project : 
![image](https://user-images.githubusercontent.com/4388707/27677124-d6843254-5cb0-11e7-8f9e-71259552fdb4.png)
What I see in SC Admin Logs:
![image](https://user-images.githubusercontent.com/4388707/27677155-f6c3a6ee-5cb0-11e7-893f-68427a87859b.png)


Erik from Mopedo fixed the issue by updating the Weaver as following:
```
Newtonsoft.Json.dll
Sigil.dll
DocumentFormat.OpenXml
ClosedXML.dll
ICSharpCode.SharpZipLib
Excel
System.ValueTuple
._Newtonsoft.Json.dll
._Sigil.dll
._DocumentFormat.OpenXml
._ClosedXML.dll
._ICSharpCode.SharpZipLib
._Excel
._System.ValueTuple
```

**Comment by erikvk** [comment] 2017-06-29 09:09
@atifwaqar @per-samuelsson 

Just to be clear: 

The problem Atif is having is separate from the problem with System.ValueTuple. He is having more general issues with the weaver, and its unclear if its the weaver that's to blame. For some reason, his Visual Studio project keeps generating and referencing duplicate assemblies (hence the duplicates in weaver.ignore).

**Comment by per-samuelsson** [comment] 2017-06-30 06:22
> The problem Atif is having is separate from the problem with System.ValueTuple.

Thanks for feedback on that. I did not realize that at first.

>  For some reason, his Visual Studio project keeps generating and referencing duplicate assemblies (hence the duplicates in weaver.ignore).

That is weird. I never heard of anything like that, and my initial guess is it's not caused by the weaver, but well, yeah, could be. Let's see if we can gather the cause.

**Comment by per-samuelsson** [comment] 2017-06-30 10:26
I've checked with @atifwaqar about duplicate assemblies (those starting with a period) and it seem to have been caused by a flawed environment. It's no longer a problem, and hence I'll focus on other stuff until further notice (cleared that with @atifwaqar too).

Regarding the original issue, I'll see if I can reproduce it and comment on it.

**Comment by atifwaqar** [comment] 2017-07-05 14:35
SC Version: 2.3.0.6350

Guys, we experienced `An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. (ScErrUnhandledWeaverException (SCERR6066))` again today. I don't know how and why it appeared. but it was not disappearing no matter what I do. 
After spending an hour, I just deleted my DB, and this issue disappeared. I did not change anything in my Weaver file. I hope this helps.

**Comment by mmnosek** [comment] 2017-07-26 18:13
I drive some POC project (huge codebase with a lot of external assemblies). We hit the same issue as above after installing `MoreLinq` from NuGet. It installs `System.ValueTuple` which generates this issue. Logs:

```
ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 6066.
Arguments=--nocache --maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave "C:\Projects\Test\Test\bin\Debug\Test.exe" --outdir="C:\Starcounter\Personal\Temp\default\default-20170726T173354318\weaver\14D7DB6EE86E7B981837ACFDBEF4B4901518A5DE"
Output:
A4A7D6FA-EB34-442A-B579-DBB1DBB859E3System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.3.1.6870.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ^44BTYvkqH04n.Add(!0 _0)
   at PostSharp.Sdk.Collections.IndexedCollection`1.^FrCoGNuk(Int32 _0, Boolean _1)
   at PostSharp.Sdk.Collections.IndexedCollection`1.TryGetFirstValueByKey[K](Int32 indexOrdinal, K key, !0& value)
   at PostSharp.Sdk.CodeModel.Collections.UniquelyNamedTokenOrderedDeclarationCollection`1.^A5daVqtW.^sIcri3ug(String _0)
   at PostSharp.Sdk.CodeModel.Collections.UniquelyNamedTokenOrderedDeclarationCollection`1.GetByName(String name)
   at PostSharp.Sdk.CodeModel.AssemblyEnvelope.GetTypeDefinition(String typeName, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)
   at PostSharp.Sdk.Extensibility.Tasks.IndexGenericInstancesTask.Execute()
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 321
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 153
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(WeaverHost host, String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 218
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(WeaverHost host, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 164
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 47
   --- End of inner exception stack trace ---A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
System.Exception: ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver.
Version: 2.3.1.6870.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ^44BTYvkqH04n.Add(!0 _0)
   at PostSharp.Sdk.Collections.IndexedCollection`1.^FrCoGNuk(Int32 _0, Boolean _1)
   at PostSharp.Sdk.Collections.IndexedCollection`1.TryGetFirstValueByKey[K](Int32 indexOrdinal, K key, !0& value)
   at PostSharp.Sdk.CodeModel.Collections.UniquelyNamedTokenOrderedDeclarationCollection`1.^A5daVqtW.^sIcri3ug(String _0)
   at PostSharp.Sdk.CodeModel.Collections.UniquelyNamedTokenOrderedDeclarationCollection`1.GetByName(String name)
   at PostSharp.Sdk.CodeModel.AssemblyEnvelope.GetTypeDefinition(String typeName, BindingOptions bindingOptions)
   at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)
   at PostSharp.Sdk.Extensibility.Tasks.IndexGenericInstancesTask.Execute()
   at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)
   at PostSharp.Hosting.PostSharpObject.ExecuteProjects()
   at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)
   at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 321
   at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 153
   at Starcounter.Weaver.Program.ExecuteWeaveCommand(WeaverHost host, String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 218
   at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(WeaverHost host, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 164
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 47
   --- End of inner exception stack trace ---

Version: 2.3.1.6870.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
```

```
 ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.3.1.6870. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.ArgumentException: An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)    at ^44BTYvkqH04n.Add(!0 _0)    at PostSharp.Sdk.Collections.IndexedCollection`1.^FrCoGNuk(Int32 _0, Boolean _1)    at PostSharp.Sdk.Collections.IndexedCollection`1.TryGetFirstValueByKey[K](Int32 indexOrdinal, K key, !0& value)    at PostSharp.Sdk.CodeModel.Collections.UniquelyNamedTokenOrderedDeclarationCollection`1.^A5daVqtW.^sIcri3ug(String _0)    at PostSharp.Sdk.CodeModel.Collections.UniquelyNamedTokenOrderedDeclarationCollection`1.GetByName(String name)    at PostSharp.Sdk.CodeModel.AssemblyEnvelope.GetTypeDefinition(String typeName, BindingOptions bindingOptions)    at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)    at PostSharp.Sdk.Extensibility.Tasks.IndexGenericInstancesTask.Execute()    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 321    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 153    at Starcounter.Weaver.Program.ExecuteWeaveCommand(WeaverHost host, String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 218    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(WeaverHost host, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 164    at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 47    --- End of inner exception stack trace ---
```

```
System.Exception:  ScErrUnhandledWeaverException (SCERR6066): An unhandled, unidentified (non-Starcounter) exception occurred in the weaver. Version: 2.3.1.6870. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR6066. ---> System.ArgumentException: An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)    at ^44BTYvkqH04n.Add(!0 _0)    at PostSharp.Sdk.Collections.IndexedCollection`1.^FrCoGNuk(Int32 _0, Boolean _1)    at PostSharp.Sdk.Collections.IndexedCollection`1.TryGetFirstValueByKey[K](Int32 indexOrdinal, K key, !0& value)    at PostSharp.Sdk.CodeModel.Collections.UniquelyNamedTokenOrderedDeclarationCollection`1.^A5daVqtW.^sIcri3ug(String _0)    at PostSharp.Sdk.CodeModel.Collections.UniquelyNamedTokenOrderedDeclarationCollection`1.GetByName(String name)    at PostSharp.Sdk.CodeModel.AssemblyEnvelope.GetTypeDefinition(String typeName, BindingOptions bindingOptions)    at PostSharp.Sdk.CodeModel.TypeRefDeclaration.GetTypeDefinition(BindingOptions bindingOptions)    at PostSharp.Sdk.Extensibility.Tasks.IndexGenericInstancesTask.Execute()    at PostSharp.Sdk.Extensibility.Project.ExecutePhase(String phase)    at PostSharp.Hosting.PostSharpObject.ExecuteProjects()    at PostSharp.Hosting.PostSharpObject.ProcessAssemblies(ModuleLoadStrategy[] modules)    at Starcounter.Weaver.CodeWeaver.Execute() in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 321    at Starcounter.Weaver.CodeWeaver.ExecuteCurrent(CodeWeaver weaver) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Starcounter.Weaver\CodeWeaver.cs:line 153    at Starcounter.Weaver.Program.ExecuteWeaveCommand(WeaverHost host, String inputDirectory, String outputDirectory, String cacheDirectory, String fileName, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 218    at Starcounter.Weaver.Program.ApplyOptionsAndExecuteGivenCommand(WeaverHost host, ApplicationArguments arguments) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 164    at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\scweaver\Program.cs:line 47    --- End of inner exception stack trace ---
   at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 198
   at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory, Boolean disableEditionLibraries) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 121
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__2(CommandTask task) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 108
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-6735\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR6066
```

Removing `System.ValueTuple` works fine, adding it to `weaver.ignore` as well.

**Comment by per-samuelsson** [comment] 2017-08-09 11:30
I'm currently trying to find out just what it is that make PostSharp fail to index generic instances, considering there are more instances with the same name.

As I see it, there are 2 ways forward here:

1. Try to analyse in depth what actually causes this problem in PostSharp, and see if we can find a way to fix it there.
2. Add some kind of support for global exclusions of (third-party) assemblies we know a) cause trouble and b) surely don't need to be analyzed by the weaver.

As for 2, we actually already have a list of such assemblies, but it's hard-coded and also pretty old. It might be an alternative to open that up, and move the content to some file we send as part of every version, kind of like one of those predefined `.gitignore` files. Then every time we meet something like this, we can extend that list (or even have customers doing it in their installation, if the problem is urgent).

**Comment by per-samuelsson** [comment] 2017-08-11 09:21
> Try to analyse in depth what actually causes this problem in PostSharp, and see if we can find a way to fix it there.

I've spent some time now testing various ways and debugging a custom PostSharp build, and the conclusion I'm reaching at that above approach just doesn't seem realistic.

In this particular instance, it's clearly a PostSharp bug, that can't correctly handle some kind of variant with complex generic overloads, and the bug is really deep down in PostSharp, in some caching of type definitions that renders a duplicate index-copy on some certain occasion with a generic type.

Now, reaching at that conclusion led me to start thinking more and doing some experimenting with (2), to see if we could improve the experience. 

The idea I had was that next-best thing would be that we'd try to provide an experience that when some exception stemmed from PostSharp not being able to correctly process some certain artifact, the user was given a correct and meaningful message in the lines of:

> Starcounter can not properly analyse the `System.ValueTuple` assembly, referenced by your application. To correctly run your application, we can skip analyzing that assembly if you know there are not any database classes in it. Do you wan't Starcounter to skip analysis of `System.ValueTuple`? Type [Y]es to skip analysis in this application, [A]lways to always skip analysis of `System.ValueTuple` or [C]ancel to take no action.

That would not be for free. It would take some time of development and there are a few uncertainties involved (mainly regarding how to properly catch those exceptions in the weaver, and correctly know and provide the name of the failing assembly). However, after considering that even more, there is still a problem with it because it does **only address errors happening in third-party assemblies** while we already know there are cases where PostSharp fail in assemblies that *do include* Starcounter database classes (like for example https://github.com/Starcounter/level1/issues/3739). Hence, even if we landed that, we'd still have no solution for errors happening in code defined by applications themselves.

Conclusion at this point: we still have no final idea about the proper solution, and must spend some more time assessing alternatives. Right now I can't see how we can really do move in any other direction that trying to get an alternative to the 2.x-weaver ready, in whatever form. I will raise some discussion about this ASAP to try to go through ways forward.

**Comment by miyconst** [comment] 2017-08-31 07:46
Archiving the issue. The issue in the old weaver won't be fixed, the new weaver is currently in development.

@per-samuelsson please create another issue and link this one, if you want to keep the task open, since this thread is too long.

**Closed by miyconst** 2017-08-31 07:46 UTC
Labels: bug, weaver, _Usability
