### ISSUE TITLE
WebSocket closing message not always includes the stack trace

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#174] opened 2017-07-06 09:56 UTC
## Steps to reproduce

See @alshakero's comment https://github.com/Starcounter/Home/issues/174#issuecomment-313372872 for easy reproduction.

Alternative:

<details>
<ol><li>Start <a href="https://github.com/StarcounterApps/KitchenSink/commit/a35a6f01ad81944efb0c94a5399928c2ce30ee34">https://github.com/StarcounterApps/KitchenSink/commit/a35a6f01ad81944efb0c94a5399928c2ce30ee34</a>
<li>Start <a href="https://github.com/StarcounterApps/SysUpgrade/commit/453b87dda0a13345960e9a5cbc143b02ec956124">https://github.com/StarcounterApps/SysUpgrade/commit/453b87dda0a13345960e9a5cbc143b02ec956124</a>
<li>Go to <a href="http://localhost:8080/KitchenSink/Button">http://localhost:8080/KitchenSink/Button</a>  
<li>Click on the button that says "Button (function)"  
<li>An exception happens
</ol>
</details>

## Expected

Whenever the WebSocket message causes **an app or Starcounter** to throw an exception, this exception should be sent over WebSocket (unless verbose errors are disabled for production env). 

WebSocket closing message is a useful form of transporting the stack trace to the developer. For example, if my `.json.cs` throws an exception in response to the client side WebSocket patch, this will break the connection and include the stack trace in the closing message.

## Actual

However, if the error happens between the gateway and the app (as presented on the below sample, in case of an illegal "add" operation), the closing message is empty. The stack trace is only presented in the Adminsitrator.

Example. This was in the browser console:

```txt
Websocket connection to xxxx failed: Invalid frame header

Connection error: WebSocket connection could not be made.
```

![image](https://user-images.githubusercontent.com/566463/27905657-e64a3dec-6240-11e7-8932-0711ca828805.png)

This was in the Administrator log:

```
Starcounter.XSON.JsonPatchException: Unsupported patch operation in patch: 'Add'. Patch: '{"op":"add","path":"/CurrentPage/CurrentPage/KitchenSink/AddCarrots","value":2}'. Viewmodel versions: {client (_ver#c$): 3, clients serverversion: 1, server (_ver#s): 2}.
   at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 17
   at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 541
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 469
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 367
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\TeamCity10\buildAgent\work\sc-6025\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 62
Patch={"op":"add","path":"/CurrentPage/CurrentPage/KitchenSink/AddCarrots","value":2}
Severity=1
HResult=-2146233088
```

Source: https://github.com/Palindrom/palindrom-polymer-client/issues/42#issuecomment-313136788

## Starcounter version 2.3.1.6682

@alemoi is this a change that you can make?

cc @alshakero

**Comment by alshakero** [comment] 2017-07-06 11:43
Easier reproduction would be: 

In **any** SC app:
1- Open Chrome console.
2- Execute `document.querySelector('puppet-client').puppet.ignoreAdd = false; document.querySelector('puppet-client').puppet.obj.a = 1`
3- Click anywhere in the app to trigger jsonpatch.

**Comment by alshakero** [comment] 2017-07-24 14:39
Any update on this?

**Comment by miyconst** [comment] 2017-08-31 07:55
@alemoi please read the issue and close it if it's something we can't or won't implement.

**Comment by warpech** [comment] 2017-09-26 21:39
I think this should have increased priority. This makes issues like https://github.com/Starcounter/inside.starcounter.com/issues/23 take DAYS to debug.

**Comment by warpech** [comment] 2017-10-24 08:35
This manifested today again: https://github.com/Palindrom/palindrom-redirect/issues/1#issuecomment-338915901

**Comment by alemoi** [comment] 2017-10-28 22:33
I have researched this issue and found the reason: `All control frames MUST have a payload length of 125 bytes or less and MUST NOT be fragmented.` Closing frame is a control frame. It wasn't displayed correctly previously because it was exceeding 123 bytes.

What I did is that now I truncate the error message to around 123 bytes:

![image](https://user-images.githubusercontent.com/208134/32139009-585d82de-bc3e-11e7-8c77-b0626ef9cc3e.png)

In addition: if I try to send an error message first, you get this (because JSON patch message is expected):

![image](https://user-images.githubusercontent.com/208134/32139033-1c311ff4-bc3f-11e7-9d0e-14184a6fe9ae.png)

Is there an error handling protocol part in JSON patch? Because if there would be - the problem would be solved.

**Comment by alemoi** [comment] 2017-10-28 23:10
Regarding the JSON patch protocol error handling the issue should separate, if needed to be created. Closing this one.

**Closed by alemoi** 2017-10-28 23:10 UTC
Labels: desired, enhancement, errors, errors-reports

**Comment by warpech** [comment] 2017-10-30 22:24
Great job!

> In addition: if I try to send an error message first, you get this (because JSON patch message is expected):
>
> [picture]
>
> Is there an error handling protocol part in JSON patch? Because if there would be - the problem would be solved.

How are you sending the erors? It looks as you are sending them as a regular message. Palindrom expects messages to be JSONs, so it crashes at trying to parse `Unsupported patch operation...` as JSON.

Is there some special way to mark messages as "error messages" in Websocket that I am not aware of?

**Comment by alemoi** [comment] 2017-11-07 12:12
> Is there some special way to mark messages as "error messages" in Websocket that I am not aware of?

Only via Close messages with reason as above. Its up to the upper layer protocol, in this case, Json patch, to handle and send such errors.

**Comment by warpech** [comment] 2017-11-07 12:38
> Only via Close messages with reason as above. Its up to the upper layer protocol, in this case, Json patch, to handle and send such errors.

JSON Patch only sends patches, so it cannot send an error either. We would need to redesign Palindrom data protocol to have some kind of envelope for the messages that can be either patches or something else: requests, errors, etc.

But this is off-topic for this issue.

**Comment by alshakero** [comment] 2017-11-07 12:51
I just tried it. `ws.onmessage` isn't being called at all and only `socket.onclose` is being called with a proper error message. So I think this is fixed. I don't know why this 
![image](https://user-images.githubusercontent.com/17054134/32494585-7efd3f20-c3c2-11e7-9af0-86c0235c3cf1.png)

...happened in your case, but here all I get is this:

<img width="959" alt="2" src="https://user-images.githubusercontent.com/17054134/32494638-acb9d72a-c3c2-11e7-9c86-7db9e4a4500c.png">

Which I think is perfect.

**Comment by alshakero** [comment] 2017-11-07 12:53
Sorry for the last now-deleted comment, I misread. Maybe we can send a normal string error from the server. And in Palindrom we can simply `try` before `JSON.parse` and throw the raw message in `catch` and that's it. Without any protocal changes.

**Comment by warpech** [comment] 2017-12-11 17:02
But what is it needed for? To send the full error message instead of the truncated error message?

Sounds like a good idea.

**Comment by alshakero** [comment] 2017-12-11 17:10
> To send the full error message instead of the truncated error message

Yes exactly. Because `CloseEvent.Reason` is a control frame and can be [125 bytes max](https://tools.ietf.org/html/rfc6455#section-5.5). Whereas a message can be anything.

**Comment by warpech** [comment] 2017-12-11 17:29
Can you pls make an issue about it in Palindrom?

**Comment by alshakero** [comment] 2017-12-11 17:54
>Can you pls make an issue about it in Palindrom?
 
Sure https://github.com/Palindrom/Palindrom/issues/188.

I would say it isn't a breaking change for Palindrom to have the ability to handle non-JSON WebSocket messages. So I'll implement it in Palindrom first, and when I'm done I'll comment here so @alemoi (?) can go for it when Palindrom is ready and is waiting for the error messages. Do you agree?

**Comment by warpech** [comment] 2017-12-12 16:13
In my opinion this is only "Nice to have", so don't treat it with high priority.

I will open a new issue for @alemoi about this.
