### ISSUE TITLE
Incorrect messages during switching between 2.3.1 and 2.4.0 versions of Starcounter

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#322] opened 2017-11-23 14:28 UTC
When I have Starcounter v. 2.3.1.7877 installed, and I'm running installer for v 2.4.0.3938, I'm getting messages saying, that I'm actually downgrading my starcounter, not updating. 
Same goes the other way. When I have 2.4.0 installed, and trying to downgrade to version 2.3.1 I'm getting information about update not downgrade:
![image](https://user-images.githubusercontent.com/25042256/33177404-c4538d70-d062-11e7-9d1f-84710fdc4650.png)
Either information before installation and right after ("Update/Downgrade successful") seems to be swapped.

**Comment by k-rus** [comment] 2017-11-23 14:43
Should we even allow downgrading? It is definitely not possible to start database by earlier version of Starcounter created in later version. In some cases it can be even undefined behaviour and in very rare occasion corrupted database (if downgrade between some old 2.3 versions or to 2.2)

**Comment by PatrykSzwer** [comment] 2017-11-24 09:02
Well, that if we should or shouldn't allow it It's separated story. Right now, It's clearly a mistake, that moving from 2.3.1 to 2.4 is understood as downgrade. 

About first part, I think We definitely should at least give user a warning, that he has to recreate database, or just forbid downgrading/updating at all. but I'm not sure that's the most intuitive solution.

**Comment by k-rus** [comment] 2017-11-24 10:15
Because of my question, I see two ways to fix the OP:

1. Call `downgrade` on downgrade, not `upgrade`
2. Don't allow downgrade

Both cases require to put a branch in the installer, but different things inside the downgrade branch. Thus I feel my question is relevant in this issue.

**Comment by PatrykSzwer** [comment] 2017-11-24 12:21
Well, I think We should involve bigger group of people in discussion about not allowing downgrade. Right now, I Think step 1 should require small amount of work and should be pretty simple to do.

**Comment by mmnosek** [comment] 2017-11-24 12:39
Guys, I think that this issue is super simple. What @PatrykSzwer does:
* Upgradeing from `2.3.1` to `2.4` - but message says: "Would you like to upgrade from 2.4 to 2.3.1"
* Downgrading from `2.4` to `2.3.1` - but message says: "Would you like to downgrade from 2.3.1 to 2.4

So message says: from `A` to `B`. All we need to do is fix a message to show `B` to `A`. It's no-brainer, isn't it?

**Comment by mmnosek** [comment] 2017-11-24 12:43
It's a no-brainer. Let's change a word "downgrade" to "upgrade" and another way around and close this issue.

**Comment by miyconst** [comment] 2017-11-29 09:33
cc @ubbeK

**Comment by k-rus** [comment] 2017-11-30 07:49
> BTW just forbidding downgrade/update is bad solution. We can't just say to user, that He can't install SC 2.4 because he has 2.3.1. Smarter solution would be to give information, that with this update/downgrade entire database has to be erased and recreated, and installer should do that.

User can downgrade manually by uninstalling current version and installing downgraded version.

Installer and Starcounter product in general should never erse database, since it is potential lost of customer data.

I am against of just fixing the word. We either should prevent from downgrading or make sure that downgrade is safe for the customer. imho, this issue is much more serious than just incorrect word. @PatrykSzwer you found an important bug.

**Comment by mmnosek** [comment] 2017-11-30 08:33
> Installer and Starcounter product in general should never erse database, since it is potential lost of customer data.

@k-rus I agree. Data needs to be safe at all cost. Making installer able to prevent from downgrade (and upgrade!) if there is no auto-migration is in general very good idea. 

However, I think it's a separate issue. That should be discussed and handled separately (it may take much more time). A quick fix to make communicate correctly will not change Starcounter behavior but will make a user experience a little bit more clear.

**Comment by k-rus** [comment] 2017-11-30 08:45
> A quick fix to make communicate correctly will not change Starcounter behavior but will make a user experience a little bit more clear.

Then I suggest to keep as it is, which gives experience of a bug, since it is a bug, which is not resolved and even not thought. I don't see any need to create new issue, since this issue reports the bug. The original suggestion for the bug resolution hides the problem from the user.

**Comment by mmnosek** [comment] 2017-11-30 10:13
This issue is about message problem. "Would you like to upgrade from 2.4 to 2.3" looks just silly and securing from incorrect upgrade/downgrade process is a separate story.

**Comment by k-rus** [comment] 2017-11-30 11:12
Then at least the message should say that starting a database after downgrade might corrupt the database. Without this warning our customers are more likely to be in trouble and we will need to fix their databases.

As I see this issue will be discussed tomorrow during release planning meeting.

**Comment by PatrykSzwer** [comment] 2017-11-30 15:07
Not enough informative message is one problem. Replaced 2 words, that should be in opposite places - that's problem that should be fixed first. Right now, those messages, about e.g "downgrading from 2.3.1 to 2.4.0" are just wrong.

**Comment by k-rus** [comment] 2017-11-30 15:26
> Replaced 2 words, that should be in opposite places - that's problem that should be fixed first. Right now, those messages, about e.g "downgrading from 2.3.1 to 2.4.0" are just wrong.

It is not just replacement of 2 words. You need to add if-statement to compare versions. Then the logic can be written to be more appropriate for the same development cost.

Current wrong message is good. It gives a sign to our customer that we've never thought about downgrading. So some of them might stop and think here. Currently the behaviour is undefined when downgrading.

**Comment by Mackiovello** [comment] 2017-12-01 10:34
The issue is on this line: https://github.com/Starcounter/level1/blob/3818bdc50b0c5a672ef22a148167201695c2f97d/src/Starcounter.Installer/Starcounter.InstallerWPF/InitializationWindow.xaml.cs#L123

We're comparing the date of the version, not the version number. 

The same comparison is made here:
https://github.com/Starcounter/level1/blob/3818bdc50b0c5a672ef22a148167201695c2f97d/src/Starcounter.Installer/Starcounter.InstallerWPF/InitializationWindow.xaml.cs#L140

Since we're already doing this, it shouldn't be controversion to fix so that downgrading from 2.4 to 2.3.1 gives the same message as downgrading from 2.3.1.1234 to 2.3.1.1233.

**Comment by miyconst** [comment] 2017-12-01 14:23
On today's release planning with @k-rus, @bigwad, @chrhol, @per-samuelsson, @linkdata meeting it was discussed with the following outcome:

- Downgrading from `2.4` to `2.3` will crash during database startup.
- Downgrading between `2.3.1` versions will seamlessly work until a very old version of `2.3.1` with does not have vacuum tables selected.
- Downgrading between `2.4` will either fail when meta schema is not compatible or work seamlessly.
- Those, we only need to update the installer dialog to show a proper message and warn about possible database binary incompatibility.
- Downgrading to `2.3.0` and beyond has undefined behavior, but we are not going to do anything about it.
- [In the future we should implement full database binary backup before doing any migration operations](https://github.com/Starcounter/Home/issues/330).
- A system regression test has to be developed, which would actually try to start different versions of Starcounter on different database binaries. @ubbeK maybe Iqbal can do that?

**Comment by ubbeK** [comment] 2017-12-01 14:42
> A system regression test has to be developed, which would actually try to start different versions of Starcounter on different database binaries. @ubbeK maybe Iqbal can do that?

Please create an issue about it so we can put it into the backlog.

**Comment by ubbeK** [comment] 2017-12-01 14:45
As I see it, the only think we will implement in this issue is a proper message when downgrading. Something har that it may destroy your database to an unrecoverable state.

**Comment by iqbalskd** [comment] 2017-12-14 12:47
Fixed and merged.

**Closed by iqbalskd** 2017-12-14 12:47 UTC
Labels: bug, packaging, windows
