### ISSUE TITLE
Can't install Starcounter when 2017 Redistributable is in place

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#183] opened 2017-07-20 09:32 UTC
What goes wrong
---
Installer detects I have no 2015 Redistributable on my system and tries to install one. It's installation fails, since I have 2017 Redistributable, which is binary-compatible with 2015 ([source](https://msdn.microsoft.com/en-us/library/ms235299.aspx), 6th paragraph)

Error message (might help someone find this issue)
---
> Starcounter setup failed. Returned error code: 1638. Error message: Installation of Microsoft Visual Studio 2015 Redistributable (x64) failed

Proper solution
---
Don't try to install Redistributable if a newer version is already there

Workaround (for people with the same problem, in case it's not solved yet)
---
1. Uninstall Redistributable 2017 (x64)
1. Install Starcounter
1. Install Redistributable 2017 (x64) again. You can omit this step, but something on your system probably needs it, since it was installed in the first place

**Comment by mmnosek** [comment] 2017-08-10 14:33
@alemoi any ideas? One more person experienced the same (VS 2015 Update 1)

**Comment by alemoi** [comment] 2017-08-10 14:35
Can you please paste the contents of the: `HKEY_LOCAL_MACHINE\SOFTWARE[\Wow6432Node]\Microsoft\VisualStudio\14.0\VC\Runtimes\x64`

In this way:
![image](https://user-images.githubusercontent.com/208134/29175666-f1eb040a-7de9-11e7-9be2-8f94cb53c49b.png)

**Comment by alemoi** [comment] 2017-08-10 21:18
Way easier way (big time thanks to @bigwad), just run these separately in cmd:
```
REG QUERY HKLM\Software\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x86 /v Installed
REG QUERY HKLM\Software\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64 /v Installed
```
And post both responses here.

**Comment by bigwad** [comment] 2017-08-10 22:01
I suppose it's irrelevant since @alemoi migrated us to vs2017 and put vc2017  redistributables into the installer.

**Comment by alemoi** [comment] 2017-08-11 14:06
Yes, its interesting which SC version was used for installation.

**Comment by bigwad** [comment] 2017-08-11 14:17
Obviously, not produced with vs2017 which you made just yesterday.

**Comment by joozek78** [comment] 2017-08-14 08:58
> I suppose it's irrelevant since @alemoi migrated us to vs2017 and put vc2017 redistributables into the installer.
>  👍 1 👎 1

I don't think so - it will be the same after MS releases a new redistributable and someone installs it

**Comment by mmnosek** [comment] 2017-08-16 10:29
@alemoi response from command 1:
```
HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\
x86
    Installed    REG_DWORD    0x1
```

Command 2 gives: `ERROR: The system was unable to find the specified registry key or value.`

**Comment by miyconst** [comment] 2017-08-21 09:32
@ubbeK please take care of this issue in low priority.

**Comment by mmnosek** [comment] 2017-08-21 09:41
> @ubbeK please take care of this issue in low priority.

I would say it should be a high priority for us. It's a showstopper and if somebody tries Starcounter and faces this issue at the very beginning, we can lose such opportunity.

**Comment by miyconst** [comment] 2017-08-21 09:45
@mmnosek, thank you for the input. @ubbeK please prioritize the issue when possible.

**Comment by ubbeK** [comment] 2017-08-21 11:19
I just tried this with out latest RC build `2.3.1.7018` (install/uninstall) with different combinations of `2015 Redist` and `2017 Redist`. If any of them are installed, then Starcounter installer wont install anything, it will only install `2017 Redist` if none of them are installed. Although the pop-up windows says it will install `2015 Redist`.

So I cannot reproduce this. @mmnosek

**Comment by miyconst** [comment] 2017-08-21 11:24
I think, the problem happen when there is `2019 Redist` released and installed, then installer won't recognize it and will try to install `2017 Redist`, which will fail.

**Comment by threezool** [comment] 2017-08-23 07:38
I encountered this on Monday when i needed to uppgradera the SC version and it would not install. Weird thing was that after 5-6 tries it actually installed successfully.

**Comment by mmnosek** [comment] 2017-08-23 08:41
@ubbeK I see, but unfortunately it was not on my machine. It was some person that tried Starcounter and I don't want to bother and ask again and again. All I have is the input above. Have you tried with `2019 redist` as @miyconst suggested? @threezool what version have you tried to install? In my case it was `2.3.0.6350` (stable). @ubbeK can you try with this one?

**Comment by threezool** [comment] 2017-08-23 09:20
@mmnosek  Must have been 2.3.1.7018 (RC) since it was the latest available that day. Tried no other and it finally installed after a couple of tries.

**Comment by ubbeK** [comment] 2017-08-23 23:27
@mmnosek I will try it out tomorrow.

**Comment by ubbeK** [comment] 2017-08-24 11:52
Have you tried with 2019 redist as @miyconst suggested?

Isn't `2017 Redistributable` the latest redistributable? @miyconst mentioned that this will be a problem `when` a new redistributable will be released.

**Comment by mmnosek** [comment] 2017-08-24 13:25
If so, then it's not this issue, the reason must be different.

**Comment by ubbeK** [comment] 2017-08-24 13:30
I have now been trying to reproduce this without any luck but I did manage to check out the source code and this is how it works.

![redistributable](https://user-images.githubusercontent.com/8124023/29668244-be39d054-88df-11e7-83c6-3fd44bbb91cd.PNG)

We check in the registry if 

- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x86 => `Installed == 1`
- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64 => `Installed == 1`

If both of the above are true, then we go about our days as usual. But here is the catch, VC 2015 and 2017 Redistributable share the same `Major REG_DWORD` value which is `0x0e (14)`. If we want to install VC 2017 Redistributable when VC 2015 Redistributable is installed, then we have to check the `Minor REG_DWORD` value which is >= 0x0a (10) for VC 2017 Redistributable.

See https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering for the different internal version numbering.

**Comment by ubbeK** [comment] 2017-09-04 14:44
This issue has been implemented. The Installer now also checks if `Minor` DWord is greatar than 10, i.e. if vc redist 2015 is installed, then vc redist 2017 will be installed.

Closing

**Closed by ubbeK** 2017-09-04 14:44 UTC
Labels: bug, packaging, scheduled, windows
