### ISSUE TITLE
XSON fails to compare request mime-type with custom Thread Culture Info (Turkish)

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#455] opened 2018-11-28 07:11 UTC
Starcounter version: `<2.4.0.7014>`.

### Issue type

- [x] Bug
- [ ] Feature request
- [ ] Suggestion
- [ ] Question
- [ ] Cannot reproduce
- [ ] Urgent

### Issue description
Works `Start Without Debugging` but not works with debugging.
Previous versions work well.
### Reproduction code snippet

```cs

```

### Exception stack trace

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The debug sequence failed. Consult the Visual Studio error list for more information. HTTP/1.1 500 InternalServerError
Cache-Control: no-store
Date: Wed, 28 Nov 2018 06:45:34 GMT
Server: Starcounter/2.4.0.7014
Server: (Windows)
Content-Length: 1351

System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Administrator.API.Handlers.ExecutableHandler.JSON.CreateRepresentation(DatabaseInfo state, AppInfo exeState, Dictionary`2 headers) in C:\tc_work\sc-19753\Level1\src\Starcounter.Administrator\API\Handlers\ExecutableHandler.cs:line 48
   at Starcounter.Administrator.API.Handlers.ExecutableCollectionHandler.OnPOST(String name, Request request) in C:\tc_work\sc-19753\Level1\src\Starcounter.Administrator\API\Handlers\ExecutableCollectionHandler.POST.cs:line 138
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\tc_work\sc-19753\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 203
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\tc_work\sc-19753\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 88
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\tc_work\sc-19753\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 354
HResult=-2147467261
```

**Comment by SenerDemiral** [comment] 2018-11-29 05:37
Same problem exists in `v2.4.0.7020`.
`v2.4.07006` is working as expected.

**Comment by miyconst** [comment] 2018-11-29 14:14
@alemoi do you have an idea of what is this?

**Comment by SenerDemiral** [comment] 2018-11-30 05:15
Sorry, but same problem exists in `v2.4.0.7024`.
Downgraded to  `v2.4.0.7006`.

**Comment by SenerDemiral** [comment] 2018-12-01 07:48
Same problem exists in `v2.4.0.7030`.
I don't know what to do!

**Comment by alemoi** [comment] 2018-12-01 09:10
Seems something in Administrator, but not something I know of. I will check if there is anything there.

**Comment by SenerDemiral** [comment] 2018-12-01 12:00
I tried on another machine `Windows Server 2018 R2`, same problem exists.

**Comment by alemoi** [comment] 2018-12-01 21:10
Seems its related to changes for `exeState.Key` made by @bigwad.
@bigwad can you please check?

**Comment by SenerDemiral** [comment] 2018-12-03 06:29
`v2.4.0.7032` is working now.

But there is another problem on the first run `Start with Debugger`. 
`Ctrl+F5` on the browser solves the problem.
`Start Without Debugger` runs as expected. (No need to press `Ctrl+F5` on the browser)

Firefox 
```
Error: "Client error
	N/A
	statusCode: 513
	reason: Unsupported mime type application/json.
	url: http://127.0.0.1:8084/__bodved2/70E1B738DED4920400000010
	HTTP method: GET"
	t http://127.0.0.1:8084/sys/Palindrom/dist/palindrom-dom.min.js:23:8658
	PalindromConnectionError http://127.0.0.1:8084/sys/Palindrom/dist/palindrom-dom.min.js:23:8974
	xhr http://127.0.0.1:8084/sys/Palindrom/dist/palindrom-dom.min.js:14:5948
 starcounter.html.js:22:13
```
Chrome
```
 Unsupported mime type text/html.
```

**Comment by miyconst** [comment] 2018-12-03 10:30
@SenerDemiral thank you for validating the fix and reporting the issue.

Regarding the ` Unsupported mime type text/html` issue, it seems like something is cached in browser, could you please:

- Open Chrome Developer's Console and disable caching on the Network tab.
- Keep the Console open and load the page.
- See if the error persists.
- Report the network requests available on the Network tab if the issue is still there.

**Comment by SenerDemiral** [comment] 2018-12-03 11:55
Reproduction
VS2017: Start With Debugger

-Firefox: 
 Load the page. Page is Empty. (Network -> Disable Chache is checked)
 Console: XML Parsing Error: syntax error
          Location: http://127.0.0.1:8084/__bodved2/D2512EF3D685261100000010 Line Number 1, Column 1:
          View Source in Debugger: Unsupported mime type text/html.
					Network request has only uniform.css
 Then Ctrl+F5: Page loads as expected.

-Chrome: 
 Load the page. Page is Empty. (Network -> Disable Chache is checked)
 Console: Failed to load resource: the server responded with a status of 513 (N/A)
          Unsupported mime type text/html.
					There is no item in Network request
 Then Ctrl+F5: Page loads as expected.

Works if page loaded again on the second tab of the browser.
Even works, if page loaded on other browser second time.
First page load never success.

**Comment by alemoi** [comment] 2018-12-03 12:43
@SenerDemiral which page in browser are you loading after `Start With Debugger`?

**Comment by SenerDemiral** [comment] 2018-12-03 14:42
Web Administrator -> Select Database -> Open App

**Comment by miyconst** [comment] 2018-12-03 16:34
@SenerDemiral could you please try with the [Images](https://github.com/Starcounter/Images) app or provide the sources to reproduce the error?

**Comment by SenerDemiral** [comment] 2018-12-03 19:39
I finally found the mistake.
```
static void Main()
{
	/* Below lines cause the error!
	CultureInfo culture;
	culture = CultureInfo.CreateSpecificCulture("tr-TR");
	Thread.CurrentThread.CurrentCulture = culture;
	Thread.CurrentThread.CurrentUICulture = culture;
	*/

	IHandler[] handlers = new IHandler[]
	{
		new MainHandlers(),
		new PartialHandlers()
	};

	foreach (IHandler handler in handlers)
	{
		handler.Register();
	}
}
```
Where can I put these lines?

**Comment by SenerDemiral** [comment] 2018-12-03 19:52
Anyway, I can live without it.
I exhausted all of your valuable time.
Sorry and thank you again.

**Comment by miyconst** [comment] 2018-12-03 21:49
@SenerDemiral thank you very much for using Starcounter and finding all of those bugs, it's very appreciated.

I have reproduced the issue, and it's not acceptable to have it. Thus, I am reopening the issue.

Steps to reproduce:

- Create a Starcounter application.
- Register an app handler using `Handle.GET` in the `Main` function.
- Add the culture settings at the beginning of the `Main` function.
- Stop the `default` database if it's running.
- Start the application in the `default` database with debugging, by clicking `F5` in visual studio.
- **Open the registered handler in browser, Palindrom connection fails with `513 N/A Unsupported mime type application/json`, Starcounter administrator logs a `NullReferenceException`.**
- Reload the page with `F5` or `Ctrl + F5` in browser - the page works as expected.

```cs
CultureInfo culture = CultureInfo.CreateSpecificCulture("tr-TR");
Thread.CurrentThread.CurrentCulture = culture;
Thread.CurrentThread.CurrentUICulture = culture;
```

```
"System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.Administrator.API.Handlers.ExecutableHandler.JSON.CreateRepresentation(DatabaseInfo state, AppInfo exeState, Dictionary`2 headers) in C:\	c_work\sc-19783\Level1\src\Starcounter.Administrator\API\Handlers\ExecutableHandler.cs:line 48
   at Starcounter.Administrator.API.Handlers.ExecutableCollectionHandler.OnPOST(String name, Request request) in C:\	c_work\sc-19783\Level1\src\Starcounter.Administrator\API\Handlers\ExecutableCollectionHandler.POST.cs:line 138
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\	c_work\sc-19783\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 203
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\	c_work\sc-19783\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 88
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\	c_work\sc-19783\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 354
HResult=-2147467261
"
```

**Comment by miyconst** [comment] 2018-12-03 21:54
@SenerDemiral, as a temporary work you can use the following properties to set culture info per session:

```cs
CultureInfo culture = CultureInfo.CreateSpecificCulture("tr-TR");
Starcounter.Session.Current.CurrentCulture = culture;
Starcounter.Session.Current.CurrentUICulture = culture;
```

Beware that:

- It has to be done in the place where the session is created.
- It is only applicable for the session thread, means it will not affect the `Main` function itself, and it will not affect any running background jobs.
- The `Starcounter.Session.Current` property may be null if the session is not created yet.
- Every `Starcounter.Session` has it's own `CurrentCulture` and `CurrentUICulture` value, setting it for one session will not affect other sessions.

**Comment by SenerDemiral** [comment] 2018-12-04 05:55
@miyconst same problem exists.
```
protected static MasterPage GetMasterPageFromSession()
{
	var session = Session.Ensure();

	MasterPage master = null; // session.Store[nameof(MasterPage)] as MasterPage ?? new MasterPage();

	if (session.Store[nameof(MasterPage)] == null)
	{
		master = new MasterPage();

		// https://github.com/Starcounter/Home/issues/455#issuecomment-443884798

		/* Still, it is not working
		CultureInfo culture = CultureInfo.CreateSpecificCulture("tr-TR");
		Starcounter.Session.Current.CurrentCulture = culture;
		Starcounter.Session.Current.CurrentUICulture = culture;
		*/

		session.Store[nameof(MasterPage)] = master;
	}
	else
	{
		master = session.Store[nameof(MasterPage)] as MasterPage;
	}

	return master;
}
```

**Comment by SenerDemiral** [comment] 2018-12-04 06:43
`CultureInfo culture = CultureInfo.CreateSpecificCulture("tr-TR");`
What a pity that, there is a problem on `tr-TR`.
`se-SE`, `es-ES`, `fr-FR` are all working.

**Comment by SenerDemiral** [comment] 2018-12-04 06:49
I think below characters causes the problem.
`i -> İ`
`ı  -> I`

**Comment by SenerDemiral** [comment] 2018-12-04 06:57
The Turkish Example
For most Latin alphabets, the letter i (Unicode 0069) is the lowercase version of I (Unicode 0049). The Turkish alphabet, however, has two versions of the letter I, one with a dot and one without. In Turkish, the character I (Unicode 0049) is considered the upper case version of a different character ý (Unicode 0131), and i (Unicode 0069) is considered the lower case version of yet another character Ý (Unicode 0130).

Confused? Below is a diagram that might make this clearer. The result is that in this culture, case-insensitive string comparisons that should normally succeed will fail.

https://msdn.microsoft.com/en-us/library/ms994325.aspx

Here is some code that demonstrates what this means:

Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
Console.WriteLine("Culture = {0}", Thread.CurrentThread.CurrentCulture.DisplayName);
Console.WriteLine("(file == FILE) = {0}", (string.Compare("file", "FILE", true) == 0));

Thread.CurrentThread.CurrentCulture = new CultureInfo("tr-TR");
Console.WriteLine("Culture = {0}",Thread.CurrentThread.CurrentCulture.DisplayName);
Console.WriteLine("(file == FILE) = {0}", (string.Compare("file", "FILE", true) == 0));
Because of the difference of the comparison of I, results of the comparisons change when the thread culture is changed. This is the output:

Culture = English (United States)
(file == FILE) = True
Culture = Turkish (Turkey)
(file == FILE) = False

**Comment by miyconst** [comment] 2018-12-04 08:42
Aha! Thank you @SenerDemiral for nailing the issue down, I tested with `se-SE` collation and that's why it worked for me.

@alemoi this looks like an issue in URI matcher or related component, where string comparison happens, please follow up.

**Comment by alemoi** [comment] 2018-12-04 15:48
I have investigated this and found the problem. And the problem is in some Starcounter strings comparison, that are not culture independent. So, when you set current thread culture to something non-standard - than it persists on the threads for other non-user code as well. In this case its in `Starcounter.XSON` here: https://github.com/Starcounter/Starcounter.XSON/blob/develop/src/Starcounter.XSON/Helpers/MimeTypeHelper.cs#L40
which by itself is used here: `if (request.PreferredMimeType != MimeType.Application_Json)` from https://github.com/Starcounter/level1/blob/develop/src/Starcounter.Apps.JsonPatch/BuiltInRestHandlers/PuppetRestHandler.cs#L179 and other places of course.
Therefore string comparison should be made independent in Starcounter.
@miyconst I'm not sure if that is correct but will assign @erikvk for this, since its `Starcounter.XSON` repo issue so far.

**Comment by SenerDemiral** [comment] 2018-12-04 19:22
This is the reason why the same error occurs if Windows region/country is set to TR.

**Comment by erikvk** [comment] 2019-04-08 09:02
I have pushed fixes to XSON to address this, and test to validate, in PR https://github.com/Starcounter/Starcounter.XSON/pull/63 for those of you who can see it. Closing this as fixed.

**Comment by miyconst** [comment] 2019-04-08 15:17
Thank you for the fix @erikvk . Closing.

**Closed by miyconst** 2019-04-08 15:17 UTC
Labels: bug, investigate, json, json-typed
