### ISSUE TITLE
Administrator SQL Panel features

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#143] opened 2017-06-03 17:25 UTC
A wishlist of features for the admin sql panel:

* Add execution time and row count to query result
* Add palette of common snippets: create index etc.
* "Copy to Code" translate Query to C# snippet running the SQL, e.g. scalar queries to a scalar query and entity queries to a QueryResultRows

**Comment by miyconst** [comment] 2017-06-03 20:40
cc @andwah

**Comment by k-rus** [comment] 2017-06-05 05:16
Thank you for your suggestion!



> Add execution time and row count to query result

Can you elaborate about execution time? What kind of time do you expect to see here? How do you reason about the time, what kind of conclusions can you derive from it?

**Comment by rogeralsing** [comment] 2017-06-05 05:30
To know how the query engine behaves, e.g. `select count (s) from Spender s` seems to be a slow operation if there is much data.
if your app behaves oddly, it would be a good thing to be able to verify if it is due the query or something else.

**Comment by k-rus** [comment] 2017-06-05 06:01
> To know how the query engine behaves, e.g. select count (s) from Spender s seems to be a slow operation if there is much data.
> if your app behaves oddly, it would be a good thing to be able to verify if it is due the query or something else.

Thank you for clarification!

It is difficult to provide execution time, which will allow to reason about execution time of a query in an app for any query. It will work for long running queries, which return small results like in the example, but the difference for short running queries between Administrator and an app will be significant.

Another problem is the queries, which return large result sets. In such case the query doesn't need to be executed completely, but can be executed to return only part of the result (to cover visible page in Administrator). Furthermore, an app code iterates over result, while needed, and not over complete result. Thus potential mismatch between execution times. In current implementation of SQL and API to it, obtaining entire result set for a query returning million rows might take seconds, while obtaining just 10 rows can result in microseconds. 

Note that partial result can be also a problem to provide the row count.

We are aware that SQL execution does not perform well for certain query classes and we are working on significant improvements. However, it will be always possible to write queries, which will be expensive to execute. Providing feedback on execution time of queries will be always needed. Benchmarking is usually used for this, but it is not so convenient for users. So we need to come up with some strategy/way, which will be meaningful and will not degrade general performance of entire system.

**Comment by threezool** [comment] 2017-06-05 06:12
A feature i would like to se added is a button to the database beside Start and Delete that drops all tables. This should have the same security check as deleting the table.

**Comment by miyconst** [comment] 2019-12-06 11:08
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:08 UTC
Labels: enhancement, nice to have, tools-admin-ui, won’t fix
