### ISSUE TITLE
Transaction.Current is null inside Db.Transact

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#212] opened 2017-08-28 12:38 UTC
What are the facts
---
```c#
Db.Transact(() => Transaction.Current == null) // returns true
```

What is the problem
---
This is confusing, especially since there is no other obvious way to roll back a transaction (other than `Transaction.Current.Rollback`). [This is documented](https://docs.starcounter.io/guides/transactions/using-transactions/#dbtransact-and-dbtransactasync-usage), but it's not that easy to understand that `Transaction.Current` has nothing to do with `Db.Transact`. 

What could be done about it
---
1. `Transaction.Current` could return a usable object when invoked inside `Db.Transact`. This will probably be hard to implement, but would be most readable and obvious for user
1.  `Transaction.Current` could have a docstring explaining that it doesn't work in `Db.Transact` and docs page could be updated explaining how to roll back a `Db.Transact`<sup>1</sup>

----

<sup>1</sup> Docs currently say "Due to this, if there's a need to rollback changes, use `Db.Scope` over `Db.Transact`" suggesting it's impossible to roll back `Db.Transact`. AFAIK you can do it by throwing an exception

**Comment by miyconst** [comment] 2019-12-06 11:11
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:11 UTC
Labels: awaiting, db, won’t fix
