### ISSUE TITLE
Optimization Suggestion: Replace lambdas/delegates with C# 7 Local Functions

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#197] opened 2017-08-05 14:18 UTC
Using lambdas/delegates cause allocations which result in GC pressure.
In C# 7, we have local functions, local functions compile to normal static functions, even if they capture local variables. 

See: https://asizikov.github.io/2016/04/15/thoughts-on-local-functions/

**Comment by bigwad** [comment] 2017-08-07 08:23
Could you point to the places you think would take advantage of this?
I believe it depends on usage. If the intent of a lambda is to structure function code, i.e. local function would be called explicitly in the scope of the parent function, then it's true. Otherwise, if it's being passed somewhere as a Func/Action/delegate - it should have no difference. I doubt we have significant cases of the former usage if any. 

I might be wrong and would like to prepare proves with IL analysis. Real sample from starcounter code would help it to be in point.

**Comment by miyconst** [comment] 2017-08-31 08:13
@rogeralsing please provide some more specific examples of what and where should be replaced or close the issue if it can wait.

**Comment by miyconst** [comment] 2019-12-06 11:11
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:11 UTC
Labels: won’t fix
