### ISSUE TITLE
Starpack unable to execute with release mode

### ISSUE THREAD

**Issue by habib535** [Starcounter/Home#205] opened 2017-08-16 12:51 UTC
I've build my project in release mode and I want to build package.zip from the exe generated under release folder using the following command

`starpack -p -c=release`
`starpack -p -c='release'`

but I get the following errors
`Visual Studio project file not found (-c=release)`

Can someone please help me in writing the right command?

**Comment by andwah** [comment] 2017-08-16 13:42
I can just confirm that this is true, there is some issues around the -c argument, i have still not figured out why it sometimes/all the time picks the wrong configuration when using the -c argument.

Sometimes i need to rebuild both debug and release to make it work and even then it sometimes picks the 'debug' version when i used -c=release.

**Comment by miyconst** [comment] 2019-12-06 11:11
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:11 UTC
Labels: bug, desired, enhancement, tools, won’t fix
