### ISSUE TITLE
Robocopy of ImageDirectory

### ISSUE THREAD

**Issue by careri** [Starcounter/Home#363] opened 2018-01-25 15:12 UTC
Hi,

we're using shadowcopy to make backups of the database files.
I use robocopy /mir to mirror the files into another folder with shadowspawn.

But now I realize that last write doesn't change on your image/log files. So my backups doesn't contain any new data.

Is this by design or a bug?

**Comment by careri** [comment] 2018-01-26 08:27
It doesn't seem like copying the data-folder with shadownspawn works at all, that latest data isn't available.
Any input on that?
@eriohl @per-samuelsson

**Comment by per-samuelsson** [comment] 2018-01-26 08:47
Hi @careri,

I think @bigwad is the one with most knowledge about this. I know there are some docs somewhere. Let's see if he can link to that.

**Comment by bigwad** [comment] 2018-01-26 10:28
I carried out following test:
1. Start a database
2. Make a write
3. Copy database files to another location. For copying, I used conventional `copy` command
4. Start a new database instance over copied data
5. See the write from p2

With that, I can conclude:
- writes reaches transaction log
- a cloned database is able to see it
- problems are probably with shadowspawn

@careri, can I ask you to try copying a database without shadowspawn? In the meanwhile, I'll try out shadowspawn myself.

**Comment by bigwad** [comment] 2018-01-26 10:50
The actual problem is that `robocopy` ia unable to detect log file being changed. This is because robocopy seems to rely on the file modification timestamp. Which is fine, but incompatible with starcounter IO method. Starcounter uses such IO mode, that requires explicit flushing of a file metadata (which includes modification timestamp). And we don't flush metadata to maximize log writing thoughput.

**Comment by careri** [comment] 2018-01-26 13:31
Nah, robocopy isn't the problem. I use the /IS switch to force copy same items.
So files are copied as far as I can tell.

Could you try that to confirm?

**Comment by careri** [comment] 2018-01-26 13:32
@bigwad 

I have a question about your list above.
1,2 is clear.
But 3 isn't possible without stopping the database. So I guess you did that?

The whole issue here is using shadowspawn to copy locked files, and shadowspawn not being able to get the writes

**Comment by miyconst** [comment] 2018-01-26 13:36
@careri please specify the full steps of how you perform the copy, including all command lines commands.

**Comment by bigwad** [comment] 2018-01-26 13:48
>But 3 isn't possible without stopping the database. So I guess you did that?

It is. Starcounter allows shared reads.

>Nah, robocopy isn't the problem. I use the /IS switch to force copy same items.

That's true. With /IS all files get copied regardless of timestamp. So given you use /IS then probably the problem is with `shadowspawn`.

**Comment by careri** [comment] 2018-01-26 13:52
Are you sure about that?
Because I used powershell to compute hash of the logs to compare with  shadowcopied files. I got read error on two of the files

**Comment by bigwad** [comment] 2018-01-26 13:59
>Are you sure about that?

absolutely

>Because I used powershell to compute hash of the logs to compare with shadowcopied files. I got read error on two of the files

Seems it tried to open files for writing for some reason. If no way you can open it for reading only, then you can first copy it (command line or explorer - all work) and get hash of the copy

**Comment by careri** [comment] 2018-01-26 14:05
Sounds strange that it would open it for writing, but I can't confirm that now.

But still we need to use shadowspawn to get a consistent snapshot of all the files at a certain point in time.
Could you confirm that your test works with shadowspawn as well? Because it sure doesn't in our environments

**Comment by bigwad** [comment] 2018-01-26 14:53
>Could you confirm that your test works with shadowspawn as well? Because it sure doesn't in our environments

Works for me with `robocopy /IS`

**Comment by miyconst** [comment] 2018-01-26 15:22
Also works for me, I just made a backup of a live database using the following command. The destination folder was empty.

```
ShadowSpawn.exe C:\Users\User\Documents\Starcounter\Personal\Data\default\Default-20180126T145615258\ Q:\ robocopy Q:\ "D:\Temp\ShadowSpawn-0.2.2-x64\Backup\%date:~10,4%.%date:~4,2%.%date:~7,2%-%TIME:~0,2%.%TIME:~3,2%" /s
```

**Comment by per-samuelsson** [comment] 2018-01-27 08:44
Just want to assure something here: @careri, what Starcounter version are you using? 

Just want to make sure we are not talking 1.x here, since things have changed quite a bit. :)

**Comment by careri** [comment] 2018-01-28 08:26
I'll try to put together a script on monday that shows that it doesn't work. At least not in our environment.
@miyconst, yes the files get copied but the content of the files seems to be from the last start/stop of the server.
Any changes after the db is started is not transfered to the backup

**Comment by careri** [comment] 2018-01-29 09:48
@per-samuelsson, no this is 2.3 we're talking about.
Making a github project that aims to reproduce the problem.

@bigwad About shared reads, your right. I was using a remote powershell session that wasn't elevated, so it was a simple file access issue

**Comment by miyconst** [comment] 2018-01-29 10:52
>@miyconst, yes the files get copied but the content of the files seems to be from the last start/stop of the server.

@careri I understand your problem, and saying "works", I mean that the files **with latest transactions** are copied. Sorry for not being clear.

Maybe your issue is somehow related to the storage setup. For example network drive, RAID array(s). Can you please specify full hardware specification, so I can try to reproduce?

**Comment by careri** [comment] 2018-01-31 16:35
@miyconst @bigwad  @andwah 

I finally got a project working that uses shadowspawn to copy files. I think my problem was that I wrote to StdErr which caused shadowspawn to exit directly without completing the copying.
https://github.com/careri/StarcounterShadowspanTest.git

Clone the project and open a PowerShell ISE "run as administrator"
Execute the script **run.ps1**  with F5

I still have to confirm this. But at least my script seems to be copying at the moment. Once I get the restore fully working I intend to run the script every 10 seconds a 100 times to see that it really works

# The new problem seems to be restore the backup. 
1. Delete db using rest **scshadowtest**
2. Delete any trailing folders in personal\data and personal\database
3. robocopy the files back
4. Run staradmin start db **scshadowtest**

I get a new sequence number under data for some reason.

Step 4 fails with this exception:
>ScErrUnexpectedCommandException (SCERR10016): Creating database scshadowtest failed due to an unexpected problem.
Version: 2.3.1.7971.
Help page: https://docs.starcounter.io/v/2.3.1/?q=SCERR10016.
 System.IO.IOException: Cannot create a file when that file already exists.

>   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at Starcounter.Server.DatabaseSetup.CreateFiles() in C:\TeamCity\BuildAgent\work\sc-11696\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 124
   at Starcounter.Server.DatabaseSetup.CreateDatabase() in C:\TeamCity\BuildAgent\work\sc-11696\Level1\src\Server\Starcounter.Server\CoreServices\DatabaseSetup.cs:line 134
   at Starcounter.Server.Commands.CreateDatabaseCommandProcessor.Execute() in C:\TeamCity\BuildAgent\work\sc-11696\Level1\src\Server\Starcounter.Server\Commands\Processors\CreateDatabaseCommandProcessor.cs:line 33
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\TeamCity\BuildAgent\work\sc-11696\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
HResult=-2147024713

**Comment by careri** [comment] 2018-02-01 12:10
Think I have things figured out now. 
There was two problems.
1. I wrote to StdErr which cause shadowspawn or maybe powershell to stop directly.
2. I didn't stop the starcounter service during data restore, so starcounter didn't detect that I had restored the database and tried to create a new one

**Comment by miyconst** [comment] 2018-02-01 12:19
@careri is there anything else I can help with?

**Comment by careri** [comment] 2018-02-02 06:46
Well, should it be possible to restore a database without restarting the service?
Also there seems to be a partial file lock on:
> Starcounter\Personal\Data\scshadowtest\scshadowtest-20180201T113830946\scshadowtest.cfg

So I can't compute hash on that one, is this by design?

**Comment by miyconst** [comment] 2018-02-02 09:59
>Well, should it be possible to restore a database without restarting the service?

No, that's not currently supported.

>Starcounter\Personal\Data\scshadowtest\scshadowtest-20180201T113830946\scshadowtest.cfg
>So I can't compute hash on that one, is this by design?

It's a configuration file, it contains no user data, @bigwad please clarify regarding the file lock and hash computation.

**Comment by bigwad** [comment] 2018-02-02 10:04
>>Starcounter\Personal\Data\scshadowtest\scshadowtest-20180201T113830946\scshadowtest.cfg

>So I can't compute hash on that one, is this by design?

It's locked, but allows shared reads, so shouldn't be a problem to calculate a hash. Can you copy it? How do you produce hash?

**Comment by bigwad** [comment] 2018-02-02 10:11
>It's a configuration file, it contains no user data

It's true. The file is read-only. You can get this file updated only if you recreate a database by the same path, which seems to be impossible with our tools.

**Comment by careri** [comment] 2018-02-02 10:18
@miyconst Ok, so now I know that I must always restart the service on restore.

@bigwad I open the stream with read access, fileshare read,write and delete
```c#
using System;
using System.Collections.Concurrent;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Threading;

namespace Heads.FileDiff
{
    internal class SHA256Provider : IHashProvider
    {
        private static readonly ConcurrentDictionary<int, SHA256> s_instances = new ConcurrentDictionary<int, SHA256>();

        public string Compute(FileInfo fi)
        {
            try
            {
                using (var stream = fi.Open(FileMode.Open, FileAccess.Read, FileShare.Delete | FileShare.ReadWrite))
                {
                    return Compute(stream);
                }
            }
            catch (Exception ex)
            {
                throw new ApplicationException($"[{fi.FullName}] access error", ex);
            }
        }

        public string Compute(Stream stream)
        {
            var sha256 = s_instances.GetOrAdd(Thread.CurrentThread.ManagedThreadId, id => SHA256.Create());
            var bytes = sha256.ComputeHash(stream);
            return Convert.ToBase64String(bytes);
        }

        public void Dispose()
        {
            var instances = s_instances.Values.ToArray();
            DisposeHelper.DisposeAll(instances);
            s_instances.Clear();
        }
    }
}
```

**Comment by bigwad** [comment] 2018-02-02 11:15
The problem with hashing is that the file is locked beyond end-of-file to allow reading the file, but .Net FileStream tries to read further end-of-file, thus getting an error. As a workaround, I can suggest using `File.ReadAllBytes`, as it reads an exact number of bytes and doesn't go beyond end-of-file. And I'll create an issue to make locking schema more friendly.

**Comment by careri** [comment] 2018-02-02 12:06
Well, I don't want to use ReadAllBytes since e.g. the image/log files are 256MB.

I dont understand what you're saying. Are you locking bytes after end of file?
So I could use length of the file and read that many bytes?

**Comment by careri** [comment] 2018-02-02 12:40
The hashing of files was a sanity check that shadowcopy really exposed the new files and not some old copy.
It's not a thing I will use in the real application.
But I'll try to update the hashing to support that file as well

**Comment by careri** [comment] 2018-02-02 13:56
I can confirm that limiting the number of bytes to read works:
```C#
using (var stream = fi.Open(FileMode.Open, FileAccess.Read, FileShare.Delete | FileShare.ReadWrite))
using (var limitedStream = new LimitedStreamDecorator(stream, fi.Length, false))
```

**Comment by miyconst** [comment] 2018-02-05 13:53
@careri am I right that all your questions/issues were answered/resolved? So far I see the following items to improve in the documentation:

- Restore database binaries requires Starcounter server restart.
- Database configuration `*.cfg` file is locked while database is started. 
- The configuration `*.cfg` file never changes during the database lifetime, so it's not required to back it up every time.
- Starcounter does not update `Date modified` attribute of the transaction log files for better performance. Those, it's not possible to use the `Date modified` value to see if there are any changes.

**Comment by careri** [comment] 2018-02-07 10:25
Yeah, I think I have things figured out.

**Comment by careri** [comment] 2018-02-07 13:47
@miyconst 

Well, I didn't have things figured out it seems.

My test project works locally on my developer machine, Windows 10.

But running the same scripts on our Windows Server 2016 yields backups without data. 
Have you verified that shadowspawn works on 2016?

**Comment by miyconst** [comment] 2018-02-07 14:05
>@miyconst
>
>Well, I didn't have things figured out it seems.
>
>My test project works locally on my developer machine, Windows 10.
>
>But running the same scripts on our Windows Server 2016 yields backups without data.
>Have you verified that shadowspawn works on 2016?

@careri I didn't try it on Windows Server 2016, but I can do that if required.

I no longer see your message, did you delete it? Were you able to solve the issue?

**Comment by careri** [comment] 2018-02-08 09:50
@miyconst Please try on Server 2016

Yeah, I realized that I was using a version of shadowcopy that required VC++ Redist 2010.
So I though that was the problem.

But now I have come to the conclusion that your custom way of writing the translog files isn't compatible with Server 2016.

If I run my project locally on Windows 10 it works.
https://github.com/careri/StarcounterShadowspanTest.git

But running the exact same code on Server 2016 fails after a couple of itterations, shadowspawn produces shadowcopies that are not up to date.


To confirm the problem I put togheter a small program that creates 2 x 256mb files.
Loops 512 times writing one megabyte at the time. Where the first loop writes the first mb of file 1 and the last loop writes the last mb of file 2.

So the main flow:
1. Create files
2. Loop 0 -> 511
3. Write one block
4. Backup the files with shadowspawn
5. Restore the files from the backup
6. Verify the hash of the last written hash
7. Next loop

```c#
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Cryptography;

namespace ShadowSpawnTest
{
    class Program
    {
        private static readonly string s_workingDir;
        private static readonly int s_verbosity = 2;

        static Program()
        {
            s_workingDir = System.IO.Directory.GetCurrentDirectory();
        }

        public class Megabyte
        {
            public const int One = 1024 * 1024;

            public static int ToBytes(int mb) => One * mb;
        }

        static void Main(string[] args)
        {
            // Create two 256 mb  files and write to their streams
            var assFI = new FileInfo(new Uri(typeof(Program).Assembly.Location).LocalPath);
            var shadowspawn = new FileInfo(Path.Combine(assFI.DirectoryName, "shadowspawn.exe"));

            if (!shadowspawn.Exists)
            {
                Error($"[Shadowspawn] {shadowspawn.FullName} doesn't exists", -1);
            }
            var sizeMB = 256;
            var sizeBytes = Megabyte.ToBytes(sizeMB);
            var count = 2;
            var buffer = new byte[Megabyte.One];
            var rnd = new Random();

            // Setup the files
            Section("Creating files");
            for (int i = 0; i < count; i++)
            {
                var fi = GetFile(sizeMB, i);
                fi.Directory.Create();

                using (var stream = fi.Open(FileMode.Create, FileAccess.ReadWrite, FileShare.Read))
                {
                    Info($"Creating: {fi.FullName}");
                    stream.SetLength(sizeBytes);
                }
            }
            var blockCount = (int)(sizeMB * count);

            Section($"Writing blocks 0 -> {blockCount}");

            using (var md5 = MD5Cng.Create())
            {
                for (int i = 0; i < blockCount; i++)
                {
                    rnd.NextBytes(buffer);
                    var expected = Convert.ToBase64String(md5.ComputeHash(buffer));
                    WriteFile(sizeMB, buffer, i);

                    // Shadow Copy
                    MakeShadowCopy(shadowspawn);

                    // Restore the shadowcopy
                    RestoreBackup();

                    // Now read the block
                    ReadFile(sizeMB, buffer, i);
                    var actual = Convert.ToBase64String(md5.ComputeHash(buffer));

                    if (!string.Equals(expected, actual))
                    {
                        Error($"[Restore] Failed to restore data block, hash mismatch: {expected} != {actual}", -11);
                    }
                } 
            }
        }

        private static void Section(string v)
        {
            Info($"{Environment.NewLine}* {v}{Environment.NewLine}");
        }

        private static DirectoryInfo DataDI => new DirectoryInfo(Path.Combine(s_workingDir, "Data"));

        private static DirectoryInfo BackupDI => new DirectoryInfo(Path.Combine(s_workingDir, "Backup"));

        private static void MakeShadowCopy(FileInfo exe)
        {
            Section($"ShadowCopy");
            var drive = GetFreeDrive();
            var backupDI = BackupDI;
            backupDI.Create();
            var rcArgs = GetRobocopyCommand(drive + ":\\", backupDI.FullName);
            var args = $"/verbosity={s_verbosity} \"{DataDI.FullName}\" {drive}: {rcArgs}";
            var info = "Shadowspawn";
            var exitCode = Run(info, exe.FullName, args);

            if (exitCode > ExitCodes.OK)
            {
                // Removed the shadowcopy offset to get the real exit code
                exitCode = exitCode - ExitCodes.OK;
            }
            else
            {
                if (exitCode == -1073741515)
                {
                    // Missing VC++
                    Error($"{info} Missing VC++ Redistribule, shadowspawn doesn't work", exitCode);
                }
                Error($"{info} Failed with exit coode {exitCode}", exitCode);
            }

            if (exitCode >= 7)
            {
                Error($"{info} robocopy failed with exit code: {exitCode}", exitCode);
            }
            
        }

        private static void RestoreBackup()
        {
            Section($"RestoreBackup");
            var drive = GetFreeDrive();
            var rcArgs = GetRobocopyArgs(BackupDI.FullName, DataDI.FullName);            
            var info = "Robocopy";
            var exitCode = Run(info, info, rcArgs);

            if (exitCode >= 7)
            {
                Error($"{info} failed with exit code: {exitCode}", exitCode);
            }

        }

        private static int Run(string info, string exe, string args)
        { 
            var watch = Stopwatch.StartNew();

            using (var p = new Process())
            {
                var psi = p.StartInfo;
                
                psi.FileName = exe;
                psi.UseShellExecute = false;
                psi.Arguments = args;
                psi.RedirectStandardError = true;
                psi.RedirectStandardOutput = true;
                Info($"{info} {psi.Arguments}");
                p.OutputDataReceived += OnProcessOut;
                p.ErrorDataReceived += OnProcessError;
                p.Start();
                p.BeginOutputReadLine();
                p.BeginErrorReadLine();

                p.WaitForExit();
                p.OutputDataReceived -= OnProcessOut;
                p.ErrorDataReceived -= OnProcessError;

                Info($"{info} Took {watch.Elapsed}");
                return p.ExitCode;
            }
        }

        private static string GetRobocopyCommand(string from, string to)
        {
            return $"robocopy {GetRobocopyArgs(from, to)}";
        }

        private static string GetRobocopyArgs(string from, string to)
        {
            return $"{from} {to} /MIR /NP /ndl /njh"; // /IS";
        }

        private static void OnProcessError(object sender, DataReceivedEventArgs e)
        {
            Warn(e.Data);
        }

        private static void OnProcessOut(object sender, DataReceivedEventArgs e)
        {
            Write(e.Data, ConsoleColor.Cyan);
        }

        internal static char GetFreeDrive()
        {
            var drives = Directory.GetLogicalDrives().ToDictionary(d => d.ToLower()[0]);

            for (char i = 'a'; i < 'z'; i++)
            {
                if (!drives.ContainsKey(i))
                {
                    return i;
                }
            }
            throw new ApplicationException("No free drive letter, cancelling mapping of drive");
        }


        private static void WriteFile(int sizeMB, byte[] buffer, int writeIndex)
        {
            Section($"Writing index: {writeIndex}");
            StreamOperation(FileAccess.Write, sizeMB, buffer, writeIndex, (s, b) => s.Write(buffer, 0, buffer.Length));
        }

        private static void ReadFile(int sizeMB, byte[] buffer, int writeIndex)
        {
            Section($"Read index: {writeIndex}");
            StreamOperation(FileAccess.Read, sizeMB, buffer, writeIndex, (s, b) => s.Read(buffer, 0, buffer.Length));
        }

        private static void StreamOperation(FileAccess access, int sizeMB, byte[] buffer, int writeIndex, Action<Stream,byte[]> streamAction)
        { 
            var fileIndex = (writeIndex / sizeMB);
            var offset = writeIndex - (fileIndex * sizeMB);
            var writeFI = GetFile(sizeMB, fileIndex);

            using (var stream = writeFI.Open(FileMode.Open, access, FileShare.Read))
            {
                var offsetBytes = Megabyte.ToBytes(offset);
                Info($"[{writeFI.Name}] reading @ {offsetBytes}");
                stream.Seek(offsetBytes, SeekOrigin.Begin);
                streamAction(stream, buffer);                
            }
        }

        private static FileInfo GetFile(int sizeMB, int i)
        {
            return new FileInfo(Path.Combine(DataDI.FullName, $"data.{sizeMB}.{i}.dat"));
        }

        private static void Info(string v)
        {
            Write(v, ConsoleColor.Green);
        }

        private static void Warn(string v)
        {
            Write(v, ConsoleColor.Yellow);
        }

        private static void Write(string v, ConsoleColor writeColor)
        {
            var c = Console.ForegroundColor;

            try
            {
                Console.ForegroundColor = writeColor;
                Console.WriteLine(v);
            }
            finally
            {
                Console.ForegroundColor = c;
            }
        }

        private static void Error(string msg, int exitcode)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.Error.WriteLine(msg);

            if (Debugger.IsAttached)
            {
                Console.Error.WriteLine("Waiting for debugger");
                Debugger.Break();
            }

            Environment.Exit(exitcode);
        }

        private abstract class ExitCodes
        {
            public const int ProcessingError = 1;
            public const int UserError = 2;
            public const int OK = 0x8000;

            public const string Help =
@"Exit Status:

If there is an error while processing (e.g. ShadowSpawn fails to
create the shadow copy), ShadowSpawn exits with status 1.

If there is an error in usage (i.e. the user specifies an unknown
option), ShadowSpawn exits with status 2.

If everything else executes as expected and <command> exits with
status zero, ShadowSpawn also exits with status 0.

If everything else executes as expected and <command> exits with a
nonzero status code n, ShadowSpawn exits with status n logically OR'ed
with 32768 (0x8000). For example, robocopy exits with status 1 when
one or more files are Scopied. So, when executing

  shadowspawn C:\foo X: robocopy X:\ C:\path\to\backup /mir

the exit code of ShadowSpawn would be 32769 (0x8000 | 0x1).";
        }
    }
}

```

**Comment by careri** [comment] 2018-02-08 09:51
Just out of interest are you doing something like this to write without affection lastwrite:
https://stackoverflow.com/questions/15903972/how-to-change-a-file-without-affecting-the-last-write-time

I would like to be able to reproduce the problem

**Comment by miyconst** [comment] 2018-02-08 10:36
@careri am I right that you are trying to replicate files and file writes which happen during a Starcounter database lifetime? Then perform shadow copy using `ShadowSpawn`.

This works under Windows 10, but does not work on Windows Server 2016, and by "does not work" I mean that shadow copy does not contain the latest writes.

**Comment by careri** [comment] 2018-02-08 10:49
@miyconst  
Yes, that pretty much sums up the problem.

To get around the problem I added two properties:
RunBefore
RunAfter

The RunBefore is executed before shadowcopying
And RunAfter is executed after shadowcopying
```js
  "RunBefore": "sc stop CustomBatchWatchdog;staradmin stop db headswms",
  "RunAfter" : "staradmin start db headswms;sc start CustomBatchWatchdog",
```

RunBefore: Before copying I stop custom watchdog service and stop headswms database.
I then use shadowspawn to copy the files
RunAfter: Start headswms database and then custom watchdog


This approach works, the files are updated.
So I'm guessing it has something to do with how you write the files. Windows Server 2016 doesn't detect your file changes and therefore serves up an old version.

But stopping the database releases your "custom" handle to the files and thus updating some flag that makes windows detect the change

**Comment by careri** [comment] 2018-02-08 10:53
Of course the shadowspawn part serves no purpose in the previous comment. Just  proof that it works if I stop the database

**Comment by bigwad** [comment] 2018-02-08 12:18
>Seems like your using memory mapped files for the trans-log right?

Actually, not. Instead, we open a file with FILE_FLAG_WRITE_THROUGH|FILE_FLAG_NO_BUFFERING.
Please try your test with a stream opened with [WriteThrough](https://msdn.microsoft.com/en-us/library/system.io.fileoptions(v=vs.110).aspx) option passed to a FileStream(https://msdn.microsoft.com/en-us/library/d0y914c5(v=vs.110).aspx)

**Comment by careri** [comment] 2018-02-08 14:41
@bigwad @miyconst 

I can now confirm that Windows Server 2016 (only tried one installation so far) doesn't work with shadowspawn and **FILE_FLAG_WRITE_THROUGH|FILE_FLAG_NO_BUFFERING**

You can clone this program to try it:
https://github.com/careri/StarcounterShadowspanTest/blob/master/src/ShadowSpawnTest/Program.cs

Running it on my win10 machine works. Running it on server2016 fails after a couple of itterations. Usually the second.

**Comment by careri** [comment] 2018-02-08 15:32
Well, this is confusing.  It seems that it doesn't work on 2016 even if I use FileOptions.None

Time to change line of work, crap!

**Comment by careri** [comment] 2018-02-09 10:09
@miyconst @bigwad 

Could you please verify this insanity.
1. Open an elevated powershell on windows server 2016
2. Run my script directly from github (downloads):
```iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/careri/StarcounterShadowspanTest/master/server2016_fail.ps1'))```
3. The script works, the content of the file being copied with shadowspawn is 8 bytes. It only contains the bytes for the current datetime ticks
4. Break the script after e.g. 10 itterations or something
5. Increase the file size to 64MB using the environment variable:
```$env:SERVER_FAIL_SIZE=64```
6. Go to step 2, it will fail on the second itteration. Or one of the following

Any ideas?

**Comment by bigwad** [comment] 2018-02-09 11:40
will try today and get back to you

**Comment by bigwad** [comment] 2018-02-09 15:48
@careri, regarding the script `server2016_fail.ps1` you asked to run. Probably, I'm missing something, but it seems it has two clear issues:
1. `FileStream.Flush()` may not flush OS buffers, so I switched to `FileStream.Flush(true)`
2. You seem to compare sequences of a different length. First one is always 8 bytes you get from `Get-Date` and the second is a content of the file, which size is controlled by env:SERVER_FAIL_SIZE

You can see proposed changes here:
https://github.com/careri/StarcounterShadowspanTest/pull/1

Also, as we discussed earlier `/IS` flag for robocopy would be useful. But in this case it's not mandatory as metadata is flushed by `FileStream.Flush(true)` call.

**Comment by bigwad** [comment] 2018-02-09 15:51
Now, I'm checking out c# test program you mentioned here https://github.com/Starcounter/Home/issues/363#issuecomment-364131967

**Comment by careri** [comment] 2018-02-12 14:13
Ah I introduced the env:SERVER_FAIL_SIZE late, my bad with the byte-compare.
I'll fix that, and try again

**Comment by bigwad** [comment] 2018-02-15 11:54
As to c# test program - the problem is still with `robocopy /IS`:  robocopy doesn't copy files it considers the same even with `/IS` switch. All the difference `/IS` makes is that those files get reported.
Here is a similar question: https://stackoverflow.com/questions/40744335/how-do-i-force-robocopy-to-overwrite-files.
I thinks we should reconsider our recommendations of using robocopy for making incremental backup.

**Comment by miyconst** [comment] 2018-02-15 12:19
The only place where we mention the incremental backups says:

>Copying is done with robocopy utility that ships with Windows, you can use any other command, e.g. you can call your favorite incremental binary backup utility and store the result in a cloud.

[Database Backups](https://docs.starcounter.io/guides/working-with-starcounter/run-starcounter-in-production#database-backups).

Probably it should be updated with info, that incremental backups are not supported.

**Comment by bigwad** [comment] 2018-02-15 12:32
>Probably it should be updated with info, that incremental backups are not supported.

Log files are assigned with incremental numbers and once we have switched to a file, we never write to a previous one. With that incremental backup is possible - backup script just has to overwrite two files with greatest numbers regardless.

**Comment by careri** [comment] 2018-02-15 13:06
Ok, I'll implement my own copy using hash-check on the files.

I can confirm that the byte check using SERVER_FAIL_SIZE was my bad. I fixed it and the script works on Server 2016:
https://raw.githubusercontent.com/careri/StarcounterShadowspanTest/master/server2016_fail.ps1

**Comment by careri** [comment] 2018-02-15 13:10
@bigwad Thanks for linking to:
https://stackoverflow.com/questions/40744335/how-do-i-force-robocopy-to-overwrite-files.

So it's merely an update of the documentation that needs to be done.

**Comment by careri** [comment] 2018-02-21 16:13
@bigwad @miyconst 

FYI
robocopy that ships with Windows 10 has a working implementation of /IS
Win10, version 10.0.16299.15
Server 2016, 10.0.14393.0

I ran the script you linked to on stackoverflow.
Win10 it works as expected
Win2016 it doesn't copy the file

**Comment by bigwad** [comment] 2018-02-21 16:50
>robocopy that ships with Windows 10 has a working implementation of /IS

Then it's a problem on it own. Working /IS option defeats the purpose of using robocopy - making an incremental backup. As I said, to make backup incremental - one has to overwrite two latest log files and then run robocopy without /IS on top.

**Comment by careri** [comment] 2018-02-23 06:02
Yes, I agree with thaht. Just wanted to provide the information, if you wanted to state it in the documentation.
I'm moving away from robocopy.

**Comment by Mackiovello** [comment] 2018-03-28 09:27
Information added to documentation in https://github.com/Starcounter/Docs/pull/205

Closing as done

**Closed by Mackiovello** 2018-03-28 09:27 UTC
Labels: docs, investigate, question
