### ISSUE TITLE
Set database by env var in star.exe / staradmin.exe

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#184] opened 2017-07-20 12:52 UTC
Currently it's possible to start an app in a specific database by passing `-d=dbname` to it. It should also be possible to set the default database name by env var. That would make possible to run in a non-default DB those apps whose authors didn't think about it when writing their startup scripts.
This env var should override the default database, so all the `star` and `staradmin` commands would be affected

The precedence should be:
1. `-d` specified on CLI
1. `STARCOUNTER_DATABASE` env var
1. `default`

If you have a better idea for a name, don't hesitate to propose it!

**Comment by per-samuelsson** [comment] 2017-08-09 10:56
If we decide to do this, it's quite prepared for. All access to resolve the name of the database to use in all CLI-based management operations already utilize a shared authority - method `SharedCLI.ResolveDatabase`. It's an easy enhancement there + adding some tests and extending `star`/`staradmin` help messages basically.

One word of caution though - there might be other spots (e.g. webadmin, etc) where the name of the default database will be used if not given. If we fail to find and also include those, it's better not to support this kind of configuration at all IMO.

**Comment by k-rus** [comment] 2017-08-11 06:03
> It should also be possible to set the default database name by env var.

The problem is that people tend to forget about the setting and spend a lot of time trying to understand why it doesn't work as expected. Environment variable is questionable solution.

**Comment by joozek78** [comment] 2017-08-14 09:45
> It should also be possible to set the default database name by env var.
> The problem is that people tend to forget about the setting and spend a lot of time trying to understand why it doesn't work as expected. Environment variable is questionable solution.

This would solve real problems and it's totally optional. Anything could confuse people, but I don't think it's enough of a reason to reject something

**Comment by miyconst** [comment] 2019-12-06 11:10
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:10 UTC
Labels: enhancement, nice to have, tools, windows, won’t fix
