### ISSUE TITLE
Prevent loosing open transaction on page refresh

### ISSUE THREAD

**Issue by papusa** [Starcounter/Home#112] opened 2017-05-16 09:52 UTC
As I understand currently there is no way to prevent transaction loss on page refresh. 

In our app we have a functionality which consists of few steps. Each step is a separate page inside master page. We need to commit transaction only on the last page (step). To achieve this we are storing transaction inside the master page. Unfortunately, it doesn't work if any page is refreshed - transaction and it's data is getting lost, which is rising exceptions.

I think it will be useful to have a possibility to prevent current transaction form a loss.

**Comment by mmnosek** [comment] 2017-05-16 09:54
cc @chrhol @alemoi could you please help with this?

**Comment by chrhol** [comment] 2017-05-22 07:01
Hi @papusa,
what do you mean by page refresh? Do you mean attaching a new page to the master page, or refresh of a browser tab?

What exceptions do you get, could you post any of the exceptions with stacktrace. And it would be really good to see some sample of the code, or some instructions how to reproduce it to determine the root of the problem.

**Comment by papusa** [comment] 2017-05-22 07:11
I mean refresh of browser tab. Exception is related to the fact that data being in transaction is getting lost together with a transaction when you press F5 for example. 

It's easy to reproduce: just create common transaction for multiple pages and you will see that transaction on refresh will be lost.

**Comment by chrhol** [comment] 2017-05-22 07:26
> I mean refresh of browser tab

When refreshing the browser tab, the browser looses the information about the location of the resource/session on the server, so this is more an issue for the client. Unfortunately I know too little of this part to give you an answer.

@mmnosek, I'm not sure who the best person is to help with this question about retaining sessioninformation on browser refresh. Maybe you can point someone out?

**Comment by mmnosek** [comment] 2017-05-22 08:25
@warpech could you take a look?

**Comment by warpech** [comment] 2017-05-23 13:18
Long-running transactions are bound to sessions. Each browser tab is a separate session. Reloading the browser tab is equivalent to launching a new browser tab at the same url.

@chrhol, I am afraid that this is a Typed JSON question actually. I assume it would be possible to create an explicit long-running transaction and keep a reference to it in a dictionary: https://docs.starcounter.io/guides/transactions/long-running-transactions/

@papusa can you pls explain the purpose? Maybe it is good to commit work-in-progress to the database more often, if it's a business requirement to retain the state of work in progress?

**Comment by papusa** [comment] 2017-05-23 13:33
@warpech
We have a booking process in our app which is consisting of multiple pages. On each page user is entering some data and goes to next page. Once he is on the last page and press confirm button transaction got committed. 
Committing on each page will save partially done bookings. If user leaves in the middle of booking process then we will have rubbish data.

**Comment by warpech** [comment] 2017-05-24 07:00
Partially done booking is also legit information. You just need to mark it appropriately in your data model, so it does not appear as "rubbish" among finished bookings. Maybe have a scheduled job to cleanup abandoned bookings.

@chrhol, @miyconst - any better ideas?

**Comment by chrhol** [comment] 2017-05-24 07:18
> @chrhol, @miyconst - any better ideas?

I agree, this sounds like a good approach considering how the current starcounter version works. This also have the benefit that it's possible of doing the actual confirmation in a short `Db.Transact` that has a higher transaction isolation level and will detect conflicts (which the long-running transaction does not, it simply saves the data) so it can actually be guaranteed that the booking is correct. 

Restoring/reusing session (and including in that, long-running transactions) serverside after browser tab refresh is not a pattern that we have looked into, and might have some additional side-effects to consider. It might be possible to do but most likely requires additional enhancements in Starcounter to work properly.

**Comment by warpech** [comment] 2017-05-24 07:39
> Restoring/reusing session (and including in that, long-running transactions) serverside after browser tab refresh is not a pattern that we have looked into, and might have some additional side-effects to consider. It might be possible to do but most likely requires additional enhancements in Starcounter to work properly.

I don't even think it is possible without having the session id in the URL, which I think is an anti-pattern.

**Comment by papusa** [comment] 2017-05-24 07:48
@warpech 
Thanks, I was thinking about that approach. But it looks more like a workaround than a nice solution. It will make our code more complex. 

1) We have to add additional properties (that's OK)
2) Background job for cleaning "rubbish" bookings
3) We will have to implement more code to keep our business logic. For example, such scenario:
User has saved a booking. Due to requirements there is a possibility to modify existing bookings. Than user started to modify previously stored booking. Changed some data let's say on first page. After that changed his mind and closed a browser. 
I'm pretty sure during development there will appear more cases like that.

Anyway as I understood there are no other option in Starcounter :(

**Comment by papusa** [comment] 2017-05-24 07:49
@warpech 
It could be token saved in cookies. 
Or it can be passed through using HTTP headers

**Comment by warpech** [comment] 2017-05-24 07:59
> It could be token saved in cookies.

Not really, because you have as many Starcounter sessions as you have the browser tabs opened. A cookie is shared between all tabs.

> Or it can be passed through using HTTP headers

Yes, but not in a regular lifecycle of a web page, because you cannot control the HTTP request header of the main HTML request. Perhaps [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) can help there, but that's very complex and perhaps undesired.

----

You can keep the booking draft in a non-database POCO and copy to a database class when the booking is finalized.

To identify the booking draft of a specific user, you will need a `Dictionary<SystemUser, BookingDraft>`.

**Comment by papusa** [comment] 2017-05-24 08:11
@warpech 

> You can keep the booking draft in a non-database POCO and copy to a database class when the booking is finalized.

Sorry, didn't get you. How this will solve my initial problem with pending data loss on tab refresh?

**Comment by warpech** [comment] 2017-05-24 08:54
If you are using an app like SignIn, is sets a cookie that identifies a user. Each browser tab is a separate session and a separate long running transaction. But you can still identify the user based on the cookie that comes in each request.

In case of SignIn, only an authenticated system user is referable using a `SystemUser` instance obtained from [`SystemUser.GetCurrentSystemUser()`](https://github.com/StarcounterApps/Simplified/blob/99888d7106a4782a45307d1cf53476d20648a556/Ring3/User/SystemUser.Static.cs#L36).

**Comment by warpech** [comment] 2017-06-05 08:11
Closing as answered

**Closed by warpech** 2017-06-05 08:11 UTC
Labels: Question, Transactions
