### ISSUE TITLE
Session IDs exhausted

### ISSUE THREAD

**Issue by mtornwall** [Starcounter/Home#471] opened 2020-05-27 11:20 UTC
Starcounter version: `2.3.1.8367`. It probably affects all 2.x versions.

### Issue type

- [x] Bug
- [ ] Feature request
- [ ] Suggestion
- [ ] Question
- [ ] Cannot reproduce
- [ ] Urgent

### Issue description

Starcounter has a limited number of session ID's. If memory serves, it allocates 100,000 ID's per scheduler on startup. You would expect that these ID's are released when calling `Session.Destroy()`, but alas they are not. This means that after a while, all available ID's will have been exhausted and the code host must be restarted before new sessions can be initiated.

### Reproduction code snippet

```cs
Handle.GET("/boom", () =>
{
    for (int i = 0; ; i++)
    {
        var s = new Session();
        if (i % 100 == 0)
        {
            System.Diagnostics.Trace.TraceInformation("Session {0}", i);
        }
        s.Destroy();
    }
});
```

### Exception stack trace

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: No free session indexes left.
   at Starcounter.Internal.SchedulerSessions.CreateNewSession(ScSessionStruct& ss, IAppsSession apps_session_int) in C:\TeamCity\BuildAgent\work\sc-15106\Level1\src\Starcounter.Internal\Sessions\InternalSessions.cs:line 537
   at Starcounter.Session..ctor(SessionOptions options, Nullable`1 includeNamespaces) in C:\TeamCity\BuildAgent\work\sc-15106\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 115
   at Starcounter.Session..ctor() in C:\TeamCity\BuildAgent\work\sc-15106\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 95
   at StarcounterApplication1.Program.<>c.<Main>b__0_0() in C:\Users\Martin\source\repos\StarcounterApplication1\Program.cs:line 14
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-15106\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-15106\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-15106\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
ParamName=No free session indexes left.
HResult=-2146233086
```

**Comment by per-samuelsson** [comment] 2020-05-27 13:20
Text-book sample of an issue report, @mtornwall. 👍🙂 

Seriously, that's not good at all. Let us think it through some and get back to you.

**Comment by per-samuelsson** [comment] 2020-05-28 15:32
Have an environment now where I can reproduce this. Spending time on understanding this session management better; it seem a bit complex.

What is clear is at least that the intention of the server is to return those internal session handles to the pool by means of background tasks, running periodically. Runs every minute normally, and checks for sessions that have fell out of scope.

However, it also looks like it will miss every session that has been explicitly destroyed like in the sample. And that is likely not by design, because of the fact that we have this leakage. As the criteria in how it picks what session to release is not straightforward, I'll need some more time to understand better where exactly the glitch are at, and what can be done about it.

**Comment by per-samuelsson** [comment] 2020-05-29 12:11
@mtornwall 

This is taking some time, but I'm doing slow progress learning and considering alternatives.

One thing I have been able to prove for sure now is that the background releasing of sessions indexes, making them reusable from the scheduler pool, is not activated for sessions that have been explicitly destroyed (i.e. `Session.Destroy()` or `Session.Dispose()`). I can also see why it's so, but still don't know how to best fix it (not risking breaking something else).

The host default is to run session cleanup every minute and to release sessions that have been inactive for 20 minutes. But as said, will miss sessions explicitly destroyed.

Out of curiosity - how did this surface for you? I'm guessing you don't create more sessions than 100.000 / 20 min interval normally. Do you explicitly destroy/dispose sessions? (Could be that some of our code does too, just trying to understand the use case here).

**Comment by mtornwall** [comment] 2020-05-29 13:26
> Out of curiosity - how did this surface for you? I'm guessing you don't create more sessions than 100.000 / 20 min interval normally. Do you explicitly destroy/dispose sessions? (Could be that some of our code does too, just trying to understand the use case here).

Something like this:

```
Handle.GET("/frequently-called-rest-endpoint", (Request request) => {
    Session.Current = Session.Ensure();
    try {
        Session.Current.Store["User"] = Login(request);
        return DoSomethingRequiringUserInSession(request);
    } finally {
        Session.Current.Destroy();
    }
});
```
Now call this once a second for about a week. :smile:

**Comment by per-samuelsson** [comment] 2020-05-29 13:35
> Now call this once a second for about a week. 😄

😆🤓

OK, thanks. Make sense obviously. And that answered the question about explicit disposal call too. 

I hope we can have some fix for this bug in not to long. Sorry it's taking time. I'll keep you posted.

**Comment by mtornwall** [comment] 2020-05-29 13:51
> I hope we can have some fix for this bug in not to long. Sorry it's taking time. I'll keep you posted.

We were able to work around it for now so it's not urgently holding us back.

**Comment by per-samuelsson** [comment] 2020-06-05 07:56
@mtornwall 

Short update:

We've come up with a fix, and also a general improvement in session re-usage and it's tested and merged to our 2.x branches.

We'll build and publish a new version after we've decided if there's some other fix we want to bring into it too. But expect a new version within like a week, or ping if you want us to just do it right away, and we can do that.

**Comment by mtornwall** [comment] 2020-06-05 08:07
Nice work! No rush on our account.

**Comment by per-samuelsson** [comment] 2020-06-12 12:16
We now have a new build - 2.3.1.8659 -- with the improvements we mentioned above. Grab it from here:

https://downloads.starcounter.com/download/Starcounter/LTS/latest

I'll close this issue as being fixed, but of course just ping us if you find something don't work, and we'll reopen it.

**Closed as completed by per-samuelsson** 2020-06-12 12:16 UTC
Labels: bug

**Comment by mtornwall** [comment] 2020-06-15 06:45
Thanks Per!
