### ISSUE TITLE
Inconsistent syntax for the helpunofficial option in star CLI

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Home#216] opened 2017-08-29 08:51 UTC
All other options in the `star` CLI start with a two dash prefix and some have a short hand notation with one dash prefix. Both the long and short version of `helpunofficial` are prefixed with one dash: 

```
Options:
  -h, --help            Shows help about star.exe.
  -hx, --helpextended   Shows extended help about star.exe.
  -v, --version         Prints the version of Starcounter.
  -i, --info            Prints information about the Starcounter installation.
  -p=,--serverport=port Port to the admin server.
  -hxx, -helpunofficial Shows unofficial help about star.exe.
```
(shortened snippet)

Also, do we really need three help commands? The `star` CLI is not that big.

This is super low priority, if we're sticking with the `star` CLI long-term, it should still be fixed eventually, possibly at the same time as some other fix.

CC @ubbeK

**Comment by ubbeK** [comment] 2017-08-29 09:36
Thanks for this feedback. It will be taken into consideration when all of our CLI tools are evaluated.

**Comment by miyconst** [comment] 2019-12-06 11:11
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:11 UTC
Labels: enhancement, nice to have, tools, won’t fix
