### ISSUE TITLE
SQL comparison failed

### ISSUE THREAD

**Issue by un-tone** [Starcounter/Home#437] opened 2018-08-28 18:48 UTC
Investigation of https://github.com/Starcounter/Starcounter.Linq/issues/55 revealed a bug with the following case:

```cs
[Database]
public class Product
{
    public string Name { get; set; }
    public string Description { get; set; }
    public bool IsProductGroup { get; set; }
    public Product ProductGroup { get; set; }
}

...

Db.Transact(() =>
{
    var test1 = new Product
    {
        Name = "test1",
        IsProductGroup = true
    };
    _ = new Product
    {
        Name = "test2",
        ProductGroup = test1
    };
    _ = new Product
    {
        Name = "test3"
    };
});

...

// returns "failed: ", the query should return the "test3" product
Handle.GET("/test1", () =>
{
    var group = Db.SQL<Product>("SELECT P FROM Product P WHERE P.Name = ?", "test1").First();
    var products = Db.SQL<Product>("SELECT P FROM Product P WHERE P.ProductGroup <> ? AND P <> ?", group, group).ToList();
    
    if (products.Count == 1 && products[0].Name == "test3")
    {
        return "ok";
    }
    return $"failed: {string.Join(", ", products.Select(x => x.Name))}";
});

// returns "failed: ", the query should return the "test1" and "test3" product
Handle.GET("/test2", () =>
{
    var group = Db.SQL<Product>("SELECT P FROM Product P WHERE P.Name = ?", "test1").First();
    var products = Db.SQL<Product>("SELECT P FROM Product P WHERE P.ProductGroup <> ? AND P <> ?", group, group).ToList();
    
    if (products.Count == 2 && products.All(x => x.Name != "test2"))
    {
        return "ok";
    }
    return $"failed: {string.Join(", ", products.Select(x => x.Name))}";
});

// returns "failed: test2", the query should return the "test1" and "test2" product
Handle.GET("/test3", () =>
{
    var group = Db.SQL<Product>("SELECT P FROM Product P WHERE P.Name = ?", "test1").First();
    var products = Db.SQL<Product>("SELECT P FROM Product P WHERE P.ProductGroup <> ? AND P <> ?", group, group).ToList();
    
    if (products.Count == 2 && products.All(x => x.Name != "test3"))
    {
        return "ok";
    }
    return $"failed: {string.Join(", ", products.Select(x => x.Name))}";
});
```

The query plan looks well:

```
{Tables(
	0 = ObjCmpIssue.Product
)
Projection(
	0 = 
		ObjectThis(0)
)
FullTableScan(
	MotherOfAllLayouts_SetspecIndex ON ObjCmpIssue.Product
	0
	LogicalOperation(
		AND
		ComparisonObject(
			NotEqual
			ObjectProperty(0, ProductGroup)
			ObjectVariable(1)
		)
		ComparisonObject(
			NotEqual
			ObjectThis(0)
			ObjectVariable(1)
		)
	)
	Ascending
)
}
```

Queries with literals works with the same bug:

```sql
select * from ObjCmpIssue.Product P where P.ProductGroup.ObjectNo <> 1 AND P.ObjectNo <> 1
select * from ObjCmpIssue.Product P where P.ProductGroup.Name <> 'test1' AND P.Name <> 'test1'
```

**Comment by PatrykSzwer** [comment] 2018-08-29 08:28
@miyconst, @bigwad you probably should know about this. Fix on this issue is needed for Omni project and has to be fixed ASAP. Please put high priority on that.

**Comment by un-tone** [comment] 2018-08-29 13:49
After the investigation I see that the following query works well:

```cs
Db.SQL<Product>("SELECT P FROM Product P WHERE (P.ProductGroup IS NULL OR P.ProductGroup <> ?) AND P <> ?", group, group);
```

Due to the https://github.com/Starcounter/Home/issues/343 issue we should not touch this behaviour.

@miyconst @bigwad agree?

Also should the behaviour also works for LINQ (https://github.com/Starcounter/Starcounter.Linq/issues/55#issuecomment-416955442)?
Or SC.Linq should add `P.ProductGroup IS NULL OR ` part for such paths comparisons?

**Comment by bigwad** [comment] 2018-08-29 14:09
I don't really see how it relates to #343. Where is a path expression here?

**Comment by miyconst** [comment] 2018-08-30 09:29
@un-tone, @bigwad, @PatrykSzwer please correct me if I am wrong, but this is the case of `NULL` comparison.

How SQL works is that both of those comparisons will return `false` if the `X.Value` is `NULL`.

- `SELECT * FROM x WHERE x.Value = 123456`.
- `SELECT * FROM x WHERE x.Value <> 123456`.

Since C# and LINQ work differently with `NULL` comparison, it may be non-intuitive to add manual `... OR x.Value IS NULL` part to the `Where` clause, but it's important to understand the difference between [`IEnumerable` vs `IQueryable`](https://stackoverflow.com/questions/2876616/returning-ienumerablet-vs-iqueryablet).

In fact, LINQ provider in Entity Framework works the same way, comparing a `NULL` value in the database with any value produces `false`, but comparing to C# `null` is automatically converted to `IS (NOT) NULL`.

There was a bug in the early versions of LINQ provider in Entity Framework, which caused `NULL` comparison in SQL when a passed parameter had `null` value.

Example:

```cs
string name = null;

// SELECT p FROM People WHERE Name = NULL;
// Returns no records. Comparison with `NULL` is always `false`.
var people = db.People.Where(x => x.Name == name);

// SELECT p FROM People WHERE Name IS NULL;
// Returns all records where Name column is null.
var people = db.People.Where(x => x.Name == null);
```

**Comment by bigwad** [comment] 2018-08-30 13:20
>How SQL works is that both of those comparisons will return false if the X.Value is NULL.

`NULL` to be exact

>difference between IEnumerable vs IQueryable.

Actually, the difference is that you don't know where would be that difference exactly, because IQueryable can run a query on a datasource side and thus result depends on the datasource rules of handling NULLs.
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/bb882669(v=vs.100)
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/null-comparisons

Seems, Starcounter behavior here is aligned with what one can expect from LINQ to SQL running against an abstract ANSI SQL database.

**Comment by miyconst** [comment] 2018-08-30 14:15
>Actually, the difference is that you don't know where would be that difference exactly ... 

That's not exactly true, `IQueryable` is always executed on the database as an SQL query, while `IEnumerable` is always executed in .Net runtime. So, it's well known which part of the query is gonna be executed on database side and which not.

>Seems, Starcounter behavior here is aligned with what one can expect from LINQ to SQL running against an abstract ANSI SQL database.

So, after all this is not a `bug`, but expected behavior. Shall we agree to close the issue as `invalid`?

**Comment by un-tone** [comment] 2018-08-30 16:17
Sorry for confusing @bigwad , I meant the folowing cases when told about #343:
```sql
select * from ObjCmpIssue.Product P where P.ProductGroup.ObjectNo <> 1 AND P.ObjectNo <> 1
select * from ObjCmpIssue.Product P where P.ProductGroup.Name <> 'test1' AND P.Name <> 'test1'
```
The same workaround with adding `IS NULL OR` works for all the cases from the description.

> Shall we agree to close the issue as invalid?

Seems so. And this one https://github.com/Starcounter/Starcounter.Linq/issues/55 too.

**Comment by miyconst** [comment] 2018-08-31 11:05
Closing as invalid.

**Closed by miyconst** 2018-08-31 11:05 UTC
Labels: invalid, qp, qp-old
