### ISSUE TITLE
Webmethod Exception inside Db.Transact breaks the code host

### ISSUE THREAD

**Issue by habib535** [Starcounter/Home#417] opened 2018-05-22 07:56 UTC
In the following sample, we have a rest call that breaks the starcounter host process and we have to restart the server. As a temporary solution we have wrapped the rest call inside `try ` `catch`. Nothing is logged in the server logs.

```cs
public class Program
    {
        static void Main()
        {
            Handle.GET("/RestMethod", () =>
            {
                return 503;
            });

            //works as expected, we get the exception but nothing breaks.
            Handle.GET("/ManualException", () =>
            {
                Db.Transact(() =>
                {
                    throw new Exception();
                });
                return 200;
            });

            //breaks the code host
            Handle.GET("/RestException", () =>
            {
                Db.Transact(() =>
                {
                    using (var client = new WebClient())
                    {
                        //following line should be wrapped inside try catch
                        var response = client.DownloadString("http://localhost:8080/RestMethod");
                    }
                });
                return 200;
            });
        }
    }
```

**Comment by miyconst** [comment] 2018-05-22 09:30
@habib535 thank you for reporting, here are a few things:

1. Making a REST call inside a transaction is not a good idea. The transaction can be re-tried in case of a conflict, and the REST call will be executed multiple times. 
2. Are there crash dumps available?
3. From the URL `http://localhost:8080/RestMethod`, I can guess, that the REST call is made to Starcounter served app. Could it be that this app crashes the host?

**Comment by habib535** [comment] 2018-05-22 09:41
> Making a REST call inside a transaction is not a good idea. The transaction can be re-tried in case of a conflict, and the REST call will be executed multiple times.

Good point, we are going to refactor the code but what was painful is that the server went down.

> Are there crash dumps available?

Where to find?

> From the URL http://localhost:8080/RestMethod, I can guess, that the REST call is made to Starcounter served app. Could it be that this app crashes the host?

REST call is a 3rd-party api (fortnox).

**Comment by miyconst** [comment] 2018-05-22 10:03
[Collecting User-Mode Dumps](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx).

**Comment by miyconst** [comment] 2018-05-22 10:03
>Good point, we are going to refactor the code but what was painful is that the server went down.

Can you please reproduce the issue with a minimal example?

**Comment by habib535** [comment] 2018-05-22 10:16
In the above sample code, the code host will crash on executing `/RestException` endpoint. You want sample code with Fortnox api?

**Comment by bigwad** [comment] 2018-05-22 10:37
It was discussed in https://github.com/Starcounter/Home/issues/51
As we don't have exception filters or any sort of exception handling middleware, the only thing we can do is left an exception unhandled thus crashing a hosting process.

**Comment by bigwad** [comment] 2018-05-22 10:55
Can't reproduce given the code above. @habib535, ss there a crash dump of sccode process?

**Comment by mtornwall** [comment] 2018-05-22 11:05
@bigwad I think this is a different problem. A breakpoint is hit due to heap corruption in `sccoredb!free_transaction()`.

**Comment by bigwad** [comment] 2018-05-22 11:07
> I think this is a different problem. 

I agree. I missed the fact that host crashes only when inside Db.Transact. Now, I'm waiting for a dump or additional repro details as I can't reproduce it locally.

**Comment by habib535** [comment] 2018-05-22 11:34
`Version=2.4.990.86`

![restexception](https://user-images.githubusercontent.com/2991381/40359968-c1266920-5dc4-11e8-8441-2029fc2168e2.gif)

**Comment by miyconst** [comment] 2018-05-22 12:47
@habib535 please collect the crash dumps.

**Comment by miyconst** [comment] 2018-05-22 14:03
I just have reproduced the error, and it does not generate the crash dumps.

```
"System.Exception: Exception of type 'System.Exception' was thrown.
   at Program.<Main>b__2() in c:\Temp\HomeIssue417.cs:line 19
   at Starcounter.Db.TransactAsyncInternal(Action action, UInt32 flags, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-18255\Level1\src\Starcounter\Db.cs:line 295
   at Starcounter.Db.Transact(Action action, TransactOptions opts) in C:\TeamCity\BuildAgent\work\sc-18255\Level1\src\Starcounter\Db.cs:line 515
   at Program.<Main>b__1() in c:\Temp\HomeIssue417.cs:line 17
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-18255\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 202
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-18255\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 95
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-18255\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 356
HResult=-2146233088
"
```

```cs
using System;
using System.Net;
using Starcounter;

public class Program
{
    static void Main()
    {
        Handle.GET("/RestMethod", () =>
        {
            return 503;
        });

        //works as expected, we get the exception but nothing breaks.
        Handle.GET("/ManualException", () =>
        {
            Db.Transact(() =>
            {
                throw new Exception();
            });
            return 200;
        });

        //breaks the code host
        Handle.GET("/RestException", () =>
        {
            Db.Transact(() =>
            {
                using (var client = new WebClient())
                {
                    //following line should be wrapped inside try catch
                    var response = client.DownloadString("http://localhost:8080/RestMethod");
                }
            });
            return 200;
        });
    }
}
```

Step to reproduce:

1. Install `Starcounter-Develop-2.4.0.6159 (May 22, 2018 12:59:55 AM)`.
2. Create a new empty database.
3. Create a file with the content of the application above.
4. Start the file with `star FileName.cs`.
5. Navigate to `http://localhost:8080/ManualException` and make sure that an exception is shown.
6. Do the step 5 again and make sure that the app is still running.
7. Navigate to `http://localhost:8080/RestException`. **The code host crashes.**

**Comment by bigwad** [comment] 2018-05-22 14:40
I also managed to reproduce it. Strange, but it crashes only in the release build. That's why I failed before.

**Comment by bigwad** [comment] 2018-05-22 16:55
Found the culprit - it's this commit by @Mackiovello: https://github.com/Starcounter/level1/commit/7fcc96780306297a66715a0cb4baed96580c84a6

In this change interop calls to kernel were extracted into separate package. But the problem is that original kernel calls did more than just calling the kernel, in particular they did this: 
```csharp
            ThreadData.CheckAndAttachKernelContext(verify);
```

Tomorrow I'll look through all calls and make appropriate changes.

**Comment by miyconst** [comment] 2018-05-22 20:50
>Tomorrow I'll look through all calls and make appropriate changes.

Should there be a test for this case as well? Can @Mackiovello implement such?

**Comment by bigwad** [comment] 2018-05-23 10:06
Fixed.

>Should there be a test for this case as well?

We can't directly test what we actually need to test - that certain kernel functions are called when the current thread is attached to a scheduler. To test that properly we have to tie interop functions with level1 scheduling or introduce some DI points to interops, which I guess we don't want to do. Then the easiest test would be indirect - to see if something goes wrong (like a crash) in certain circumstances. The easiest test would look like this:

```csharp
        static void Main(string[] args)
        {
            try
            {
                Db.Transact(() =>
                {
                    //ensure thread is detached
                    new System.Threading.AutoResetEvent(true).WaitOne();

                    throw new System.Exception();
                });
            }
            catch (Exception)
            { }
            Environment.Exit(0);
}
```

We can write such test, but as you see I couldn't even reproduce it in debug build, so the test would be not that indicative - it might have a lot of false negatives (a test says it's alright, but actually it isn't).

PS. 
I'm closing the issue, but will work on this a little more to figure out why crash dump wasn't generated

**Closed by bigwad** 2018-05-23 10:06 UTC
Labels: investigate, question
