### ISSUE TITLE
Error on Creating a new project.

### ISSUE THREAD

**Issue by SenerDemiral** [Starcounter/Home#399] opened 2018-04-04 07:28 UTC
When the new Project created below error occurred.

Affected SC v:2.4.0.5630 & 2.4.0.5675 (Previous version Uninstalled) 
Working  SC v:2.4.0.5604

Visual Studio Community 2017 v:15.6.4
VS Extension: Starcounter for Visual Studio v:3.0.0

Create Project parameters:
Starcounter 2.4 Application
Framework .NET framework 4.6.1

Error message:
The project file
'C:\Users\Sener\AppData\Local\Temp\coux011e.dvx\Temp\SA3.csproj' 
cannot be opened.

There is a missing project subtype.
Subtype: '{C86118D7-451E-4933-BFEE-A1EFDB162FD7}' is unsupported by this installation.

**Comment by miyconst** [comment] 2018-04-04 08:01
@SenerDemiral thank you for reporting, the issue will be solved soon.

**Comment by miyconst** [comment] 2018-04-04 08:02
Extra info, Visual Studio shows the following errors during the project creation:

![image](https://user-images.githubusercontent.com/6435556/38295303-d944d264-37ed-11e8-9d53-f444dd231f07.png)

![image](https://user-images.githubusercontent.com/6435556/38295314-e2799f36-37ed-11e8-90de-71f7b67b1852.png)

**Comment by iqbalskd** [comment] 2018-04-04 12:24
This is  `2.4`  only issue,  `2.3`  seems working fine. This issue started in `v2.4.0.5630` on 31st March, @Mackiovello looks like you made some changes on 28th March, can you please have a look if that change caused this.

**Comment by Mackiovello** [comment] 2018-04-04 13:56
A fix is found and will be included for the next nightly

**Comment by Mackiovello** [comment] 2018-04-04 14:29
Changes are merged, closing this as done. 

Thank you again for reporting @SenerDemiral!

**Closed by Mackiovello** 2018-04-04 14:29 UTC
Labels: investigate, tools, tools-vs

**Comment by hamzim** [comment] 2018-09-05 20:14
Hi, I got the same problem as @SenerDemiral , 
![image](https://user-images.githubusercontent.com/11314574/45118498-f4607280-b158-11e8-875a-3270f42f7c63.png)

I am using SC v. 2.4.0.6717, how did you solve this?

**Comment by miyconst** [comment] 2018-09-06 04:44
@hamzim, unfortunately I was not able to reproduce the error with the versions specified, could you please try the following:

- Execute `staradmin start server` from the command line.
- Navigate to `http://localhost:8181/#/server/settings` and copy-paste the full Starcounter version.
- Open Visual Studio then go to `Tools -> Extensions and Updates ...` and copy-paste a screenshot of the window so the Starcounter extension is visible.

**Comment by hamzim** [comment] 2018-09-06 07:35
@miyconst  


Starcounter-Develop-2.4.0.6717 (Sep 5, 2018 1:03:55 AM)

![image](https://user-images.githubusercontent.com/11314574/45142191-2ead2c80-b1b8-11e8-9135-b10499878daf.png)

**Comment by SenerDemiral** [comment] 2018-09-06 07:45
I also was not able to reproduce the error with the version 2.4.0.6721 (.Net 4.7.2)

**Comment by hamzim** [comment] 2018-09-06 07:59
I have tried different versions of 2.4.* versions (initially I used v. 2.3.*, switched to 2.4.*) but nothing works for me (.Net 4.6.1).

**Comment by miyconst** [comment] 2018-09-06 09:37
>It seems like the environment variable for StarcounterBin was set on the administrator user.

It seems like Starcounter was installed with Administrator account, while you are trying to use the same installation under another user. Unfortunately this is not supported.

Please try to uninstall Starcounter and install it with the user you intend to use it.

**Comment by miyconst** [comment] 2018-09-06 10:31
@hamzim, we will address the issue with multiple system users. You can track the progress here - [Starcounter installation is corrupted when used from another system user](https://github.com/Starcounter/Home/issues/441).
