### ISSUE TITLE
Weaver crashes for absolute path in weaver.ignore

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#179] opened 2017-07-11 12:57 UTC
Probably because of spaces.

1. Create weaver.ignore with absolute path, like `C:\Program Files\Starcounter\LibrariesWithDatabaseClasses\Starcounter.Extensions.dll`
1. run scweaver
1. Exception:
 ```
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.IO.TextWriter.WriteLine(String format, Object[] arg)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)
   at Starcounter.Weaver.WeaverHost.WriteWithColor(TextWriter stream, ConsoleColor color, String message, Object[] parameters) in C:\TeamCity\BuildAgent\work\sc-5899\Level1\src\scweaver\WeaverHost.cs:line 118
   at Starcounter.Weaver.WeaverHost.WriteError(UInt32 errorCode, String message, Object[] parameters) in C:\TeamCity\BuildAgent\work\sc-5899\Level1\src\scweaver\WeaverHost.cs:line 50
   at Starcounter.Weaver.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-5899\Level1\src\scweaver\Program.cs:line 59```

**Comment by bigwad** [comment] 2017-07-11 13:25
I played with a weaver a little bit, so I'll answer this.

The problem is that the weaver tries to create a regexp out of weaver.ignore items, but don't convert backslashes to fulfill regex format. So the problem is with unescaped backslashes. This one would pass:
`C:\\Program Files\\Starcounter\\LibrariesWithDatabaseClasses\\Starcounter.Extensions.dll`

But it serves no purpose, as the weaver matches filename only while doing its analysis.

**Comment by per-samuelsson** [comment] 2017-08-09 09:49
Overall, `weaver.ignore` and the processing of it's content is pretty naive. Like @bigwad says, we simply try to create regular expression from each line and if that does not work, then... well, things tend to be undefined. 😢 

It's not straightforward to address though. Both how to validate content, and how to report a meaningful error to the user. Especially validation seem fuzzy.

So, should we try to address this, or close it as a known flaw? Any ideas how we can improve, i.e. what validations can we do with arbitrary strings being read from the file?

**Comment by joozek78** [comment] 2017-08-14 09:12
I think we could improve the parsing a bit - directly disallow everything from `Path.GetInvalidFileNameChars()` and provide a nice error message. If that's unfeasible for some reason, please go ahead and close this issue, it turns out I don't need to exclude Starcounter Extensions - it was a false lead and probably no one needs it.

**Comment by per-samuelsson** [comment] 2017-08-14 09:21
> I think we could improve the parsing a bit - directly disallow everything from `Path.GetInvalidFileNameChars()`

Yeah, that is what I considered too, but then are we sure some of those chars are not legal to create a regex from? And also, it still won't guard us against all problems, just improve a little bit I think.

**Comment by joozek78** [comment] 2017-08-14 09:31
> Yeah, that is what I considered too, but then are we sure some of those chars are not legal to create a regex from? And also, it still won't guard us against all problems, just improve a little bit I think.

You're right in both your points - it needs a little bit more than `Path.GetInvalidFileNameChars()` and it won't be the absolute final solution, but I think this little improvement could solve a lot of small frustration.

Again, if you feel you can't implement this in a foreseeable future (lack of time, etc.) please close this - IMO it's better to know that nobody will fix this than have a false hope ;)

**Comment by per-samuelsson** [comment] 2017-08-14 11:20
> Again, if you feel you can't implement this in a foreseeable future (lack of time, etc.)

I don't consider lack of time the biggest problem, but rather reaching a conclusion on exactly how we want this thing implementing, trying to find side effects for even the simplest suggestion above. If I knew a very consistent and good way to improve, I would do it for sure.

**Comment by miyconst** [comment] 2019-12-06 11:10
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:10 UTC
Labels: bug, nice to have, weaver, won’t fix
