### ISSUE TITLE
sccode crash during DROP COLUMN

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#425] opened 2018-06-19 13:25 UTC
We are seeing `sccode` crashes on a production server when running the following SQL:

```
ALTER TABLE FacebookManager.Database.FacebookNode DROP COLUMN Archived
```

Table definition:

```
public abstract class FacebookNode
{
    public String DspId { get; }
    public String FacebookId { get; internal set; }
    public AdAccount AdAccount { get; }
    public String Name => $"{GetType().Name}-{DspId}";
    public DateTime CreatedTime { get; }
    public DateTime DeletedTime { get; set; }
    public bool CreatedAtFacebook { get; set; }
    public bool Archived { get; set; }
    public bool Deleted { get; set; }

    protected FacebookNode(AdAccount account, String dspId)
    {
        DspId = dspId;
        AdAccount = account;
        CreatedTime = DateTime.UtcNow;
        Archived = false;
        Deleted = false;
    }
}
```

Crash dump available at https://www.dropbox.com/s/dp8zk1jchf56ivx/sccode.exe.2560.dmp?dl=0

SC version: `2.3.2.930`

**Comment by bigwad** [comment] 2018-06-19 15:38
cc @alexanderstc, @k-rus 
something wrong with metadata.

**Comment by k-rus** [comment] 2018-06-19 17:01
@alexanderstc can you look at it?

**Comment by alexanderstc** [comment] 2018-06-19 17:02
Yes, sure, can it wait till tomorrow?

**Comment by k-rus** [comment] 2018-06-19 17:03
> Yes, sure, can it wait till tomorrow?

Yes, of course. I assign it to you.

**Comment by alexanderstc** [comment] 2018-06-20 10:35
@erikvk if the problem is easily reproducible, could you try to change the name of the field "Name" to something else and see if it works.

**Comment by alexanderstc** [comment] 2018-06-20 10:38
@miyconst please find out
- the urgency of the problem
- can a reproduction be arranged for me to debug
- if easy, make a reproduction VM not larger than 40GB, 32GB may be enough.

**Comment by miyconst** [comment] 2018-06-20 10:39
@alexanderstc I am already working on it, waiting for @erikvk at the moment.

**Comment by alexanderstc** [comment] 2018-06-20 10:51
Ideally, a VirtualBox VM.

**Comment by miyconst** [comment] 2018-06-20 11:36
@erikvk is there anything else we could do for you now?

**Comment by erikvk** [comment] 2018-06-20 11:43
@miyconst This was never an urgent issue for us, since the production server did not contain crucial data. I posted the issue mainly for you guys, to investigate the reason for the `sccode` crash.

**Comment by erikvk** [comment] 2018-06-20 11:45
If something like this happens again in the future, we'll make sure to keep the db files for troubleshooting.

**Comment by alexanderstc** [comment] 2018-06-20 11:48
Based on the info from the crash dump i have an idea how i can make my own experiment, but that after my vacation or if this issue becomes urgent.

**Comment by alexanderstc** [comment] 2018-06-20 12:12
@miyconst VM isn't needed, just the DB. I can build the relevant sources locally.

**Comment by alexanderstc** [comment] 2018-06-20 12:13
@miyconst if you have time, you could try to create a table with one of the column named "Name", then delete it.

**Comment by miyconst** [comment] 2018-06-21 09:45
>@miyconst if you have time, you could try to create a table with one of the column named "Name", then delete it.

Just tried it, works flawlessly.

Since the database files are not available, and there is no way to reproduce the issue, I have no other choice but archive the issue.

@erikvk please save the database files and reopen the issue if the problem happens again.

**Closed by miyconst** 2018-06-21 09:45 UTC
Labels: db, db-schema, db-schema-migration, kernel

**Comment by erikvk** [comment] 2018-06-21 10:06
@miyconst Sure, will do
