### ISSUE TITLE
Add support for Binary datatype in Stardump and Core.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#241] opened 2017-09-18 10:01 UTC
We have had some discussion about what to do with `Binary` but now it's getting more urgent to get this included in at least Stardump.

This is very needed for Adtoma to be able to unload (and reload) data. They are currently not able to do a proper unload/reload.

/cc @miyconst, @jedynykaban

**Comment by miyconst** [comment] 2017-09-18 10:03
Duplicate of - [Implement support for byte[] data type](https://github.com/Starcounter/StarDump/issues/30).

Closing this issue, but will prioritize the original one.

**Closed by miyconst** 2017-09-18 10:03 UTC
Labels: duplicate
