### ISSUE TITLE
Exceptions thrown out of Scheduling.ScheduleTask should be logged instead of killing the app

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#301] opened 2017-11-06 11:00 UTC
This code will kill the codehost, it's documented [here](https://docs.starcounter.io/guides/transactions/running-background-jobs#scerrunhandledexception-(scerr1069))
```c#
Scheduling.ScheduleTask(() => throw new Exception());
``` 

It's very dangerous (you can kill other apps if you forget to catch your exceptions) and unintuitive (Input and HTTP handlers catch the exception for you and log it).
I propose change this behavior and log those exceptions just like those inside handlers.

CC @miyconst to make the decision

**Comment by miyconst** [comment] 2017-11-06 12:15
>I propose change this behavior and log those exceptions just like those inside handlers.

There is a problem. If an exception happens in the session thread, then Starcounter can crash the session and show an error message to user.

Now, what to do if an exception happens in a non-session thread? There is no guarantee that this exception is not lethal for entire application life-circle. That is why we can't simple "swallow" such exceptions.

Regarding the logging, I think the exception is already logged and visible under Starcounter Administrator panel. Is not it?

**Comment by Mackiovello** [comment] 2017-11-06 13:41
There was an extensive discussion about this here: https://github.com/Starcounter/home/issues/51

**Comment by joozek78** [comment] 2017-11-08 12:02
> There is a problem. If an exception happens in the session thread, then Starcounter can crash the session and show an error message to user.

Than at least that should be done.

> Now, what to do if an exception happens in a non-session thread? There is no guarantee that this exception is not lethal for entire application life-circle. That is why we can't simple "swallow" such exceptions.

IMO it's far worse that entire codehost goes down. If innocent apps weren't killed I could agree with you

> Regarding the logging, I think the exception is already logged and visible under Starcounter Administrator panel. Is not it?

**Comment by Mackiovello** [comment] 2017-11-17 16:04
The current implementation is painful, during development but also if you're running a production server with many apps. I agree with @eriksunsol from #51 :

> Everything else aside, I think it is totally unacceptable that the server goes down when there is an unhandled exception. Anywhere. Unless it is caused by some internal error in Starcounter from which it is impossible to recover. Excessive logging and performance degradation may be bad, but letting the server go down is worse.

We're struggling with usability, and this is one of the factors. 

Is this something that can be solved with the updated hosting model in 2.4 or 3.0?

**Comment by miyconst** [comment] 2017-11-17 17:16
@Mackiovello we should elaborate on what is "server goes down when there is an unhandled exception".

Server does not go down, it's code host crashes. Take a windows application and throw an exception from it. What happens? Entire application crashes. Exactly the same thing happens in the code host.

If an unhandled exception in the code host crashes `scdata` process or brings down entire server, then of course it's not acceptable, and it's not the case as of now.

**Comment by Mackiovello** [comment] 2017-11-17 18:13
> Server does not go down, it's code host crashes. Take a windows application and throw an exception from it. What happens? Entire application crashes. Exactly the same thing happens in the code host.

Exactly. The difference with Starcounter is that you often run 5, 10, 15 applications in one code host, and restarting those after the host is brought down by one app takes a lot of time.

If just the app with the exception crashes that would be better, although, as I understand it, that's impossible with the current hosting model. This pain would also be reduced if the startup time of apps was shorter.

**Comment by eriksunsol** [comment] 2017-11-17 22:47
I still don't see any reason why an unhandled exception should be allowed to crash the code host, even if there is just a single app running in it.

If application state is stored in the database, it is guaranteed to stay consistent if transactions are used properly. If session state is stored in a session and an exception crashes the session, we lose the session state, but the application is still in good shape. If application state is stored by some other means which is not protected by transactions and is not connected with the session, then it doesn't matter where an unhandled exception is thrown (session thread or not) because the state may be inconsistent either way.

So the only way to mess things up is if you don't use transactions to keep application state consistent (i.e. you don't store it in the database), or you're not using the transaction right. If this is the case, then your application is broken by design and needs to be fixed. And if you are storing state in the database but not using transactions right, crashing the code host doesn't help because when it is fired back up the state will still be inconsistent. 

I think the code host should be able to assume that:

1. Database transactions are used right.
2. Session state is stored with the session.
3. Application state as a whole is only stored in these two places.

Then there is no reason to crash the code host due to an unhandled exception in user code. Ever. Is there? What am I missing?

**Comment by miyconst** [comment] 2017-11-19 11:04
@eriksunsol let's have a chat about it offline.

**Comment by miyconst** [comment] 2017-11-21 14:10
Today I have a discussion with @eriksunsol, @alemoi, and we agreed that:

- Exception inside a **synchronous** task scheduled with either `Scheduling.ScheduleTask` or `Session.ScheduleTask` should not crash the code host, instead it should be propagated to the parent thread.
- Exceptions inside an **asynchronous** task scheduled with either `Scheduling.ScheduleTask` or `Session.ScheduleTask` should not crash the code host, instead it should just be logged to the Administrator Log.

The issue will be brought to the next release planning.

**Comment by miyconst** [comment] 2017-11-22 11:38
@joozek78, @Mackiovello, @eriksunsol it turns out that what you asked was already implemented and only required some polishing.

The features are available from `Starcounter-RC-2.3.1.7870 (Nov 22, 2017 10:53:34 AM)` version - [Document deprecation of `Scheduling.ScheduleTask` in favor of `Scheduling.RunTask`](https://github.com/Starcounter/Home/issues/320).

Documentation on [starcounter.io](https://starcounter.io/) will be updated shortly.

Thank you all for the contribution. Closing the issue as done.

**Closed by miyconst** 2017-11-22 11:38 UTC
Labels: errors, errors-reports, question
