### ISSUE TITLE
Method to send streams to client over websocket

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#350] opened 2018-01-11 13:36 UTC
@alemoi 
(I already talked to @alemoi about this. This issue is for future reference)

It would be great if I could post `Stream` data back to the client over a `WebSocket`

I was thinking something like this for the `WebSocket` class:

```c#
public void Send(byte[] data, bool isText = false, Response.ConnectionFlags connFlags = Response.ConnectionFlags.NoSpecialFlags);
public void Send(byte[] data, int dataLen, bool isText = false, Response.ConnectionFlags connFlags = Response.ConnectionFlags.NoSpecialFlags);
public void Send(string data, bool isText = true, Response.ConnectionFlags connFlags = Response.ConnectionFlags.NoSpecialFlags);
public void Send(Stream data, bool isText = false, Response.ConnectionFlags connFlags = Response.ConnectionFlags.NoSpecialFlags);
public void Send(Stream data, int dataLen, bool isText = false, Response.ConnectionFlags connFlags = Response.ConnectionFlags.NoSpecialFlags);
```

**Comment by alemoi** [comment] 2018-03-12 17:28
I have researched a bit and unfortunately such APIs does not exist in standard .NET APIs which we are trying to aim for. I have answered the question here: https://github.com/Starcounter/Home/issues/389

@miyconst what's your opinion on this?

**Comment by miyconst** [comment] 2018-03-13 08:57
Such method should not be included into Starcounter, but there might be a standalone NuGet package like `Starcounter.Networking` or something with helper functions.

Closing this issue as a duplicate of - [Sending large payloads over WebSocket](https://github.com/Starcounter/Home/issues/389).

**Closed by miyconst** 2018-03-13 08:57 UTC
Labels: enhancement, nice to have
