### ISSUE TITLE
Staradmin stop db stops wrong database

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#109] opened 2017-05-11 14:40 UTC
1. `staradmin stop db palma` stops `default` database, instead of palma
1. the same mistake is made with `staradmin delete db`
1. reproduced on version 2.3.1.6405
![image](https://cloud.githubusercontent.com/assets/6013217/25954995/3cc121ae-3668-11e7-86db-e02a5db905f3.png)

**Comment by miyconst** [comment] 2017-05-11 14:41
@joozek78 this is how the command line currently works.

You have to use:

```
staradmin -d=palma stop db
staradmin -d=palma delete db
```

**Comment by k-rus** [comment] 2017-05-11 14:43
I also do this mistake all the time.

**Comment by joozek78** [comment] 2017-05-11 14:48
That's *very* confusing. CLI doesn't tell me I made a mistake, it happily stops the other database. Can't we make it accept database as last positional parameter? Or at least not execute if given additional parameter?

**Comment by k-rus** [comment] 2017-05-11 14:50
cc @per-samuelsson

**Comment by per-samuelsson** [comment] 2017-05-12 08:32
@joozek78 

Sorry for the confusion. It's kind of by design, but I agree it's not good. When we designed a common CLI experience for all our tools waaaaay back, we choose this certain way of doing things, and one design decision was made so that it should be possible to invoke `star` with just a single argument (the file) and still confirm to the expanded syntax.

As you could see, running `staradmin` help will give you this:

```
Usage: staradmin [options] <command> [<command options>] [<parameters>]

Options:
  --help                 Shows help about staradmin.exe
  --database=<name>      Specifies the database commands run against
  --serverhost=<host>    Specifies the admin server host
  --serverport=<port>    Specifies the admin server port

Commands:
  console    Shows console output from applications
  delete     Deletes various types of objects, e.g. databases.
  help       Shows help about a command
  kill       Kills processes relating to Starcounter
  list       List various types of objects, e.g. databases or applications.
  new        Creates various types of objects, e.g. databases or applications.
  reload     Reloads data into a data source, usually a database
  start      Starts various types of objects, e.g. databases or the server.
  stop       Stops various types of objects, e.g. databases or applications.
  unload     Unloads data from a data source, usually a database
```

Now, we have already kind of decided to improve this, also long ago: https://github.com/Starcounter/level1/issues/3000. And it's been reported earlier by @k-rus too: https://github.com/Starcounter/level1/issues/3489. I think it's time we finally address this, right here and now. I'll assign it to me and will start working out something ASAP. I just need to consider it some, to be sure not to break usage already out there.

**Comment by per-samuelsson** [comment] 2017-05-16 14:38
Done, pushed to both main branches, and announced in this https://github.com/Starcounter/level1/issues/3000#issuecomment-301795757.

**Closed by per-samuelsson** 2017-05-16 14:38 UTC
Labels: Command line
