### ISSUE TITLE
Schema mismatch error kills all apps

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Home#444] opened 2018-09-18 15:05 UTC
Starcounter version: `2.4.990.161`

I have multiple apps running. Then I try to deploy a  new version of one of those, and I got an error:

`Starcounter.DbException: ScErrSchemaCodeMismatch (SCERR4177): Operation failed because input does not match schema. CLR Class is not loaded for table Search.Product`

That's understandable, the schema was changed. But suddenly all apps died when I tried to run the app. 

Isn't it possible, that I get an error, but the rest of the system is still up and running?

**Comment by k-rus** [comment] 2018-09-19 06:57
I believe it is similar situation to unloading or stopping an app. Due to single process all apps need to stop. The same is here.

@per-samuelsson can give better explanation.

**Comment by per-samuelsson** [comment] 2018-09-19 07:52
> @per-samuelsson can give better explanation.

I'm not sure we properly deal with one application crashing and preserving the state of others in the same host. But let me set up an environment and do some testing before I give a better answer.

**Comment by per-samuelsson** [comment] 2018-09-19 09:00
After doing some testing, I can confirm this. It's easy to reproduce by creating 2 apps and having one of them throwing an exception from the entrypoint, starting that last.

We have some code in the admin server that reacts to a host terminating unexpectedly, and tries to restart it (along with a snapshot of apps if available), but only under certain conditions. 

Overall, it's somewhat hard to get 100% right, because you can't be sure it was for some reason the admin server can't detect (like for instance of the host was explicitly killed), and there could be other management commands queued in the server that should have precedence.

From spending just a short amount of time on it, I can't really tell exactly why the restart is not fulfilled in this particular case. If I should spend more time on it than this, I want it to be sanctioned by @miyconst.

**Comment by bigwad** [comment] 2018-09-19 09:10
I'd consider restarting apps as a last resort. It seems to me that it's possible to prepare metalayer in reflection context, thus avoiding loading app code and crashing a host if something went wrong. Might also apply to Nova shared host, where we don't have admin service to restart apps.

**Comment by per-samuelsson** [comment] 2018-09-19 09:38
> It seems to me that it's possible to prepare metalayer in reflection context, thus avoiding loading app code and crashing a host if something went wrong.

Could be worth a try, yeah. Initially, all binding was done from a schema established and provided by the weaver, and code was never used. But I think metalayer require loaded code. Might be that it would behave better if it was reflection-only, even though I'm not really sure that would solve it.

Plus that you still have the case where shared host need to invoke the entrypoint and out comes an exception. That need to be dealt with some other way, if we need to support other apps to stay resident.

**Comment by miyconst** [comment] 2018-09-19 11:34
@mmnosek how important this issue is? I believe it's just an inconvenience during the development/deployment time, does not affect production.

**Comment by mmnosek** [comment] 2018-09-19 11:52
It's just super annoying when I have 20 apps running on dev machine (what takes like 5 minutes to run) then I do some change and... everything goes down. So it's about productivity and wasting time, not the high priority.

**Comment by miyconst** [comment] 2020-01-31 10:44
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.

**Closed by miyconst** 2020-01-31 10:44 UTC
Labels: db, db-schema, db-schema-migration, nice to have
