### ISSUE TITLE
Proposal: Self.GET("/people/person/{?}", person)

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#190] opened 2017-07-28 15:27 UTC
Right now it is hard to do a `Self.GET` to an object that you have, because you need to serialize the objects identifier:

```c#
Self.GET("/people/person/" + person.GetObjectID()");
```

It gets nicer with a string expression, but still seems redundant work:

```c#
Self.GET($"/people/person/{person.GetObjectID()}");
```

## Proposal

It would be nice if `Self.GET` supported similar syntax as `Db.SQL` has for queries.

```java
Self.GET("/people/person/{?}", person);
```

Benefits:

- consistent: first param equals the string in the first param of `Handle.GET`
- convenient: if you have multiple `{?}` in your URI, provide multiple params to `Self.GET` overload.
- maybe more performant: do we have to serialize/deserialize objects to ids when passing them in `Blender.MapUri`?

**Comment by alemoi** [comment] 2017-11-06 23:35
The initial functionality for one database object argument is added. Here is the example:
```cs
[Database]
public class SomeDbClass {
	public Double DoubleProperty;
}
...
Handle.GET("/SomeDbClass/{?}", (SomeDbClass db) => {
	Double vv = db.DoubleProperty;
	return "ahahahha";
});

SomeDbClass c = null;
Db.Transact(() => {
	c = new SomeDbClass();
	c.DoubleProperty = 0.3401;
});

Response r = Self.GET("/SomeDbClass/{?}", c);
```

CC @warpech @miyconst @mtornwall

**Comment by miyconst** [comment] 2017-11-07 07:58
This makes the handler public and accessible from outside.

```cs
Handle.GET("/SomeDbClass/{?}", (SomeDbClass db) => {
    Double vv = db.DoubleProperty;
    return "ahahahha";
});
```

- What will happen when user tries to reach `/SomeDbClass/123`?
- What will happen for `Self.GET("/SomeDbClass/123")`?

**Comment by alemoi** [comment] 2017-11-07 08:58
If handler is called with a wrong ID the object reference will be null. Same behavior for Self and external calls.

**Comment by miyconst** [comment] 2017-11-07 09:03
>... a wrong ID ...

What is treated as a wrong ID? If the ID is correct, but points to an object of a different type?

Also, can I do the following:

```cs
Handle.GET("/Info/{?}", (Person p) => {
    return 200;
});

Handle.GET("/Info/{?}", (Company c) => {
    return 200;
});
```

**Comment by alemoi** [comment] 2017-11-07 09:06
I will check with correct but different class ID.
The second example won't work because you try to register same URI handler. Also underneath, the id is a string.

**Comment by miyconst** [comment] 2017-11-07 09:11
>The second example won't work because you try to register same URI handler. Also underneath, the id is a string.

As @warpech says, the task is not done until it's documented. Personally, I would expect this to work, same as c# works.

```cs
public int Info(Person p)
{
    return 200;
}

public int Info(Company c)
{
    return 200;
}
```

**Comment by alemoi** [comment] 2017-11-07 09:23
> As @warpech says, the task is not done until it's documented.

Sure!

>  Personally, I would expect this to work, same as c# works.

But not as handlers are working :) This would require a lot of work for the handler, which is not part of this proposal.

**Comment by miyconst** [comment] 2017-11-07 09:26
>But not as handlers are working :) This would require a lot of work for the handler, which is not part of this proposal.

Sure. Just make sure the behavior and the limitations are documented.

**Comment by alemoi** [comment] 2017-11-07 10:00
Regarding the different object cast, the exception is the following:
```
System.InvalidCastException: Unable to cast object of type 'Streamer.SomeDbClass2' to type 'Streamer.SomeDbClass'.
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in c:\github\level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in c:\github\level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in c:\github\level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
HResult=-2147467262
```
What do you think? I consider it good enough.

**Comment by miyconst** [comment] 2017-11-07 10:29
What happens in this case?

```cs
Handle.GET("/Info/{?}", (int i) => {
    return 200;
});

Self.GET("/Info/a");
```

**Comment by alemoi** [comment] 2017-11-07 10:45
> What happens in this case?

This is not related to this issue. But in this case the URI matcher will determine that its a wrong handler and it will result in static file resource handling attempt and "Error 404: Resource "/info/a" not found."

In case of database object handler - URI matcher accepts a string, so it matches it well. Later already inside the handler code, it tries to convert to needed type, but fails with exception.

**Comment by alemoi** [comment] 2017-11-07 10:58
> I would like to see the same behavior in both case, but let's see what @warpech says. Please keep the issue open until @warpech accepts it.

URI matcher does not know about database objects. When it comes to handling integers, it can detect that a letter is not integer, and use the default handler, which is static file resource handler.

**Comment by alemoi** [comment] 2017-11-10 20:47
@miyconst in any case I will not be able to achieve the same behaviour as with integer example you showed.

**Comment by alemoi** [comment] 2017-11-30 15:14
@miyconst should we close this issue?

**Comment by miyconst** [comment] 2017-11-30 15:19
Ping @warpech.

**Comment by warpech** [comment] 2017-11-30 17:11
I did some tests using 2.3.1.7793:

### Test 1. Providing ID of a wrong data type to typed Handle.GET

This is my handler:

```cs
            Handle.GET("/content/cms/item/{?}", (WebContent webContent) =>
            {
                return Db.Scope(() =>
                {
                    string url = "/content/partials/cms/item/" + webContent.GetObjectID();
                    MasterPage master = GetMasterPage();

                    master.PartialUrl = url;
                    master.RefreshCurrentPage();

                    return master;
                });
            });
```

The handler expects `Simplified.Ring6.WebContent` but the client has provided an ID of `Simplified.Ring5.SystemUserSession`.

**Result:** The handler does not execute and the client gets an exception:

```
System.InvalidCastException: Unable to cast object of type 'Simplified.Ring5.SystemUserSession' to type 'Simplified.Ring6.WebContent'.
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
HResult=-2147467262

More information about this error may be available in the server error log.
```

I guess this is fine, but here comes a question:

Where can I handle that exception? Imagine that I would like to have a custom error page. I guess this is a separate issue, same as in https://github.com/Starcounter/level1/issues/2959. @alemoi WDYT?

### Test 2. Providing something that is not an ID to typed Handle.GET

**Result:** The handler DOES execute and it receives `null` as the value, which is not handled in my handler. The client gets an exception:

```txt
System.ArgumentNullException: Value cannot be null.
Parameter name: obj
   at Starcounter.DbHelper.GetObjectID(Object obj) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter\Mock\DbHelper.cs:line 92
   at Starcounter.Self.GET(UInt16 port, String uri, Object databaseObject) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter.Internal\Rest\Self.cs:line 124
   at Content.ViewModels.MasterPage.RefreshCurrentPage(WebContent content) in C:\www\StarcounterApps\Content\src\Content\ViewModels\MasterPage.json.cs:line 37
   at Content.Api.MainHandlers.<>c__DisplayClass0_0.<Register>b__4() in C:\www\StarcounterApps\Content\src\Content\Api\MainHandlers.cs:line 41
   at Starcounter.Db.<>c__DisplayClass50_0`1.<Scope>b__0() in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter\Db.cs:line 541
   at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter\TransactionManager.cs:line 551
   at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter\Transaction.cs:line 224
   at Starcounter.Db.Scope(Action action, Boolean isReadOnly) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter\Db.cs:line 518
   at Starcounter.Db.Scope[TResult](Func`1 func, Boolean isReadOnly) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter\Db.cs:line 542
   at Content.Api.MainHandlers.<Register>b__0_3(WebContent webContent) in C:\www\StarcounterApps\Content\src\Content\Api\MainHandlers.cs:line 37
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-10971\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
ParamName=obj
HResult=-2147467261

More information about this error may be available in the server error log.
```

I am not sure if it is desired in typed handlers to get `null` in this case. I think that it should be no different to test 1 but I may be wrong here.

### Test 3. Using typed Self.GET

I tried to use `Self.GET("/content/partials/cms/item/{?}", content);` in my code.

**Result:** The response does not appear at all in the merged JSON.

@alemoi can you pls take a look?

To reproduce:

1. Clone, build and run [SignIn](https://github.com/starcounterapps/signin) `master` branch
1. Clone, build and run [WebsiteProvider](https://github.com/starcounter/website) `master` branch
2. Clone, build and run [Content](https://github.com/starcounterapps/content) `typed-handlers` branch commit `832af47089e3ddc3c1cd6515ae01d65fc0a81053`
3. Go to <http://localhost:8080/signin/createadminuser> to create an admin user
5. Go to <http://localhost:8080/signin> to sign in as the admin user
5. Go to <http://localhost:8080/content/cms> and press "Create" to create a new content

Expected: 

You should see the content editing form and SignIn at the bottom

Actual: 

You only see SignIn

------

Does anyone from @Starcounter/sc-apps want to evaluate this new API too?

**Comment by miyconst** [comment] 2019-12-06 11:10
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:10 UTC
Labels: nice to have, question, won’t fix
