### ISSUE TITLE
Remove session URI from PartialToStandaloneHtmlProvider

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#333] opened 2017-12-07 15:53 UTC
In order to allow best possible experience with Progressive Web Apps (PWA), we need to make the initial bootraping HTML ("app shell") free of session ID. This will allow us to:

- cache the app shell on the client side
- improve the time to first contentful paint by speeding up the request for view-model

Right now app shell HTML that comes from `PartialToStandaloneHtmlProvider.cs` contains the session URI. 

Please note that to achieve blending compatibility, the app shell HTML must be the same for all apps, including mobile apps, PWAs, etc.

cc @Starcounter/webplatformteam, @miyconst

**Comment by miyconst** [comment] 2017-12-07 15:55
How do we provide session id then?

**Comment by warpech** [comment] 2017-12-07 16:21
We can change the `PartialToStandaloneHtmlProvider.cs` middleware to be always on, so that the app developer does not have to initiate it. Imagine such flow:

1. Browser makes a request. 
2. PartialToStandaloneHtmlProvider checks if the request:
   - has type `Accept: text/html`
   - will be handled by a registered handler (and the handler does not have `SkipRequestFilters: true`)
3. If the answer for the above points is positive, PartialToStandaloneHtmlProvider immediately responds with the bootstraping HTML (without calling the handler!).
4. Browser receives the bootstraping HTML and runs Palindrom.
5. Palindrom makes a request with headers `Accept: application/json` and `X-Palindrom-Protocol-Version: 1` to the same URI. 
6. The request is handled by the app. 
7. The app responds with a `Json`.
8. If the response is a `Json` and the request was `Accept: application/json` and `X-Palindrom-Protocol-Version: 1`, a middleware creates a Starcounter session even if the app did not create the session.
9. The server responds with the stringified JSON and the header `Location: /_db/default/<sessionid>`
10. Palindrom reads the session URI from the `Location` header
11. Palindrom creates the WebSocket upgrade to the session URI
12. Palindrom sends patches to the session URI

This is the only idea that I have. Maybe someone has better?

Related: https://github.com/Palindrom/Palindrom/issues/61

**Comment by miyconst** [comment] 2017-12-08 07:28
>If the answer for the above points is positive, PartialToStandaloneHtmlProvider immediately responds with the bootstraping HTML (without calling the handler!).

How does it know which HTML to return?

**Comment by warpech** [comment] 2017-12-08 08:37
It is always the same HTML:

> Please note that to achieve blending compatibility, the bootstraping HTML must be the same for all apps, including mobile apps, PWAs, etc.

**Comment by miyconst** [comment] 2017-12-08 08:39
>It is always the same HTML:

Does this mean, that apps are no longer allowed to have their own `PartialToStandaloneHtmlProvider`?

What if someone does not care about the blending features?

**Comment by warpech** [comment] 2017-12-08 12:24
> Does this mean, that apps are no longer allowed to have their own `PartialToStandaloneHtmlProvider`?

Yes, because if your app depends on a custom `PartialToStandaloneHtmlProvider` as the entry point, it will not work when another app (with the standard `PartialToStandaloneHtmlProvider`) is used as the entry point. 

> What if someone does not care about the blending features?

Then they should make their app explicitly not blendable by using `SkipRequestFilters: true`

**Comment by miyconst** [comment] 2017-12-08 12:57
>Then they should make their app explicitly not blendable by using `HandlerOptions { SkipRequestFilters: true }`.

This means: either use blending or request filters. What if an app does not need blending but requires request filters?

Another reason to push myself with `Starcounter.Mvc` implementation, since there it's possible to enable/disable filters per handler.

**Comment by warpech** [comment] 2017-12-11 16:38
> This means: either use blending or request filters. What if an app does not need blending but requires request filters?

An app should not **require** request filters because it should not have external dependencies. But I agree the connection between these two is far-fetched.

We can do two alternatives:
1. provide a separate `HandlerOptions { Blendable: true }` that means this page is not wrapped by `PartialToStandaloneHtmlProvider` and is not considered by `Blender.MapUri`).
2. or, only the pages which are explicitly mapped to `Blender.MapUri` should be considered blendable wrapped in `PartialToStandaloneHtmlProvider`.

**Comment by miyconst** [comment] 2017-12-11 18:37
>An app should not require request filters because it should not have external dependencies.

A request filter is not necessary an external dependency. What if an app implements it's own auth layer via request filters?

Both of the alternatives are not good. I might sound like I am denying everything, and not proposing anything, but the problem is that our request filter mechanism is really ~~broken~~ limited.

Tomorrow I will present you my concept how to get the blending features using `Starcounter.Mvc`.

**Comment by warpech** [comment] 2017-12-12 15:47
> A request filter is not necessary an external dependency. What if an app implements it's own auth layer via request filters?

I agree. I hope we can address this by fixing the middleware layer and then using `Starcounter.Mvc` on top of that. I thought there is actually an issue for registering a local (not global) middleware, but I can't find it.

Anywhere, we got offtopic.

I made a change to https://github.com/Starcounter/Home/issues/333#issuecomment-350018064 to use `Blendable: true` instead of `SkipRequestFilters: false`. Please re-review.

cc @tomalec, @alshakero

**Comment by miyconst** [comment] 2017-12-13 12:33
>I made a change to #333 (comment) to use `Blendable: true` instead of `SkipRequestFilters: false`. Please re-review.

This looks much better now.

**Comment by warpech** [comment] 2018-08-08 21:29
@alemoi this change is needed to improve performance in the Omni project.

Is it possible for you to engage in developing the solution explained in https://github.com/Starcounter/Home/issues/333#issuecomment-350018064?

What is needed from you:

1. Implement handler option `Blendable`
2. Implement change in `PartialToStandaloneHtmlProvider` from the point 2 of my comment

cc @miyconst, @alshakero

**Comment by warpech** [comment] 2018-08-09 12:56
I have changed my comment https://github.com/Starcounter/Home/issues/333#issuecomment-350018064 to be aligned with the proposed changes to the Palindrom spec. That is more optimal for client-side performance.

**Comment by miyconst** [comment] 2018-08-10 12:15
Marking the issue as `nice to have`, means it has medium priority, as agreed during the [release planning](https://github.com/Starcounter/Minutes/issues/184).

**Comment by miyconst** [comment] 2020-01-31 10:42
Closing as won't fix in Starcounter 2.4 and not applicable in Starcounter 3.0.

**Closed by miyconst** 2020-01-31 10:42 UTC
Labels: investigate, nice to have, web, web-palindrom, won’t fix
