### ISSUE TITLE
⏰ System.IndexOutOfRangeException: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by atifwaqar** [Starcounter/Home#303] opened 2017-11-07 13:50 UTC
(Note: I have a feeling that this issue might be already reported, since there are many issues with `Index was outside the bounds of the array`)

SC Version 2.3.1.7717

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.    at Starcounter.Internal.DbState.View.GetObject(TypeBinding binding, Int32 index, Object proxy) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Internal\DbState.cs:line 71    at AdFenix.Database.Concept.Starcounter.IObjectView.GetObject(Int32 index)    at Starcounter.Query.Execution.StringPath.EvaluateToString(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\Paths\StringPath.cs:line 154    at Starcounter.Query.Execution.ComparisonString.Evaluate(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\LogicalExpressions\ComparisonString.cs:line 141    at Starcounter.Query.Execution.LogicalOperation.Evaluate(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 131    at Starcounter.Query.Execution.LogicalOperation.Evaluate(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 127    at Starcounter.Query.Execution.LogicalOperation.Filtrate(IObjectView obj) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\LogicalExpressions\LogicalOperation.cs:line 209    at Starcounter.Enumerator.MoveNext() in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Mock\Enumerator.cs:line 256    at Starcounter.Query.Execution.IndexScan.MoveNextManaged() in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 484    at Starcounter.Query.Execution.IndexScan.MoveNext() in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\Enumerators\IndexScan.cs:line 521    at Starcounter.Query.Execution.Aggregation.MoveNext() in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter\Query\Execution\Enumerators\Aggregation.cs:line 188    at Starcounter.Internal.SqlRestHandler.ExecuteQuery(String query, Int32 maxResult) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\SqlRestHandler.cs:line 142 HResult=-2146233080
--
```

I can reproduce this by using 3rd Query from description of issue Starcounter/level1#3688
```
select count(a) from adfenix.database.classifiedhomead a where publicationowner.domain='www.lansfast.se' and home.hometype.name is null and uniqueidentifier is not null
```

![image](https://user-images.githubusercontent.com/4388707/32496858-ef420966-c3ca-11e7-9217-288c43c639fc.png)

**Comment by alemoi** [comment] 2017-11-07 13:50
CC @k-rus

**Comment by k-rus** [comment] 2017-11-07 14:32
Thank you for reporting. 

The exception is different, but I guess the cause of the error is similar to Starcounter/level1#3688
It is very likely a problem in the query optimizer and query executor code. It is difficult to say how it is difficult to fix. The first step for us will be to reproduce the issue in a smaller example.

**Comment by k-rus** [comment] 2017-11-07 14:39
@miyconst I think we can mark this issue as a time bomb until proven otherwise.

**Comment by miyconst** [comment] 2017-11-07 14:43
@atifwaqar is it this query?

```sql
select count(a) 
from adfenix.database.classifiedhomead a 
where publicationowner.domain = 'www.lansfast.se' 
    and home.hometype.name is null 
    and uniqueidentifier is not null
```

Can you please provide the `adfenix.database.classifiedhomead` class declaration?

**Comment by atifwaqar** [comment] 2017-11-07 15:01
@miyconst Just sent it to your Slack.

**Comment by miyconst** [comment] 2017-11-08 10:22
The problem is nailed down and described  in the issue linked above. I am closing this one, since it's long and not very informative.

**Closed by miyconst** 2017-11-08 10:22 UTC
Labels: bug, qp, qp-old, required
