### ISSUE TITLE
Starpack cannot find assemblies

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#152] opened 2017-06-14 13:55 UTC
I have encountered an error related to how starpack finds assemblies during `pack`

To illustrate this, let's say I have two assemblies
`Mopedo.Base` (a class library) and
`TestApp2`  (an application)

I can have an assembly reference to `Mopedo.Base` from my `TestApp2` application, and starpack will handle that just fine. Building and packing the following works:

```c
namespace TestApp2
{
    class Program
    {
        static void Main() => new Mopedo.Base.ForeignKey();
    }
}
```

I cannot, however, have the app inheritit from a class in another assembly. Building works for the following, but packing fails:

```c
namespace TestApp2
{
    class Program : Mopedo.Base.ForeignKey
    {
        static void Main() { }
    }
}
```
This is a big issue for us, since all our applications inherit from a base app in a common assembly.

Stacktrace:

PS C:\Users\erik\DRTB\testapp2> starpack -p

System.IO.FileNotFoundException: Could not load file or assembly 'Mopedo.Base, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Mopedo.Base, Version=1.0.0.1, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetEntryPoint(RuntimeAssembly assembly, ObjectHandleOnStack retMethod)
   at System.Reflection.RuntimeAssembly.get_EntryPoint()
   at Starcounter.Apps.Package.Archive.ReadAssemblyFile(String file, String& id, String& title, String& version, String& company, String& description, DateTime& buildDate, String& channel) in C:\TeamCity\BuildAgent\work\sc-5093\Level1\src\Starcounter.Apps.Package\Archive.cs:line 485
   at Starcounter.Apps.Package.Archive.CreatePackageConfig() in C:\TeamCity\BuildAgent\work\sc-5093\Level1\src\Starcounter.Apps.Package\Archive.cs:line 407
   at Starcounter.Apps.Package.Archive.Create(String file, Boolean build, String projectConfiguration, String executable, String resourceFolder) in C:\TeamCity\BuildAgent\work\sc-5093\Level1\src\Starcounter.Apps.Package\Archive.cs:line 143
   at StarPack.ArchivePack.Execute(PackOptions options) in C:\TeamCity\BuildAgent\work\sc-5093\Level1\src\Programs\StarPack\ArchivePack.cs:line 11
   at StarPack.Program.Main(String[] args) in C:\TeamCity\BuildAgent\work\sc-5093\Level1\src\Programs\StarPack\Program.cs:line 22

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by erikvk** [comment] 2017-06-14 13:55
@andwah

**Comment by erikvk** [comment] 2017-06-14 14:07
I just found a work-around (makes this a smaller issue for now).

I can have a new class `Launcher` in my `TestApp2` assembly, that contains the `main()` method and simply instantiates my app. The executable will then not inherit from a separate assembly – which works.

```c
namespace TestApp2
{
    class Program : Mopedo.Base.ForeignKey
    {
        static void Run() 
        { 
            // do stuff 
        }
    }

    public class Launcher
    {
        public static void Main() => Program.Run();
    }
}

```

**Comment by miyconst** [comment] 2019-12-06 11:09
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:09 UTC
Labels: bug, nice to have, tools, windows, won’t fix
