### ISSUE TITLE
Visual studio error "Evaluating the function timed out".

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Home#108] opened 2017-05-11 12:28 UTC
When I'm trying to look up under Data variable in my json.cs file (e.g. SystemUserAuthenticationSettings.json.cs) I'm getting error: 

![image](https://cloud.githubusercontent.com/assets/25042256/25948928/05bdf040-3656-11e7-8ae5-bdc80dbeaba5.png)

after clicking OK and trying to stop debugger I'm getting: 
![image](https://cloud.githubusercontent.com/assets/25042256/25948323/3d37b0cc-3653-11e7-9424-4dd9498ba3a2.png)
and then all my starcounter applications (not only the one that I was debugging) are shut down. 
This issue might have connection with that I updated my starcounter lately to newest version (2.3.1.6413), but I'm not sure about it. It can also be related with that, It doesn't work on apps that are connected to others and invoked by them.

Do You know this issue, or have some advice what can I do to fix this?
OS: Windows 10
SC version: 2.3.1.6413.
Visual studio 2017

**Comment by miyconst** [comment] 2017-05-11 13:21
This is a serious issue.

I suspect this is happening because debugger pauses the thread while in a transaction, and VS Debugger Watch window is trying to read the locked values while Starcounter waits for the main thread be released.

@alemoi, @per-samuelsson, @linkdata, @bigwad anything you can say?

**Comment by bigwad** [comment] 2017-05-11 13:25
Probably duplicate of https://github.com/Starcounter/level1/issues/4201

**Comment by miyconst** [comment] 2017-05-11 13:27
Not probably, but for sure. @bigwad thanks for linking. I close this issue as duplicate.

**Closed by miyconst** 2017-05-11 13:27 UTC
Labels: Bug

**Comment by k-rus** [comment] 2017-05-11 13:46
> Not probably, but for sure. @bigwad thanks for linking. I close this issue as duplicate.

Note that Starcounter/level1#4201 is private.
