### ISSUE TITLE
⏰ Issue with AND operator and Double type

### ISSUE THREAD

**Issue by bouguila** [Starcounter/Home#265] opened 2017-10-06 09:02 UTC
## Description
I am trying to query a table from Administrator SQL command line, but the `AND` operator in the `WHERE` clause seems to be malfunctioning if it is composed of many comparisons with `double` values. 

- The code below have a simple `WHERE` clause and it works fine:

![2](https://user-images.githubusercontent.com/12608524/31270374-718f2aee-aa84-11e7-9538-a001dc971f5f.PNG)

- In the code below i duplicated the same condition, but did NOT work

![1](https://user-images.githubusercontent.com/12608524/31270471-d153e0be-aa84-11e7-8339-1dcfc212e735.PNG)

- further more, i tried to make the comparison with integer values  and it seemed to work:

![4](https://user-images.githubusercontent.com/12608524/31270598-41ee657e-aa85-11e7-8536-f5fb66aceec3.PNG)

- but again if we compare `double` values we get no result:

![3](https://user-images.githubusercontent.com/12608524/31270636-71d4a8a2-aa85-11e7-9a70-cbfe0136be0f.PNG)

**Sc version 2.3.1.7371**

cc @k-rus , @alemoi

**Comment by k-rus** [comment] 2017-10-06 11:48
Thank you for reporting. Seems to be a bug. Requires investigating.

Can you provide a simple way to reproduce the issue, including source code of an app with population code?

**Comment by bouguila** [comment] 2017-10-06 12:23
@k-rus here is the repo :
https://github.com/StarcounterApps/VehicleTrackDemo/settings

Just clone & run it locally, and it will generate a db with 2 tables `CarTracking.Vehicle` and `CarTracking.GpsPosition`  which will be populated with dynamic data from an external server.

**Comment by k-rus** [comment] 2017-10-06 12:27
Thank you!

**Comment by un-tone** [comment] 2018-02-13 09:46
The problem is in `star_filter_iterator_next` function https://github.com/Starcounter/level1/blob/5397023635ec1ecf1a750272c653a9b7cdd0f889/src/Starcounter/Mock/Enumerator.cs#L486

After calling that, here https://github.com/Starcounter/level1/blob/5397023635ec1ecf1a750272c653a9b7cdd0f889/src/Starcounter/Mock/Enumerator.cs#L501, `currentRef.handle.id` is zero. So the enumerator obtains nothing.

@bigwad I see that you have fixed the similar bug. Can you look at this one in the cpp code?

**Comment by un-tone** [comment] 2018-02-13 09:57
The Query plan looks well:

```sql
select * from Home_265.GpsPosition p
where p.Longitude > 11.940347 and p.Longitude > 11.940346
```

```
Tables(
 0 = Home_265.GpsPosition
)
Projection(
 0 = 
  DoubleProperty(0, Longitude)
 1 = 
  DoubleProperty(0, Latitude)
 2 = 
  DateTimeProperty(0, Timestamp)
 3 = 
  ObjectNoProperty(0, ObjectNo)
 4 = 
  ObjectIDProperty(0, ObjectID)
)
FullTableScan(
 Home_265.GpsPosition
 0
 LogicalOperation(
  AND
  ComparisonDouble(
   GreaterThan
   DoubleProperty(0, Longitude)
   DecimalLiteral(11.940347)
  )
  ComparisonDouble(
   GreaterThan
   DoubleProperty(0, Longitude)
   DecimalLiteral(11.940346)
  )
 )
 Ascending
)
```

**Comment by bigwad** [comment] 2018-02-13 15:56
@un-tone, if rewrite a query with parameters instead of literals, it will work. 
So, something wrong with collecting a stream of filter parameters, that is passed to `star_context_create_filter_iterator` here https://github.com/Starcounter/level1/blob/5397023635ec1ecf1a750272c653a9b7cdd0f889/src/Starcounter/Mock/IteratorHelper.cs#L285
You can compare how the stream is filled in both cases - with literals and with query parameters.

**Comment by un-tone** [comment] 2018-02-14 20:52
The issue is in **decimal literals** and it appears only when decimal literal is specified in the first comparison. It works well with other numerical types and if decimal literal is in the second comparison.

For instance I have the following model:

```cs
    public class GpsPosition
    {
        public double Longitude { get; set; }
        public decimal Latitude { get; set; }
        public int Cnt { get; set; }
        public DateTime Timestamp { get; set; }
    }
```

All the following queries do not work:

```sql
select * from Home_265.GpsPosition p where p.Cnt > 3.34343 and p.Cnt > 3
select * from Home_265.GpsPosition p where p.Latitude > 56.34343 and p.Latitude > 56
select * from Home_265.GpsPosition p where p.Longitude > 11.34343 and p.Longitude > 11
```

If in this queries I don't use decimal literal in first comparisons, it works well.

**Comment by un-tone** [comment] 2018-02-14 20:53
@bigwad I tried to find out what happens there, but still with no results. I'll continue tomorrow.

**Comment by un-tone** [comment] 2018-02-15 13:15
I have compared passing `dataStream` and `instrArray` instances. And the issue case looks proper to me. @bigwad please take a look, maybe you'll have some clue.

1. Without the error (2 integer literals):

```sql
select * from Home_265.GpsPosition p where p.Longitude > 11 and p.Longitude > 11
```

```
instrArr:
    [0]: 779
    [1]: 69
    [2]: 1
    [3]: 67
    [4]: 52
    [5]: 779
    [6]: 69
    [7]: 1
    [8]: 67
    [9]: 52
    [10]: 62
dataStream:
    [0]: 22
    [1]: 0
    [2]: 0
    [3]: 0
    [4]: 1
    [5]: 11
    [6]: 0
    [7]: 0
    [8]: 0
    [9]: 0
    [10]: 0
    [11]: 0
    [12]: 0
    [13]: 1
    [14]: 11
```

2. With the error (decimal and integer literal):

```sql
select * from Home_265.GpsPosition p where p.Longitude > 11.0 and p.Longitude > 11
```

```
instrArr:
    [0]: 779
    [1]: 69
    [2]: 6
    [3]: 52
    [4]: 779
    [5]: 69
    [6]: 1
    [7]: 67
    [8]: 52
    [9]: 62
dataStream:
    [0]: 30
    [1]: 0
    [2]: 0
    [3]: 0
    [4]: 1
    [5]: 0
    [6]: 0
    [7]: 96
    [8]: 1
    [9]: 0
    [10]: 0
    [11]: 0
    [12]: 0
    [13]: 0
    [14]: 0
    [15]: 0
    [16]: 0
    [17]: 0
    [18]: 0
    [19]: 0
    [20]: 0
    [21]: 1
    [22]: 11
```

3. Without the error (1 decimal literal):

```sql
select * from Home_265.GpsPosition p where p.Longitude > 11.0
```

```
instrArr:
    [0]: 779
    [1]: 69
    [2]: 6
    [3]: 52
dataStream:
    [0]: 21
    [1]: 0
    [2]: 0
    [3]: 0
    [4]: 1
    [5]: 0
    [6]: 0
    [7]: 96
    [8]: 1
```

**Comment by bigwad** [comment] 2018-02-15 13:34
Have you compared the streams when a decimal is passed as a parameter, not a literal?
I guess problem is that serializing decimal as a literal takes 16 bytes, while it should take 8. Here is the format of dataStream to make it easier for you to reason about it.
The stream starts with 4 bytes little-endian length of the entire stream. Then variables go. Each variable starts with a one byte flag (0/1) which shows if a variable is defined, or NULL. Then goes the value itself if the variable is defined. The space variable takes depends on a type. Integers, decimals and doubles take 8 bytes. Floats take 4. Binaries and strings occupies the space according to their respective length.

**Comment by un-tone** [comment] 2018-02-15 14:38
> I guess problem is that serializing decimal as a literal takes 16 bytes

Exactly! It fixes the bug. Thank you.

**Comment by k-rus** [comment] 2018-02-16 06:39
The OP was only about doubles, while the bug happens to be with decimal. Is there still an issue with doubles? Or how does fix for decimal fixes the OP with double?

**Comment by un-tone** [comment] 2018-02-16 08:17
@k-rus Actually, there is no issue with doubles. Investigation showed that the issue is in decimal literals. It also showed in OP example that decimal literals are used. You can change the property type in the query to another numerical one, e.g. Integer, and the bug will be still reproducible. Please take a look at the comment above https://github.com/Starcounter/Home/issues/265#issuecomment-365741280.

**Comment by un-tone** [comment] 2018-02-19 19:21
Closing as done.

**Closed by un-tone** 2018-02-19 19:21 UTC
Labels: bug, desired, qp, qp-old
