### ISSUE TITLE
Unexpected occurance of ScErrForbiddenFieldInitializer (SCERR4263)

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#169] opened 2017-06-30 00:05 UTC
Here's a strange one...

Adding this data definition
```c#
[Database]
public class Test
{
    public string SomeString { get; }
    public Test(string someString)
    {
        SomeString = someString;
        var others = Db.SQL<Test>($"SELECT t FROM {typeof(Test).FullName} t");
        var equals = others.Where(s => s.SomeString == someString);
    }
}
```
 to a Starcounter project on 2.3.1.6402 will generate a
```
Initializing fields in database classes must be done inside a constructor. Field initializers are not
supported. Field "Mopedo.Database.Test.<>c__DisplayClass3_0.someString" 
ScErrForbiddenFieldInitializer (SCERR4263))
```
on application launch. This, however, works just fine:
```c#
[Database]
public class Test
{
    public string SomeString { get; }
    public Test(string someString)
    {
        SomeString = someString;
        var others = Db.SQL<Test>($"SELECT t FROM {typeof(Test).FullName} t");
        // var equals = others.Where(s => s.SomeString == someString);
    }
}
```
To generalize, I think the problem occurs when a LINQ statement is used in the constructor, in which a reference is made to a member of the class along with a reference to some object in the constructors scope.
@per-samuelsson

**Comment by rogeralsing** [comment] 2017-06-30 05:57
Here is what is going on:
The ctor has an argument that is later used inside a lambda.
The C# compiler will lift that argument and create a "displayclass" containing it.
So in this specific case, we have a displayclass called `<>c__DisplayClass3_0` containing a field `someString`
There is also a method called `<.ctor>b__0` on this class, this is your lambda method.

So in essence, your class gets expanded to:

```csharp
[Database]
public class Test
{
    public string SomeString { get; }

    private class <>c__DisplayClass3_0
    {
           public string someString;
           public bool <.ctor>b__0(Test other) 
           {
                    return other.SomeString == this.someString;
           }
    }

    public Test(string someString)
    {
        var CS$<>8__locals0 = new <>c__DisplayClass3_0(someString);
        SomeString = CS$<>8__locals0.someString; 
        var others = Db.SQL<Test>($"SELECT t FROM {typeof(Test).FullName} t");
        
        var equals = others.Where(CS$<>8__locals0.<.ctor>b__0);
    }
}
```


My guess is that the weaver gets confused about this part:

```csharp
        var CS$<>8__locals0 = new <>c__DisplayClass3_0(someString);
        SomeString = CS$<>8__locals0.someString;  //this bit
```

OR.
That the weaver believes that the displayclass itself is a Database class as it is a nested class in the Test class?

**Comment by per-samuelsson** [comment] 2017-06-30 06:29
@rogeralsing, thanks for helping out!

> That the weaver believes that the displayclass itself is a Database class as it is a nested class in the Test class?

I'm quite sure that is not the case, since weaver would only ever operate on classes explicitly marked as database classes, and that include nested classes. Actually, if I recall correctly, we currently even don't support nested database classes, and I think the reason was some problem with how we should use their names in combination with SQL.

Just very generally, the weaver (and underlying PostSharp version) is getting pretty old, and we are already of cases where new language constructs (e.g expressions) are causing it trouble. This might be another one.

Anyway, I'm assigning this case to me to have a look at it during the day today. I'll get back to you on it later.

**Comment by rogeralsing** [comment] 2017-06-30 07:42
Even this generates the described problem.

```csharp
[Database]
public class Test
{
    public Test(string someString)
    {
       Action a = () => someString.ToString();
    }
}
```

**Comment by per-samuelsson** [comment] 2017-06-30 08:58
Update: I've been able to reproduce both on 2.3 and have found we did in fact rewrote the implementation that validates constructors in the weaver ~ 4 years ago. The new implementation is pretty naive, and if I'm reverting to the older (much more complex) version, above code pass.

What is bothering is there seem to be no regression tests stuck to the rewrite, so I can't really tell why it was done. It's not unlikely the old implementation contained some other problem, just that I'm not sure what.

**Comment by erikvk** [comment] 2017-06-30 09:41
OK, the issue is easy to work around. This is how I did it in my real data class:

```c#
public User(string userId)
{
    if (string.IsNullOrWhiteSpace(userId))
        throw new Exception("Missing or invalid UserId, cannot be null, empty or whitespace");
    userId = userId.Trim();
    var init = Select<User>.Where(nameof(UserId), "=", userId);
    var moreThanOne = MoreThanOne(init, userId);
    if (moreThanOne)
        this.CancelConstructor($"A User with UserId '{userId}' already exists.");
    UserId = userId;
    this.CreatedNow();
}

private static bool MoreThanOne(IEnumerable<User> users, string userId) =>
    users.Where(u => u.UserId == userId).MoreThanOne();
```
Just moving the lambda to a static method will solve the issue.

**Comment by per-samuelsson** [comment] 2017-06-30 10:21
> Just moving the lambda to a static method will solve the issue.

Thanks for sharing that @erikvk, and for providing all feedback in general.

I'm somewhat reluctant to change the constructor validation back to it's own implementation at this very point, since I'm not sure why we made the change in the first place, and I'm not sure how much I can work with it / give proper support if it would have side effects in upcoming weeks. The state of affairs right now is not good, but at least there is now a known workaround.

I'm leaning towards postponing this until august, since we will need to make a focused effort to improve relevant things at that point anyway, including trying to get further on Roslyn-based weaver. 

Let me know if you think that decision is bad.

**Comment by erikvk** [comment] 2017-06-30 10:26
Going back to old code can be a nightmare, so I'm with you on that :)

What I'm missing in these cases, and in other cases when Starcounter errors are thrown, is appropriate feedback. Clicking on an exception's "Learn more" link usually leads to a GitHub 404, or some empty error page. Just a little information saying "We know of this error, just put your lambda in a static helper method and carry on", would make these errors so much easier to deal with.

**Comment by rogeralsing** [comment] 2017-06-30 10:31
The easiest workaround seems to be to just copye the ctor arg to a local var.
This works:

```csharp
    [Database]
    public class Test
    {
        public string SomeString { get; }
        public Test(string someString)
        {
            
            SomeString = someString;
            var others = Db.SQL<Test>($"SELECT t FROM {typeof(Test).FullName} t");
            var copy = someString;
            var equals = others.Where(s => s.SomeString == copy);
        }
    }
```

This way, the ctor arg is not lifted into the displayclass (now it's the copy)

**Comment by erikvk** [comment] 2017-06-30 10:32
Nice, thank you. I will use that workaround in my project

**Comment by per-samuelsson** [comment] 2017-06-30 10:48
> What I'm missing in these cases, and in other cases when Starcounter errors are thrown, is appropriate feedback. Clicking on an exception's "Learn more" link usually leads to a GitHub 404, or some empty error page. Just a little information saying "We know of this error, just put your lambda in a static helper method and carry on", would make these errors so much easier to deal with.

Totally understand what you are saying, and 100% agree that we need to improve quite a bit in this area.

And, actually, there is already an effort going on, to support a better infrastructure for us to start documenting about particular cases, and promote that to developers. It's discussed here: https://github.com/Starcounter/TechComm/issues/253. Although I'm not sure you can access that?

Maybe @Mackiovello can bring some additional insight?

**Comment by miyconst** [comment] 2019-12-06 11:10
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:10 UTC
Labels: bug, nice to have, weaver, won’t fix
