### ISSUE TITLE
System.InvalidCastException when using AppHostBuilder

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Home#380] opened 2018-02-14 14:45 UTC
## Context
Starcounter version: 2.4.0.4593
I'm trying to follow the guide to setting up tests in Self-Hosted Starcounter:  [link](https://docs.starcounter.io/v/2.4/cookbook/unit-testing-with-database-access).

## Problem
When I execute `AppHostBuilder.Start()` the following exception occurs:

```
System.InvalidCastException
[A]Sc.Server.Weaver.Schema.DatabaseAssembly cannot be cast to [B]Sc.Server.Weaver.Schema.DatabaseAssembly. Type A originates from 'Starcounter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf' in the context 'LoadNeither' at location 'C:\Program Files\Starcounter\Starcounter.dll'. Type B originates from 'Starcounter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf' in the context 'LoadFrom' at location 'C:\Users\joozek\dev\authorization.simplified\Authorization.Simplified.Tests\bin\Debug\Starcounter.dll'.
   at Sc.Server.Weaver.Schema.DatabaseAssembly.Deserialize(Stream stream) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter\Mock\Schema\DatabaseAssembly.cs:line 190
   at Sc.Server.Weaver.Schema.DatabaseSchema.DeserializeFrom(Stream stream) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter\Mock\Schema\DatabaseSchema.cs:line 357
   at Starcounter.Hosting.RuntimeHosts.SelfHosted.AssemblyResolver.Starcounter.Hosting.IAssemblyResolver.RegisterApplication(String executablePath, DatabaseSchema& schema) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter.Hosting\RuntimeHosts\SelfHosted\AssemblyResolver.cs:line 35
   at StarcounterInternal.Hosting.Loader.ExecuteApplication(Void* hsched, ApplicationBase appBase, EntrypointOptions entrypointOptions, Stopwatch stopwatch) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter.Hosting\StarcounterInternal.Hosting\Loader.cs:line 109
   at Starcounter.Hosting.RuntimeHosts.RuntimeHost.Run(Func`1 appStartProvider) in C:\TeamCity\BuildAgent\work\sc-14742\Level1\src\Starcounter.Hosting\RuntimeHosts\RuntimeHost.cs:line 337
   at Authorization.Database.Tests.TestContext..ctor() in C:\Users\joozek\dev\authorization.simplified\Authorization.Simplified.Tests\TestContext.cs:line 38
```

## Reproduction
Code: https://github.com/Starcounter/Authorization.Simplified/tree/tests-repro
Build, and then run [`TestIfTestsTestTheTests`](https://github.com/Starcounter/Authorization.Simplified/blob/master/Authorization.Simplified.Tests/Class1.cs#L13). 
Alternatively, execute `test` target of Authorization.Simplified.Tests.csproj:
```
msbuild /t:test Authorization.Simplified.Tests\Authorization.Simplified.Tests.csproj
```

## Notes
When running the repro for the second time you may bump into #379
After the failure the test usually hangs. `staradmin kill devall` helps. I don't know if it's a separate issue or it's caused by this

**Comment by joozek78** [comment] 2018-02-14 14:55
Related: #357 
CC @per-samuelsson you asked me to ping you

**Comment by per-samuelsson** [comment] 2018-02-15 06:13
> CC @per-samuelsson you asked me to ping you

Yes, thanks a lot for taking the time to set this sample up. I will look into it and hopefully give you some feedback already today.

**Comment by per-samuelsson** [comment] 2018-02-15 06:27
It seem this is what I first expected: it's because some inconsistency in new self-hosting assembly resolver, causing that [same types loaded from different contexts are not assignable](https://blogs.msdn.microsoft.com/suzcook/2004/06/02/debugging-an-invalidcastexception/).

I will need to set up an environment for this and go through how assembly resolving happen in our self-hosting scenario, and then see how we can adapt. It's probably gonna be a day or two to figure it out.

@joozek78, what's the time-frame here? ASAP as usual I guess? 😎 Reason I'm asking is if should first try to wrap up first iteration of post-commit hooks I'm currently developing in 2.3 (which is a few more days max), or switch environment to this before. For me, it doesn't really matter, so you choose. Please synchronize it with @miyconst too.

**Comment by miyconst** [comment] 2018-02-15 08:49
>I'm currently developing in 2.3 (which is a few more days max), or switch environment to this before.

Going this way. @per-samuelsson please finish the deferred callbacks first, even if it takes the rest of this week and a few days of the next week.

**Comment by per-samuelsson** [comment] 2018-03-19 06:27
Started working on this now, and hope to have at least some idea of how to solve it later today.

**Comment by per-samuelsson** [comment] 2018-03-19 13:54
Spent the day reviewing our custom assembly resolving and the one we have for self-hosted apps in particular, and then redesigned some parts of it.

I've tested using the OP repro and it now passes locally, so when TC tests also passed, I've merged and pushed this (https://github.com/Starcounter/level1/commit/10cc3403e5c713f7c7e63374eac92557f28a0377).

Closing this as fixed for now, but suggest @miyconst only do that in the Odessa project once @joozek78 has confirmed it actually works for him. If it doesn't, please reopen.

**Closed by per-samuelsson** 2018-03-19 13:54 UTC
Labels: bug, hosting, hosting-unit-test, required, test

**Comment by joozek78** [comment] 2018-03-20 16:38
I confirm, that it works for me. I'm finally able to execute the database tests. Thanks for the fix!

**Comment by per-samuelsson** [comment] 2018-03-21 06:08
> I confirm, that it works for me.

Great. Then @miyconst should update project accordingly.
