### ISSUE TITLE
Starcounter setup missing MSVCR100.dll

### ISSUE THREAD

**Issue by habib535** [Starcounter/Home#288] opened 2017-10-25 15:01 UTC
I am trying to install Starcounter on a fresh machine. Starcounter auto install c++ redistributable if is not installed on the system. 
![image](https://user-images.githubusercontent.com/2991381/32005893-b7fba388-b9a5-11e7-9d1a-d816d624d5ed.png)

When I start the server it gives the error that MSVCR100.dll was not found.
![image](https://user-images.githubusercontent.com/2991381/32005905-bd5800ec-b9a5-11e7-8efa-6a7879d04cdc.png)

I checked that c++ redistributable 2017 x86 & x64 was installed. I tried reinstalling both and still got the same error. I tried redistributable 2015, 2013, 2012 and none of them worked but 2010 worked.

Have anyone else faced this issue before? this was reported yesterday by a customer and he ended up manually coping the dll from his development machine to server. If redistributable 2017 is not copying this dll and is required by Starcounter, we can probably make it part of the setup to manually copy these dlls?

I also got a couple of security warnings, maybe my firewall settings are very strict?
![image](https://user-images.githubusercontent.com/2991381/32005968-de005556-b9a5-11e7-82d0-84b606a6746f.png)

![image](https://user-images.githubusercontent.com/2991381/32005984-e473ae1a-b9a5-11e7-8109-6c96c2aa88a3.png)

**Comment by Mackiovello** [comment] 2017-10-25 17:25
The firewall warnings are tracked here: https://github.com/Starcounter/level1/issues/1939

**Comment by andwah** [comment] 2017-10-31 12:59
Just got this same problem on a Windows Server 2012 RC Machine. installing starcounter RC 2.3.1.7581

![image](https://user-images.githubusercontent.com/2656996/32224961-b330b3b4-be43-11e7-9cb7-031c04170559.png)

**Comment by andwah** [comment] 2017-10-31 13:07
Solution is to download and install

**Microsoft Visual C++ 2010 Redistributable Package (x86)**

https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555

Note.. i think that starcounter only installs the x64 bit version. not the x86 one.

**Comment by ubbeK** [comment] 2017-10-31 13:07
So what solution should we go for?

- Add MSVCR100.dll to installer
- Add VC++ 10 Redist to installer
- Create an msi installer which may contain prerequisites such as VC++ 10 Redist

**Comment by alemoi** [comment] 2017-10-31 13:08
Its another reason why I wanted embedded Prolog done by @bigwad to be pushed in 2.3 as well :)
One solution is to build this sqlparser on the same VS as the rest of SC.
Another is to include needed DLLs in distribution.

**Comment by ubbeK** [comment] 2017-10-31 13:11
> One solution is to build this sqlparser on the same VS as the rest of SC.

Is that a big job?

**Comment by alemoi** [comment] 2017-10-31 13:20
I did that before but don't remember the details, i.e. where the code is for the Prolog parser. I however think we should merge @bigwad work into 2.3... CC @miyconst @dan31

**Comment by bigwad** [comment] 2017-10-31 13:40
Adding merge module would be easiest and safest, but we don't package installer as an msi. Or we have plans on that?

Next option would be adding required modules to the installation package directly.

Quote from [documentation](https://msdn.microsoft.com/en-us/library/ms235299(v=vs.100).aspx)
>To deploy Visual C++ redistributable files, you can use the Visual C++ Redistributable Package (VCRedist_x86.exe, VCRedist_x64.exe, or VCRedist_ia64.exe) that is included in Visual Studio, or use Redistributable Merge Modules, or you can directly install specific Visual C++ DLLs to the application local folder. An application local folder is a folder that contains an executable application file. DLLs must be deployed to the application local folder.

As to other options. Backporting QP to 2.3 may cause regression and compatibility issues. Recompiling of sqlparser seems safe, but since we don't have established procedure to do so - it might be time-consuming and also cause regression.

**Comment by ubbeK** [comment] 2017-11-01 15:03
> Adding merge module would be easiest and safest, but we don't package installer as an msi. Or we have plans on that?

There is a plan for it, but it is currently not prioritized. 

We used to ship Starcounter installer with `msvcr110.dll` but it got removed, see https://github.com/Starcounter/level1/issues/4269

**Comment by bigwad** [comment] 2017-11-01 15:08
>We used to ship Starcounter installer with msvcr110.dll but it got removed, see Starcounter/level1#4269

Didn't know that. Then if it's just a one-month-old regression, I would say - just put it back for 2.3 (don't think we need it in 2.4) and that's it.

**Comment by ubbeK** [comment] 2017-11-01 15:15
Maybe, note that the error states `msvcr100.dll` though.

**Comment by ubbeK** [comment] 2017-11-13 22:43
`mscvr100.dll` has been readded to `%StarcounterBin%/32BitComponents` for `v2.3` branch. Will be available next RC nightly build.

Closing

**Closed by ubbeK** 2017-11-13 22:43 UTC
Labels: bug
