### ISSUE TITLE
XFilePathHeader database config option does not work

### ISSUE THREAD

**Issue by warpech** [Starcounter/Home#118] opened 2017-05-18 13:53 UTC
The `XFilePathHeader` option explained in https://docs.starcounter.io/guides/database/database-configuration/ seems not to work. I have tried with KitchenSink, both by editing the `Default.db.config` file and in runtime by calling `http://localhost:8181/sc/default/SetFlag/XFilePathHeader/True`

Starcounter 2.3.1.6433

Discovered today by @joozek78 

cc @alemoi

**Comment by mmnosek** [comment] 2017-05-18 14:00
Have you restarted the server?

**Comment by joozek78** [comment] 2017-05-18 14:24
yes

**Comment by alemoi** [comment] 2017-05-18 16:30
I tested and the actual flag setting works and it was working before, so @joozek78 can explain the scenario please? Are you sure you flushed the static files cache?

**Comment by joozek78** [comment] 2017-05-18 22:06
You mean some starcounter cache? No. If you mean browser cache, then AFAIK
when developer tools are on, the cache is skipped.
I set the value according to the docs article. I opened a page and looked
for the header in developer tools / network tab. I found none

**Comment by warpech** [comment] 2017-05-19 09:03
### Steps to reproduce

1. Open file in editor `C:\db\Personal\Databases\Default\Default.db.config` (or whatever is your path to that file).
2. Set the value of `<XFilePathHeader>` to `true` (in the `<Runtime>` section).
3. Run `staradmin stop db`
4. Run `staradmin start db`
5. Start any app (might be KitchenSink or HelloWorld)
6. Check the response headers of the GET request `http://localhost:8080/sys/starcounter.html`.

In Google Chrome Dev Tools, or with cURL:

```
curl -i localhost:8080/sys/starcounter.html
```
![2017-05-19 11_01_30-command prompt](https://cloud.githubusercontent.com/assets/566463/26240783/8a9b92c2-3c82-11e7-97c8-6513cf02ea9c.png)

### Expected

You should see `X-File-Path` among the response headers

### Actual 

`X-File-Path` is missing

**Comment by alemoi** [comment] 2017-05-19 11:41
Great @warpech I will check now.

**Comment by alemoi** [comment] 2017-05-19 13:17
Just tested the above scenario plus via `http://localhost:8181/sc/default/SetFlag/XFilePathHeader/True`, both work well for me. Can you call me on hangouts, @warpech so I can check with your remote?

**Comment by warpech** [comment] 2017-06-01 10:49
It was discussed between @alemoi and me on the Hangouts. The `XFilePathHeader` is actually set and read correctly, but the problem is with static files caching, which is not flushed after `XFilePathHeader` state is changed.

**Comment by alemoi** [comment] 2017-06-02 14:51
I will link an issue here where I want to remove support for `SetFlag` completely. 
https://github.com/Starcounter/level1/issues/4222

**Comment by miyconst** [comment] 2019-12-06 11:08
Closing as won't fix in Starcounter 2 and the issue is not applicable for the upcoming Starcounter 3.

**Closed by miyconst** 2019-12-06 11:08 UTC
Labels: bug, required, won’t fix
