### ISSUE TITLE
Client side text selection behaves strangely

### ISSUE THREAD

**Issue by rogeralsing** [Starcounter/Home#158] opened 2017-06-20 13:50 UTC
e.g. when opening the sign-in form, if you select the text in the username input:
![image](https://user-images.githubusercontent.com/647031/27336260-438d24ac-55cf-11e7-8e3c-b2437d8d6109.png)

And release the mousebutton outside of the form, the login form will close.
That is, if you select from left to right and release too far out, or in the other direction. it closes the form.

There are similar issues, e.g. when selecting text in the Sql Resultset grid.
if you try to select the text in a cell and accidentally move the mousecursor outside the cell, it goes into cell selection mode.
if you move the mouse back into the cell, the text selection is broken.

Small issues, but highly annoying from a UX perspective.

**Comment by Mackiovello** [comment] 2017-06-28 05:55
Good observation @rogeralsing! This is probably an issue with [juicy-popover](https://github.com/Juicy/juicy-popover) somewhere around this line: https://github.com/Juicy/juicy-popover/blob/master/src/juicy-popover.html#L135. In general, it's surely about our use of `mousedown` and `mouseup`. 

What do you mean with "Sql Resultset grid"? 

CC @Mihaiii, is this something you would like to take a look at?

**Comment by rogeralsing** [comment] 2017-06-28 07:07
There is a case of "normal browser text selection" and SQL Grid result selection going on at the same time.
Trying to select the text in a cell from start to end is not always as easy as one could wish.

![image](https://user-images.githubusercontent.com/647031/27622618-8063def2-5bd8-11e7-99a7-f88b5dbb9428.png)

**Comment by Mackiovello** [comment] 2017-06-29 12:33
@Mihaiii is this fixed now?

**Comment by Mackiovello** [comment] 2017-06-29 12:50
The issue in OP is fixed, the apps now have to be updated to include the change.

With the issue in https://github.com/Starcounter/Home/issues/158#issuecomment-311575790, I understand this to be the problem: 
![tableselection](https://user-images.githubusercontent.com/19392292/27688189-063c11d2-5cda-11e7-9f2f-f7b4c89b6b40.gif)
In essence, you try to select the text but end up selecting the cells. Is that right? It seems to be a handsontable issue. CC @warpech

**Comment by warpech** [comment] 2017-06-29 13:42
@Mackiovello what is presented on your screenshot, is not a bug but a feature that was requested at a time. Handsontable mimics a spreadsheet like interface. In a spreadsheet, you select complete cells. On top of that, it is configured to allow selecting text within a single cell (unless you drag the text selection out of that cell).

What I can see in @rogeralsing's screenshot is different. That should probably be fixed, but we will have to ask Handsontable guys for help.

**Comment by rogeralsing** [comment] 2017-06-29 13:54
@warpech I think they might be related.

If you do select text, and for whatever reason go outside the cell, the grid goes into grid selection mode, dropping the text selection.
The problem arise if you didn't intend to go outside the cell, personally I'm a touchpad user and it's easy to wobble a bit when selecting.
It becomes hard sometimes to select a full word from start to end w/o going outside the cell.

When going back into the cell, the text selection seems to start from some random position or as in my screenshot, totally random of the whole grid.

**Comment by warpech** [comment] 2017-06-29 14:41
Got it. 

Let's perhaps label it as "Administrator" and get back to it when we are working full throttle on Administrator tool.

**Comment by Mihaiii** [comment] 2017-10-29 19:26
> The issue in OP is fixed, the apps now have to be updated to include the change.
> 
> With the issue in https://github.com/Starcounter/Home/issues/158#issuecomment-311575790, I understand this to be the problem: 
> ![tableselection](https://user-images.githubusercontent.com/19392292/27688189-063c11d2-5cda-11e7-9f2f-f7b4c89b6b40.gif)
> In essence, you try to select the text but end up selecting the cells. Is that right? It seems to be a handsontable issue. CC @warpech 

In most cases I suppose double click is used for selecting the content of a cell.
I can disable selection of multiple cells and then the result would be like this:

![handsontableselect](https://user-images.githubusercontent.com/8951553/32147407-158bf4c8-bce7-11e7-907f-b38447b673d8.gif)

Would this be an acceptable solution?

**Comment by Mihaiii** [comment] 2017-10-30 13:16
Closing as done.

**Closed by Mihaiii** 2017-10-30 13:16 UTC
Labels: bug, nice to have, tools, tools-admin-ui
