### ISSUE TITLE
⏰ IS NOT NULL does not work with Nullable<DateTime> values

### ISSUE THREAD

**Issue by erikvk** [Starcounter/Home#260] opened 2017-10-04 07:36 UTC
Checking `IS NOT NULL` in SQL does not seem to work for nullable DateTime  properties like `MatchedAt`. `Model` is string, and `IS NOT NULL` works fine there

![screen shot 2017-10-04 at 09 33 42](https://user-images.githubusercontent.com/16880339/31164380-34d52264-a8e7-11e7-8b09-57731d500b3a.jpg)
![screen shot 2017-10-04 at 09 33 53](https://user-images.githubusercontent.com/16880339/31164383-34f678ec-a8e7-11e7-97f1-6e8a28d0ad22.jpg)

**Comment by erikvk** [comment] 2017-10-04 07:39
Version=2.3.1.6402

**Comment by erikvk** [comment] 2017-10-04 08:30
I also suspect that indexing does not work properly for nullable datetime properties. That would explain some performance issues we have had.

**Comment by erikvk** [comment] 2017-10-04 10:22
I think I have a work-around for the SQL issue. These two SQL queries should be equivalent, no?

1: `SELECT * FROM Mopedo.Database.Device t WHERE t.MatchedAt IS NOT NULL`
2: `SELECT * FROM Mopedo.Database.Device t WHERE t.MatchedAt > DATE '0001-01-01'`

**Comment by k-rus** [comment] 2017-10-04 13:13
Thank you for reporting! It looks like a bug. It can be in code host or in OldSQL. We will investigate.

**Comment by un-tone** [comment] 2018-01-23 17:18
Can't reproduce this bug with the following program: https://gist.github.com/un-tone/6a1518bf4412de3b98b89d0d6312aba7
Checked in 2.3.0.6350 and 2.3.2.141. I'm not finished.

**Comment by un-tone** [comment] 2018-01-24 13:18
I tried some variations and it is still not reproducible for me. Also checked in more old 2.3.0.5943.

cc @miyconst

**Comment by miyconst** [comment] 2018-01-24 13:31
@erikvk can you still reproduce the issue? In the original issue, were there any indexes on the problematic field?

**Comment by un-tone** [comment] 2018-01-24 13:35
> In the original issue, were there any indexes on the problematic field?

Just to be clear, I tried with indexes and without them.

**Comment by miyconst** [comment] 2018-01-24 13:40
>Just to be clear, I tried with indexes and without them.

There may be some specific situations, for example the property is defined in a parent class, while the index is defined on the child class. So, still need a confirmation from @erikvk.

**Comment by erikvk** [comment] 2018-01-24 13:43
I cannot reproduce the issue on my current version, (Version=2.3.2.90), which is good I suppose

**Comment by erikvk** [comment] 2018-01-24 13:44
There is no inheritance relations on this class. Here is the definition, for reference:

```c#
using System;
using System.Linq;
using System.Net;
using Mopedo.Bidding;
using Mopedo.ClientData;
using Newtonsoft.Json;
using RESTar;
using Starcounter;
using static Mopedo.Base.DbTools.Transactions;

namespace Mopedo.Database
{
    /// <summary>
    /// The Device resource contains information about a device, for example a
    /// mobile phone, on the Mopedo platform.
    /// </summary>
    [Database, RESTar(Description = description)]
    public class Device : IDataSource, IDatabaseResource, IEntity
    {
        private const string description = "The Device resource contains information about " +
                                           "a device, for example a mobile phone, on the Mopedo platform.";

        internal const string All = "SELECT t FROM Mopedo.Database.Device t";
        internal const string ByIP = All + " WHERE t.IP =?";
        internal const string ByMatchedAndIP = All + " WHERE t.Matched =? AND t.IP =?";


        /// <summary>
        /// The IP address of this Device. Used as unique ID
        /// </summary>
        [RESTarMember(key: true)]
        public string IP { get; }

        /// <summary>
        /// The browser user agent of this device
        /// </summary>
        public string BrowserUserAgent { get; internal set; }

        /// <summary>
        /// Geographic information about this device
        /// </summary>
        public Geo Geo { get; internal set; }

        /// <summary>
        /// Has this device asked to not be tracked?
        /// </summary>
        public bool? DoNotTrack { get; internal set; }

        /// <summary>
        /// ID sanctioned for advertiser use
        /// </summary>
        public string Ifa { get; internal set; }

        /// <summary>
        /// The type of device.
        /// 1 = Mobile/Tablet,
        /// 2 = Personal Computer,
        /// 3 = Connected TV,
        /// 4 = Phone,
        /// 5 = Tablet,
        /// 6 = Connected Device,
        /// 7 = Set Top Box
        /// </summary>
        public int? DeviceType { get; internal set; }

        /// <summary>
        /// The name of the device maker
        /// </summary>
        public string Make { get; internal set; }

        /// <summary>
        /// The name of the device model
        /// </summary>
        public string Model { get; internal set; }

        /// <summary>
        /// The name of the device operating system
        /// </summary>
        public string OperatingSystem { get; internal set; }

        /// <summary>
        /// The version of the device operating system
        /// </summary>
        public string OperatingSystemVersion { get; internal set; }

        /// <summary>
        /// Is JavaScript supported on this device?
        /// </summary>
        public bool? JavaScriptSupported { get; internal set; }

        /// <summary>
        /// What version of flash is supported (if any)
        /// </summary>
        public string FlashVersionSupported { get; internal set; }

        /// <summary>
        /// The browser language
        /// </summary>
        public string Language { get; internal set; }

        /// <summary>
        /// The name of the device carrier (if any)
        /// </summary>
        public string Carrier { get; internal set; }

        /// <summary>
        /// The type of the connection.
        /// 0 = Unknown
        /// 1 = Ethernet
        /// 2 = WIFI
        /// 3 = Cellular Network – Unknown Generation
        /// 4 = Cellular Network – 2G
        /// 5 = Cellular Network – 3G
        /// 6 = Cellular Network – 4G
        /// </summary>
        public int? ConnectionType { get; internal set; }

        /// <summary>
        /// Device ID hashed using SHA1
        /// </summary>
        public string SHA1HashedDeviceId { get; internal set; }

        /// <summary>
        /// Device ID hashed using MD5
        /// </summary>
        public string MD5HashedDeviceId { get; internal set; }

        /// <summary>
        /// Platform ID hashed using SHA1
        /// </summary>
        public string SHA1HashedPlatformId { get; internal set; }

        /// <summary>
        /// Platform ID hashed using MD5
        /// </summary>
        public string MD5HashedPlatformId { get; internal set; }

        /// <summary>
        /// The DeviceExtension entity corresponding to this object (if any)
        /// </summary>
        public DeviceExtension Extension
        {
            get => Db.SQL<DeviceExtension>(DeviceExtension.ByDevice, this).FirstOrDefault();
            set
            {
                if (value == null) Extension?.Delete();
                else value["IP"] = IP;
            }
        }

        internal bool matched;

        /// <summary>
        /// Has this device been matched?
        /// </summary>
        public bool Matched
        {
            get => matched;
            set
            {
                if (value)
                    MatchedAt = DateTime.Now;
                else MatchedAt = null;
                matched = value;
            }
        }

        /// <summary>
        /// The date and time when this device was matched, or null if not matched
        /// </summary>
        public DateTime? MatchedAt { get; private set; }

        /// <summary>
        /// Creates a new device object
        /// </summary>
        [JsonConstructor]
        public Device(string ip)
        {
            ip = ip?.Trim() ?? "";
            if (!IPAddress.TryParse(ip, out IPAddress _))
                throw new Exception("Missing or invalid IP address format");
            if (Db.SQL<Device>(ByIP, ip).Any())
                throw new Exception($"A Device with IP '{ip}' already exists.");
            IP = ip;
            this.CreatedNow();
        }

        // ReSharper disable once UnusedParameter.Local
        private Device(string _ip, object x = null)
        {
            IP = _ip;
            this.CreatedNow();
        }

        /// <summary>
        /// The date and time when this object was created
        /// </summary>
        [RESTarMember(readOnly: true)] public DateTime CreatedAt { get; set; }

        /// <summary>
        /// The date and time when this object was last involved in a bid request
        /// </summary>
        [RESTarMember(readOnly: true)] public DateTime UsedAt { get; set; }

        /// <summary>
        /// The number of times this object has been involved in a bid request
        /// </summary>
        [RESTarMember(readOnly: true)] public long UsedCount { get; set; }

        /// <summary>
        /// The activity rank (among Devices)
        /// </summary>
        [RESTarMember(readOnly: true)] public long UsedRank { get; set; }

        /// <summary>
        /// Gets the value of a certain property
        /// </summary>
        public dynamic GetValue(int index, string name)
        {
            switch ((DeviceProp) index)
            {
                case DeviceProp.IP: return IP;
                case DeviceProp.BrowserUserAgent: return BrowserUserAgent;
                case DeviceProp.DoNotTrack: return DoNotTrack;
                case DeviceProp.Ifa: return Ifa;
                case DeviceProp.DeviceType: return DeviceType;
                case DeviceProp.Make: return Make;
                case DeviceProp.Model: return Model;
                case DeviceProp.OperatingSystem: return OperatingSystem;
                case DeviceProp.OperatingSystemVersion: return OperatingSystemVersion;
                case DeviceProp.JavaScriptSupported: return JavaScriptSupported;
                case DeviceProp.FlashVersionSupported: return FlashVersionSupported;
                case DeviceProp.Language: return Language;
                case DeviceProp.Carrier: return Carrier;
                case DeviceProp.ConnectionType: return ConnectionType;
                case DeviceProp.SHA1HashedDeviceId: return SHA1HashedDeviceId;
                case DeviceProp.MD5HashedDeviceId: return MD5HashedDeviceId;
                case DeviceProp.SHA1HashedPlatformId: return SHA1HashedPlatformId;
                case DeviceProp.MD5HashedPlatformId: return MD5HashedPlatformId;
                case DeviceProp.WinCount: return this.WinCount(name);
                case DeviceProp.ClickCount: return this.ClickCount(name);
                case DeviceProp.CreatedAt: return CreatedAt;
                case DeviceProp.UsedAt: return UsedAt;
                case DeviceProp.Matched: return Matched;
                case DeviceProp.MatchedAt: return MatchedAt;
                case DeviceProp.UsedCount: return UsedCount;
                case DeviceProp.UsedRank: return UsedRank;
                default: throw new ArgumentOutOfRangeException();
            }
        }

        /// <inheritdoc />
        public void OnDelete() => Extension?.Delete();

        internal static bool TryGetMatched(string ip, out Device found)
        {
            found = Db.SQL<Device>(ByMatchedAndIP, true, ip).FirstOrDefault();
            return found != null;
        }

        internal static Device GetOrMake(string ip) => Db.SQL<Device>(ByIP, ip).FirstOrDefault()
                                                       ?? Insert(() => new Device(_ip: ip));

        /// <summary>
        /// Gets the type for a certain property
        /// </summary>
        public static Type PropertyType(int index, string name)
        {
            switch ((DeviceProp) index)
            {
                case DeviceProp.IP: return typeof(string);
                case DeviceProp.BrowserUserAgent: return typeof(string);
                case DeviceProp.DoNotTrack: return typeof(bool?);
                case DeviceProp.Ifa: return typeof(string);
                case DeviceProp.DeviceType: return typeof(int?);
                case DeviceProp.Make: return typeof(string);
                case DeviceProp.Model: return typeof(string);
                case DeviceProp.OperatingSystem: return typeof(string);
                case DeviceProp.OperatingSystemVersion: return typeof(string);
                case DeviceProp.JavaScriptSupported: return typeof(bool?);
                case DeviceProp.FlashVersionSupported: return typeof(string);
                case DeviceProp.Language: return typeof(string);
                case DeviceProp.Carrier: return typeof(string);
                case DeviceProp.ConnectionType: return typeof(int?);
                case DeviceProp.SHA1HashedDeviceId: return typeof(string);
                case DeviceProp.MD5HashedDeviceId: return typeof(string);
                case DeviceProp.SHA1HashedPlatformId: return typeof(string);
                case DeviceProp.MD5HashedPlatformId: return typeof(string);
                case DeviceProp.WinCount: return typeof(int);
                case DeviceProp.CreatedAt: return typeof(DateTime);
                case DeviceProp.UsedAt: return typeof(DateTime);
                case DeviceProp.ClickCount: return typeof(int);
                case DeviceProp.Matched: return typeof(bool);
                case DeviceProp.MatchedAt: return typeof(DateTime?);
                case DeviceProp.UsedCount: return typeof(long);
                case DeviceProp.UsedRank: return typeof(long);
                default: throw new ArgumentOutOfRangeException(nameof(index), index, null);
            }
        }
    }
```

**Comment by erikvk** [comment] 2018-01-24 13:46
There was an index on the nullable datetime `MatchedAt` earlier, but not in the version I run now.

**Comment by miyconst** [comment] 2018-01-24 13:47
>I cannot reproduce the issue on my current version, (Version=2.3.2.90), which is good I suppose

Thank you for the confirmation. Please make sure that you test the same conditions as of the time of the bug report, but with newer Starcounter version. Class definitions, indexes, inheritance should be as close as possible to the original.

**Comment by un-tone** [comment] 2018-01-24 15:13
Checked the model from @erikvk's last comment in SC 2.3.1.8329 and 2.4.0.4671. The bug is still not reproducible.

**Comment by miyconst** [comment] 2018-01-24 15:15
@un-tone thanks for checking it, closing the issue for now. @erikvk please reopen if you can reproduce it again.

**Closed by miyconst** 2018-01-24 15:15 UTC
Labels: bug, desired, qp, qp-old
